### ISSUE TITLE
Method of tracing calls to replica/shards for Sequel

### ISSUE THREAD

**Issue by mscrivo** [DataDog/dd-trace-rb#1044]
Sequel has the ability to seamlessly work with shards over the same database object. The most common scenario is using it with a simple primary/replica scenario. As per the [docs](https://github.com/jeremyevans/sequel/blob/master/doc/sharding.rdoc), the simplest way to do this is like this: 
```ruby
DB=Sequel.connect('postgres://primary_server/database', 
  servers: {read_only: {host: 'replica_server'}})
```
And that will send all select queries to the replica.

We actually define our replica as a shard, and specify `DB.server(:replica)` whenever we want a specific query to go to the replica, as we don't want to send all selects there.

Datadog's sequel integration lacks the ability to configure the database tracing to pick up on which shard the query is going to, whether it's primary, replica or whatever other custom shards you may have. From the docs, the only thing you can do is:

```ruby
Datadog.configure(postgres_database, service_name: 'my-postgres-db')
```

I've tried hacking this by patching sequel's `synchronize(server=nil)` method and doing the configuration there, but this is not a good solution for a few reasons: not thread safe, so it sometimes gives false results, and secondly it's inefficient as we're configuring DD on every call. 

It would be super nice to support this in a clean, efficient way.

**Comment by mculp** [comment]
Unfortunately, we have the same issue. Thanks for posting this. Thought I was going crazy.

**Comment by mscrivo** [comment]
Note, since the pg tracing has been added, there is not a round-about way of seeing the correct DB being queried. Look at the pg span beneath your sequel span and the `network.destination.name` tag should have the correct DB/shard being hit.

**Comment by mscrivo** [comment]
Closing as the pg span now has the necessary info
