### ISSUE TITLE
Feature request: support for qless

### ISSUE THREAD

**Issue by sco11morgan** [DataDog/dd-trace-rb#1053]
[qless](https://github.com/seomoz/qless) is Redis-based job queueing system inspired by Resque.

qless supports Resque-like [middleware hooks](https://github.com/seomoz/qless#per-job-middlewares) such as `around_perform` so presumably the existing DataDog support for Resque could be re-used.

**Comment by delner** [comment]
@sco11morgan Thanks for the request! We'll bring it up with the team and see how it fits into the schedule.

In the meantime we welcome any contributions if you felt inspired to do so. The middleware hooks might be a great way to implement this.

**Comment by sco11morgan** [comment]
@delner I've started working on a contribution for instrumenting Qless jobs that is very similar to the Resque work.  One part I'm stuck on is how to write specs using a tracer that is available across both the parent and forked job process.  The Resque specs in ddtrace don't actually use a forked process.  This call to [`worker.perform`](https://github.com/DataDog/dd-trace-rb/blob/master/spec/ddtrace/contrib/resque/job.rb#L10) should really call [`worker.work_one_job`](https://github.com/resque/resque/blob/d780aa4cb9bc2239abb026ac483aadb6bccf9640/lib/resque/worker.rb#L258-L272) to truly test the fork code. (And if you change the call you'll see the same error messages I get)

Can you recommend a tracer to use for testing across processes?  Thanks

**Comment by marcotc** [comment]
Hey @sco11morgan, sorry for the wait!

We have a helper to help us test forked code paths, `expect_in_fork`: https://github.com/DataDog/dd-trace-rb/blob/61ef72b7df6b46061e4e00e0e278deb03a7683c5/spec/ddtrace/workers/async_spec.rb#L394-L407

You can perform any RSpec assertions in side the forked path and if they fail (thus casing the forked process to return non-zero), the `expect_in_fork` method will error as well. The error propagated back to the parent process wont' be rich, but the original rich output will be printed to your terminal.

If you need rich communication between forked child and parent, you'll have to resort to [passing information over a pipe](https://ruby-doc.org/core-2.0.0/IO.html#method-c-pipe). This method is mostly manual, and yields harder-to-read code, so 🤞 `expect_in_fork` works here!

**Comment by marcotc** [comment]
@sco11morgan add this support in [v0.44.0](https://github.com/DataDog/dd-trace-rb/milestone/83), long time ago.
Thank you once again, @sco11morgan!
