### ISSUE TITLE
What may cause a lot of "Cause: execution expired" errors?

### ISSUE THREAD

**Issue by KIVagant** [DataDog/dd-trace-rb#1056]
We use `datadog/agent:6.13.0` deployed with the Helm chart `chart: datadog-1.32.1-48647cb`. On the application side we use `ddtrace-0.35.2` gem, the latest as I suppose.

After increasing the cluster payload we started getting many errors (~20 per minute) like this:

```
E, [2020-05-27T18:38:57.084572 #32] ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.35.2/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: execution expired Location: /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
```

After some digging I also found that other our clusters with the similar setup also have the issue. I checked memory and CPU usage of datadog containers: CPU is less than **1%**, memory is up to 350MB per container when the available memory is 512MB for each.

There are no errors in logs right now. We had had many warnings like `Unable to parse container: can't extract an entity ID from container ID` but when I restarted all the pods, they almost disappeared (another offtopic question is what they were about?). But the main issue is still there, so the warning is probably unrelated.

Does the error sound familiar to anyone? Any idea where do I need to look to find the root cause? Also I'm not expecting this to be a networking issue, since there are no other similar issues we see in that cluster that could indicate this.

**Comment by marcotc** [comment]
Hi @KIVagant, thank you for the issue report.
> After increasing the cluster payload we started getting many errors

Are we talking about individual payload sizes for your application, or an increasing in the number of requests?

> `E, [2020-05-27T18:38:57.084572 #32] ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.35.2/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: execution expired Location: /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize'`

[This error](https://github.com/ruby/ruby/blob/v2_6_0/lib/net/http.rb#L947) happenes when `net/http` tries to connect to the agent instance, but fails to complete the TCP handshake within the allocated timeout. This is in contrast with taking too long to send the payload data, which is not the case here: the connection socket was never successfully open. My guess is that this is cause by too many Datadog tracers trying to connect to the same agent, which might be for you too look into in your infrastructure. The default connection limit [seems](https://github.com/DataDog/documentation/blame/064b631/content/en/agent/docker/apm.md#L80) to [be 2000](https://github.com/DataDog/datadog-agent/blob/5bbf3408b9e526f6227fec49644fbe13fd80b1e4/pkg/trace/config/config.go#L136) as it is configurable through `DD_APM_CONNECTION_LIMIT` to the best of my knowledge.

Regarding `Unable to parse container: can't extract an entity ID from container ID`, that error comes from the [datadog agent](https://github.com/DataDog/datadog-agent), I recommend you open an issue there if this specific issue persists: https://github.com/DataDog/datadog-agent/issues

**Comment by KIVagant** [comment]
@marcotc , thank you for the explanation. Sorry for late response, I have actually found the cause of the issue. It turned out that we had Linkerd proxy between an application and a Datadog agent. After we filtered out DD ports in the proxy, the error disappeared.
