### ISSUE TITLE
0.36.0 stops services with custom names to show up in time spend

### ISSUE THREAD

**Issue by kramuenke** [DataDog/dd-trace-rb#1058]
Hi all,

after updating to 0.36.0 instrumentation with custom service names stop showing in time spend graphs for our rails app.

e.g. `Datadog.configure { |c| c.use :http, service_name: 'myapp-net/http' }`

<img width="675" alt="Screen Shot 2020-05-29 at 10 12 03 AM" src="https://user-images.githubusercontent.com/469886/83206935-5cf54b80-a195-11ea-9a91-90a9d1865e79.png">

default instrumentation remains, like the mysql instrumentation that comes with using `c.use :rails`.

**Comment by delner** [comment]
We have an outstanding configuration issue that may be related to this; I will advise holding back to the last stable version in the meantime. When we have a PR up to address the issue, I'll share that with you so we can see if that helps.

**Comment by delner** [comment]
We've opened #1072 to track "stale tracers" which we think is the source of this issue. I'm going to close this issue for now and move the discussion over there. When we get a PR fix up, if said fix doesn't fully resolve this issue, we can re-open this issue again and address its individual circumstances.
