### ISSUE TITLE
Getting Started not up-to-date

### ISSUE THREAD

**Issue by DocX** [DataDog/dd-trace-rb#1066]
Hi. I've noticed some stuff is not up-to-date in the Getting Started docs.

I made two PRs with changes:
* #1060 
* #1059 

Can someone please review them? Thank you

**Comment by marcotc** [comment]
Hey @DocX, thank you for your recent contributions!

I'm closing this issue was both PRs mentioned have been attended to.

I've added one follow up feature proposal for your issue related to context propagation across threads: https://github.com/DataDog/dd-trace-rb/issues/1202
