### ISSUE TITLE
Datadog tracer set_tags not setting tags on root span

### ISSUE THREAD

**Issue by KaleFive** [DataDog/dd-trace-rb#1067]
`Datadog.tracer.set_tags(key, value)` not working as expected

Hello, I am using Datadog with my ruby Sidekiq workers.

My Sidekiq workers pull from the queue and do their work. Currently, there is no way for me to identify which worker was run for which customer, the auto instrumentation cannot take care of that.

So instead - the job has the `customer_id` in the job arguments. so when the Sidekiq worker plucks a job off the queue, I parse the job arguments for a `customer_id` and then i set the Datadog trace tag at this point via [Sidekiq Server Middleware](https://github.com/mperham/sidekiq/wiki/Middleware).

In the middleware I am using `Datadog.tracer.set_tags(key, value)`, however I am noticing a strange behavior. The children spans will always get the tags, but the root span of the trace will only **_sometimes_** get the tag.

If I use `Datadog.tracer.active_root_span.set_tag(key, value)`, the children spans do not get the tags, but the root span of the trace will almost always get the tag.

Tried different versions of the gem (`0.24`, `0.34.2`, `0.36`), no luck. 

**Below screenshots are from the same trace when using `Datadog.tracer.set_tags`**

**when selecting the root span**
![Screen Shot 2020-06-04 at 11 54 38 PM](https://user-images.githubusercontent.com/11951665/83835567-1df85600-a6bf-11ea-9d4e-17da066ad919.png)

**when selecting any children span**
![Screen Shot 2020-06-04 at 11 54 52 PM](https://user-images.githubusercontent.com/11951665/83835581-2781be00-a6bf-11ea-876b-0150b440d624.png)

**Comment by marcotc** [comment]
👋 @KaleFive, sorry I missed this issue, but we've released [0.37.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.37.0) which includes fixes that should address your scenario. Give it a try and let us know if the problem still persists.

**Comment by marcotc** [comment]
@KaleFive, just a friendly bump, as other issues with the same symptoms have been addressed since 0.37.0.

**Comment by delner** [comment]
@KaleFive it looks like this one has been addressed, so I'm going to close this. Please feel free to let us know if there's more to do here!
