### ISSUE TITLE
0.36.0 regression `Datadog.tracer.active_correlation` is not set for Rails requests 

### ISSUE THREAD

**Issue by jeffblake** [DataDog/dd-trace-rb#1069]
With 0.36.0, I'm always getting 0 for span_id and trace_id from ``Datadog.tracer.active_correlation`` when logging rack (rails) requests.

Downgrading to 0.35.2 works, the ID's are present.

**Comment by delner** [comment]
Hey @jeffblake you could try out https://github.com/DataDog/dd-trace-rb/pull/1064 to see if it helps. This is a known issue for Rails in 0.36.0 and we're working on a more comprehensive solution for it.

**Comment by delner** [comment]
We've opened #1072 to track "stale tracers" which we think is the source of this issue. I'm going to close this issue for now and move the discussion over there. When we get a PR fix up, if said fix doesn't fully resolve this issue, we can re-open this issue again and address its individual circumstances.
