### ISSUE TITLE
Show Method and Url in resource_name for Faraday

### ISSUE THREAD

**Issue by linqueta** [DataDog/dd-trace-rb#1077]
I really would like to have the method and url in resource_name for Faraday requests.

I've tried to change this line https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/faraday/middleware.rb#L67 using a `class_eval` but I didn't have success. 

Is there any way to do it?

**Comment by rafaelsales** [comment]
Is this a dup of https://github.com/DataDog/dd-trace-rb/issues/277?

**Comment by linqueta** [comment]
I've done it forking the repo.
