### ISSUE TITLE
Web transaction spans disappeared after upgrade

### ISSUE THREAD

**Issue by pacoguzman** [DataDog/dd-trace-rb#1078]
Hi there,

After the migration from 0.26.0 to 0.36.0 we lost from the web services traces all the internal span which are not related with active record and dalli/cache.

We have internal instrumentation which we can have access isolated but not inside web traces. We're going to revert to 0.34.2 to try if that version works properly

**Comment by pacoguzman** [comment]
It seems after the downgrade we recover the internal spans, so the problem must be between 0.34.2 and 0.36.0

**Comment by rafaelsales** [comment]
I started using Datadog just a week ago and had killed many hours trying to figure out how to get internal spans for activerecord, mysql, cache, etc from worker analyzed spans. Could this be related?
Example:
![image](https://user-images.githubusercontent.com/1196663/84612301-9c5eb000-ae96-11ea-95fd-f0343383cd5a.png)

This worker makes many AR/DB calls, and none appears in the internal spans.

Btw, this is my config:
```
# gem 'ddtrace', '0.36.0'

Datadog.configure do |c|
  c.use :rails, analytics_enabled: false, service_name: 'backend'
  c.use :rack, analytics_enabled: true
  c.use :sidekiq, analytics_enabled: true, service_name: 'backend-sidekiq', tag_args: true
  c.use :grpc, analytics_enabled: true, service_name: 'backend-grpc'
end
```

**Comment by rafaelsales** [comment]
I was able to make it work by downgrading to 0.34.2 without changing anything in the config:

![image](https://user-images.githubusercontent.com/1196663/84614758-7983ca00-ae9d-11ea-8b78-4c4335909027.png)

**Comment by pacoguzman** [comment]
@rafaelsales thanks for checking with newer versions

**Comment by delner** [comment]
We've opened #1072 to track "stale tracers" which we think is the source of this issue. I'm going to close this issue for now and move the discussion over there. When we get a PR fix up, if said fix doesn't fully resolve this issue, we can re-open this issue again and address its individual circumstances.
