### ISSUE TITLE
http.rb tracer raises "HTTP::StateError: body is being streamed" on failure responses

### ISSUE THREAD

**Issue by evan-waters** [DataDog/dd-trace-rb#1116]
Using `ddtrace 0.38.0`, we are seeing errors with our `http.rb` responses when enabling the tracer.

Tested with `http.rb` `4.3.0` and `4.4.1`

Configuration:

```
Datadog.configure do |c|
  c.use :httprb,
        analytics_enabled: true,
        service_name: "http-rb-#{ENV['HEROKU_APP_NAME']}"
end
```

We are seeing `HTTP::StateError: body is being streamed` errors on failure responses such as 4xx. When inspecting the response returned by `http.rb`, we are seeing:

`#<HTTP::Response::Body:3fc14efc16c0 @streaming=true>`

Disabling the `httprb` trace in the configuration returns the following response:

`#<HTTP::Response::Body:3ff78f899c90 @streaming=false>`

This appears to only be happening on failure level status codes and is preventing us from properly parsing response bodies.

**Comment by marcotc** [comment]
We had a discussion on https://github.com/DataDog/dd-trace-rb/pull/1117, and it is not safe to read the `http.rb` response body in `ddtrace`: we end up consuming the body reading stream, so the host application cannot properly read it; we could end up with a very large payload in memory (think hypothetically a large download file as the body).

To address this issue we should stop reading the response body altogether. This will remove some information from our error reporting, but it's ultimately required for the safe operation of `ddtrace` with `http.rb`.
