### ISSUE TITLE
undefined method `url' for test transport adapter

### ISSUE THREAD

**Issue by benhutton** [DataDog/dd-trace-rb#1125]
When my tracer transport options are configured as follows:

```
Datadog.configure do |c|
    c.tracer transport_options: proc { |t|
      t.adapter :test
    }
end
```

I receive the following warning:

```
W, [2020-07-28T11:58:29.728607 #258707]  WARN -- ddtrace: [ddtrace] Failed to collect environment information: undefined method `url' for #<Datadog::Transport::HTTP::Adapters::Test:0x000055dc7c1acee0> location: /home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ddtrace-0.38.0/lib/ddtrace/diagnostics/environment_logger.rb:111:in `agent_url'
```

I believe that https://github.com/DataDog/dd-trace-rb/pull/1104/files probably needed to add a `#url` method to https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/transport/http/adapters/test.rb

**Comment by ericmustin** [comment]
@benhutton thanks for the report on this and investigation. Gone ahead and made a PR to address it. https://github.com/DataDog/dd-trace-rb/pull/1131/files , when this is merged/released I'll ping on this issue. 

Please feel free to reach out if you encounter any other issues!
