### ISSUE TITLE
[ActiveJob::SerializationError] Unsupported argument type: Datadog::Span

### ISSUE THREAD

**Issue by rromanchuk** [DataDog/dd-trace-rb#1140]
This must be some magic going on with `def call`, still investigating but posting for visibility  

```ruby
# frozen_string_literal: true

class Service
  private_methods :new

  class << self
    def call(*args)
      new(*args).call
    end

    def async_call(*args)
      ServiceJob.perform_later(to_s, args)      
    end
  end
end
```

**Comment by ericmustin** [comment]
@rromanchuk Thanks for reaching out here. Would you mind giving a little more context here on your issue, I'm not sure I have enough here to reproduce.

Specifically, 
- What instrumentation are you using (do you have a `Datadog.configure` block in your application), if so what does that look like?
- What version of dd-trace-rb are you running here?
- What libraries/frameworks are involved? i believe any instrumentation for `ActiveJob` is from broader instrumentation of `sidekiq`, `delayed_job`, `shoryuken`, etc, so knowing what `ServiceJob` here represents would help narrow things down. Additionally any versions for these libs would help with reproducing.
- Is there a backtrace for this error?
- If you have a minimal reproduction that would be especially useful here.

**Comment by rromanchuk** [comment]
@ericmustin yeah i was going to give you a repo, i just haven't had time yet. 

https://gist.github.com/rromanchuk/0fe5508e512e73ca8028caf6c3a30750


btw, this sounds relevant 

```
Processing Pipeline
Some applications might require that traces be altered or filtered out before they are sent upstream. The processing pipeline allows users to create processors to define such behavior.

Processors can be any object that responds to #call accepting trace as an argument (which is an Array of Datadog::Spans.)
```

**Comment by ericmustin** [comment]
@rromanchuk Thanks for the gist here. I don't believe the processing pipeline is involved here, I think it's more likely something to do with our instrumentation of ActiveSupport but I don't want to jump to any conclusions. Will try to follow up here as soon as I've been able to reproduce and determine some next steps.

**Comment by marcotc** [comment]
👋 @rromanchuk, I'm able to get the same error you are seeing by passing a span object as an argument to an `ActiveJob`:
```ruby
AnyActiveJob.perform_later(Datadog::Span.new(nil, 'foo'))
#> ActiveJob::SerializationError: Unsupported argument type: Datadog::Span
```

In the gist you linked, which was extremely helpful, the issue happens because `current_user` in your example controller is likely a complex object, which is being passed as an argument to the job, which needs to serialize it. The `Datadog::Span` is likely just one of the many components of `current_user`: https://gist.github.com/rromanchuk/0fe5508e512e73ca8028caf6c3a30750#file-application_controller-rb-L6

Did you actually intend on passing `current_user` to the job serializer, or a simpler identifier, like `user_id`?

**Comment by rromanchuk** [comment]
good catch, yeah i was passing the AR object, because you know, lazy developer lol. I just assumed activejob was just wrapping that verbosity with GlobalID. But it def works as is with just tracing disabled, so there's some sort of meta programming that doesn't conform to `GlobalID::Identification`  🤷

**Comment by marcotc** [comment]
Interesting, if `current_user` in your application is an ActiveRecord object it should be [correctly serialized](https://github.com/rails/rails/blob/94d2aef7971d7a1c7e1409dcf1a48cf7b8c2ea0d/activejob/lib/active_job/arguments.rb#L103-L104) as [a `GlobalID::Identification` object that it is](https://github.com/rails/globalid/blob/c54d0f251456acb6122b898c6269ef154fad9118/lib/global_id/railtie.rb#L38). 

I can run the same serialization code Rails runs on ActiveRecord objects:
```ruby
User.first.to_global_id.to_s
#=> "gid://rails6/User/1"
```

The only fields read from the object are [`#class` and `#id`](https://github.com/rails/globalid/blob/5bfe23a8ab3ab49c9050bc3ad0668f5c01492cf6/lib/global_id/uri/gid.rb#L68), so our Span objects should not be at play.

I'm not able to reproduce you issue on completely on my side: I was able to get the same error message by explicitly sending a Span as an argument. But I'm able to correctly pass ActiveRecord instances as arguments, with the same `Datadog.configure` block you provided earlier:
```ruby
class Worker < ActiveJob::Base
  def perform(obj)
    puts "hello from worker: #{obj}"
  end
end

Worker.perform_later(User.first)
#=> hello from worker: #<User:0x00007fb73bdf1250>
```

With this in mind, could you try:
* Print `current_user.to_global_id.to_s` and see what you get back.
* Print `current.class.ancestors` and report the results.
<details><summary>Here's what I get when I call `#.class.ancestors` on my ActiveRecord object:</summary>
<p>

```
User
User::GeneratedAssociationMethods
User::GeneratedAttributeMethods
ActiveRecord::Base
ActionText::Attribute
ActiveStorage::Reflection::ActiveRecordExtensions
ActiveStorage::Attached::Model
GlobalID::Identification
ActiveRecord::Suppressor
ActiveRecord::SecureToken
ActiveRecord::Store
ActiveRecord::Serialization
ActiveModel::Serializers::JSON
ActiveModel::Serialization
ActiveRecord::Reflection
ActiveRecord::NoTouching
ActiveRecord::TouchLater
ActiveRecord::Transactions
ActiveRecord::NestedAttributes
ActiveRecord::AutosaveAssociation
ActiveModel::SecurePassword
ActiveRecord::Associations
ActiveRecord::Timestamp
ActiveRecord::Callbacks
ActiveRecord::AttributeMethods::Serialization
ActiveRecord::AttributeMethods::Dirty
ActiveModel::Dirty
ActiveRecord::AttributeMethods::TimeZoneConversion
ActiveRecord::AttributeMethods::PrimaryKey
ActiveRecord::AttributeMethods::Query
ActiveRecord::AttributeMethods::BeforeTypeCast
ActiveRecord::AttributeMethods::Write
ActiveRecord::AttributeMethods::Read
ActiveRecord::Base::GeneratedAssociationMethods
ActiveRecord::Base::GeneratedAttributeMethods
ActiveRecord::AttributeMethods
ActiveModel::AttributeMethods
ActiveModel::Validations::Callbacks
ActiveRecord::DefineCallbacks
ActiveRecord::Locking::Pessimistic
ActiveRecord::Locking::Optimistic
ActiveRecord::AttributeDecorators
ActiveRecord::Attributes
ActiveRecord::CounterCache
ActiveRecord::Validations
ActiveModel::Validations::HelperMethods
ActiveSupport::Callbacks
ActiveModel::Validations
ActiveRecord::Integration
ActiveModel::Conversion
ActiveRecord::AttributeAssignment
ActiveModel::AttributeAssignment
ActiveModel::ForbiddenAttributesProtection
ActiveRecord::Sanitization
ActiveRecord::Scoping::Named
ActiveRecord::Scoping::Default
ActiveRecord::Scoping
ActiveRecord::Inheritance
ActiveRecord::ModelSchema
ActiveRecord::ReadonlyAttributes
ActiveRecord::Persistence
ActiveRecord::Core
ActiveSupport::Dependencies::ZeitwerkIntegration::RequireDependency
ActiveSupport::ToJsonWithActiveSupportEncoder
Object
ActiveSupport::Dependencies::Loadable
ActiveSupport::Tryable
JSON::Ext::Generator::GeneratorMethods::Object
PP::ObjectMixin
Kernel
BasicObject
```
</p>
</details>

Thank you for you patient @rromanchuk!

**Comment by rromanchuk** [comment]
@marcotc sorry for the delay, let me switch back on and deploy to staging with said debugging

**Comment by rromanchuk** [comment]
<img width="581" alt="Screen Shot 2020-08-24 at 10 43 39 PM" src="https://user-images.githubusercontent.com/102188/91127538-4f981200-e65b-11ea-8d66-42752cb61f1d.png">

Of course, no issue 🤦.  REST request -> DB r/w -> Service Async wrapper -> active job -> zero problems

It's not the exact place/service/environment from before but i'm testing in almost identical scenario,  action controller -> current_user as the only param to `async_call`.  Imma push to production, feels like a user error that was probably sitting right in front of my face but didn't see it at the time.

**Comment by marcotc** [comment]
No worries @rromanchuk, let us know if the issue still persists!

**Comment by rromanchuk** [comment]
@marcotc it's on production, no issues. I should go back and look through commits around that time, if I figure it out ill let you know.  I owe you a beer for wasting your time 🍺
