### ISSUE TITLE
Unable to patch Datadog::Contrib::ActiveModelSerializers::Integration

### ISSUE THREAD

**Issue by ian-bartholomew** [DataDog/dd-trace-rb#1190]
Hello,

Similar to [this issue](https://github.com/DataDog/dd-trace-rb/issues/993) we are getting a warning about the ActiveModelSerializer when trying to configure it:

```sh
W, [2020-09-28T23:10:29.634060 #9]  WARN -- ddtrace: [ddtrace] Unable to patch Datadog::Contrib::ActiveModelSerializers::Integration (Available?: true, Loaded? true, Compatible? false, Patchable? false)
```

Our initialization file looks like this:
```ruby
Datadog.configure do |c|
  c.analytics_enabled = true
  c.use :rails, analytics_enabled: true
  c.use :active_model_serializers, analytics_enabled: true
  c.use :aws, analytics_enabled: true
  c.use :rest_client, analytics_enabled: true
end
```

We are using:
```
ddtrace (0.40.0)
active_model_serializers (0.8.4)
```

And our gemspec file:
```ruby
Gem::Specification.new do |s|
  ...

  s.add_dependency 'rails', '~> 4.2'

  s.add_dependency 'active_model_serializers', '~> 0.8.0'
  ...
  s.add_dependency 'ddtrace'
  ...
end
```
Any idea on what the issue might be?

Thanks!

**Comment by marcotc** [comment]
👋  @ian-bartholomew, I believe your issue is that we [only support `active_model_serializers >= 0.9`](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#integration-instrumentation), thus it shows as `active_model_serializers` as "Available?: true", "Loaded? true", but "Compatible? false".

**Comment by ian-bartholomew** [comment]
@marcotc ah, I missed that.  Thank you!

**Comment by delner** [comment]
@ian-bartholomew Looks like this one is resolved? Going to close it for now; please feel free to let us know if there's more to do here. Thanks!

**Comment by ian-bartholomew** [comment]
@delner yep, this is resolved, thanks!
