### ISSUE TITLE
Capture StandardError lets some Exceptions through

### ISSUE THREAD

**Issue by Ferdy89** [DataDog/dd-trace-rb#120]
I'd like to continue the discussion started [here](https://github.com/DataDog/dd-trace-rb/pull/111#discussion_r112983808) regarding how in the recently added Rack middleware [only `StandardError`s are captured](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/rack/middlewares.rb#L61).

I wanted to point out some examples of similar gems that have similar Rack middlewares and how they all capture `Exception` (which is the absolute parent in the Ruby errors hierarchy). Here are [Honeybadger](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/rack/error_notifier.rb#L35), [New Relic](https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/middleware_tracing.rb#L100) and [Sentry](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L53).

I'd like to discuss how to make it possible to capture those errors, otherwise I think this is missing the opportunity of catching some extra info!

**Comment by ufoot** [comment]
Good catch, we probably want to do this, but also limit it to the cases where we (re)raisen the error once we've captured it. Thanks for pointing this out!
