### ISSUE TITLE
The Railtie adds an unnecessary initializer

### ISSUE THREAD

**Issue by Ferdy89** [DataDog/dd-trace-rb#121]
Hi! We've been using version 0.7.0 since yesterday and we've noticed the Rack middleware wasn't working for us. The reason is because we require the gem manually on an initializer (only in presence of `ENV['DD_API_KEY']`) and by that point no new initializers can be added. [Here's a link to the code I'm talking about](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace.rb#L49-L57).

I don't think a new initializer is necessary at all. Railties can directly access the app's configuration and [modify the middleware stack](http://api.rubyonrails.org/classes/Rails/Railtie/Configuration.html#method-i-app_middleware) like:
```ruby
config.app_middleware.insert_before(0, Datadog::Contrib::Rack::TraceMiddleware, options)
```
Is there a reason to specifically require an initializer for this?

**Comment by ufoot** [comment]
Thanks for the report. We definitely need to dig into this. (hint: we know there can be some significant side effects depending on when the instrumentation is triggered, including, but not limited to, properly handling our own config and overrides)

**Comment by palazzem** [comment]
@Ferdy89 probably we're very late in the answer, but we're working on this PR that should work for you. Feel free to have a try and to provide any feedback. It will remain WIP until we're sure it works. Also we'll try to add a regression test.

Thank you for reporting that and sorry again!

**Comment by palazzem** [comment]
@Ferdy89 https://github.com/DataDog/dd-trace-rb/pull/208 has been merged and should address this problem. We've reproduced the issue in another application and with this patch it's working. Let us know if it doesn't for you!

Thanks a lot for reporting the issue, while providing a working solution!
