### ISSUE TITLE
Rails Runner Instrumentation

### ISSUE THREAD

**Issue by allcentury** [DataDog/dd-trace-rb#1219]
We run a lot of cronjobs via:

```bash
bundle exec rails runner bin/my_runner.rb
```

However, I'm unable to find these traces in APM.  Do we need to manually set up the tracing or is there integration instrumentation that we missed?  

If these aren't automatically picked up, I think this is a common enough execution method that others would want it.

Config:
```ruby
Datadog.configure do |c|
  if !%w[development test].include?(Rails.env) || ENV["DD_AGENT_DISABLE_TRACING"]
    c.runtime_metrics_enabled = true
    c.analytics_enabled = true

    c.use :rails, service_name: app_name
    c.use :active_model_serializers, service_name: "#{app_name}-active-model-serializers"
    c.use :aws, service_name: "#{app_name}-aws"
    c.use :concurrent_ruby, service_name: "#{app_name}-concurrent-ruby"
    c.use :faraday, service_name: "#{app_name}-faraday"
    c.use :racecar, service_name: "#{app_name}-racecar"
    c.use :rake, service_name: "#{app_name}-rake"
    c.use :redis, service_name: "#{app_name}-redis"
    c.use :shoryuken, service_name: "#{app_name}-shoryuken"
    c.tracer hostname: config[:apm][:host], port: config[:apm][:port]
    c.runtime_metrics statsd: STATSD_NO_NAMESPACE
  end
end
```

**Comment by marcotc** [comment]
👋 @allcentury, thank you for reporting this issue.

We don't currently have first-class support for instrumenting Rails Runner executions.
We have plans to spend more time improving our Rails instrumentation, so I'll make sure to capture the Runner instrumentation in that effort.

Meanwhile, your only solution is to perform [manual instrumentation](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#manual-instrumentation) at your entry points.
