### ISSUE TITLE
Wrong distributed headers injection env var is used 

### ISSUE THREAD

**Issue by jumbosushi** [DataDog/dd-trace-rb#1226]
I'm finding two permutations of `DD_PROPAGATION_STYLE_INJECT` string being used throughout the documentation and the code:
A.  `DD_PROPAGATION_STYLE_INJECT`
B. `DD_PROPAGATION_INJECT_STYLE` 

From the [Ruby documentation](https://docs.datadoghq.com/tracing/custom_instrumentation/ruby/?tab=activespan#b3-headers-extraction-and-injection), I expected this library to parse the environment variable in permutation A. However, this library [uses](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/ext/distributed.rb#L23) permutation B.

[Go documentation](https://docs.datadoghq.com/tracing/custom_instrumentation/go/#b3-headers-extraction-and-injection) mentions the use of  permutation A which is consistent with the [`dd-trace-go` source code](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/textmap.go#L66)

What do you think about updating the code to use permutation A (that'll be consistent with the documentation and other languages)?

extraction env var uses the wrong ordering as well.

**Comment by marcotc** [comment]
👋 @jumbosushi, we've shipped a fix for this issue in [0.43.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.43.0). I'm closing this issue as done.

Please let us now if you still have any feedback on it.
