### ISSUE TITLE
Setup log injection with Rails Semantic Logger

### ISSUE THREAD

**Issue by truongnmt** [DataDog/dd-trace-rb#1258]
I'm using rails (6.0.3.4), ddtrace (0.40.0) and rails_semantic_logger (4.4.4). Recently Datadog releases "Trace correlation" feature and I'm trying to set it up to work.

https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#trace-correlation

As written in the documentation, I tried the "Automatic" way which is either by adding configuration in Rails instrumentation `log_injection: true` or `DD_LOGS_INJECTION=true`. However, either didn't work. A quick look in the code base, [add_log](https://github.com/DataDog/dd-trace-rb/blob/73437cb252743deacab1041f2eca32899d21b981/lib/ddtrace/contrib/rails/patcher.rb#L64-L77) method only adds the additional log tag in the case of `logger` is `lograge` or `ActiveSupport::TaggedLogging` type. In my case which is SemanticLogger, it prints the following warning:

```
W, [2020-11-18T19:13:21.688997 #87523] WARN -- ddtrace: [ddtrace] Unabe to enable Datadog Trace context, Logger #SemanticLogger::Logger:0x00007ff0d1340598 is not supported
```

Which means, I can't setup in "Automatic" way. So I tried with manual way in the section [For logging in Ruby applications](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#for-logging-in-ruby-applications). 

In SemanticLogger there is [Name Tags feature](https://logger.rocketjob.io/rails.html#named-tags) which add a set of hash log value in every request.

So I setup as below:
```ruby
config.log_tags = {
  host: -> request { request.host },
  remote_ip: -> request { request.remote_ip },
  request_id: -> request { request.uuid },
  session: -> request { ... },
  user_agent: -> request { request.headers["User-Agent"] },
  dd: -> _request {
    correlation = Datadog.tracer.active_correlation
    {
      env: correlation.env.to_s,
      service: correlation.service.to_s,
      version: correlation.version.to_s,
      trace_id: correlation.trace_id.to_s,
      span_id: correlation.span_id.to_s
    }
  }
}
```

The additional tag is sent along with the log as below screenshot. But why I can't see the related traces? In the log it said "No Trace associated with this Log"

In the APM, it still said:

> No logs found
> To correlate logs with traces, inject trace_id and span_id

<img src='https://user-images.githubusercontent.com/11817656/99622238-11996700-2a6d-11eb-81ce-8de8e446e036.png' width=500 />

May I ask in which format should I include the tags for the Trace correlation feature to works? Thanks!

**Comment by ericmustin** [comment]
Hey there, thanks for reaching out. So support for "automatic" patching of [rocketjob/semantic_logger](https://github.com/rocketjob/semantic_logger) is indeed not supported at the moment, and would currently be a feature request. I can speak with the team internally on where this would line up on our roadmap, I think we want to continue improving our trace/log injection support and this would help that, but it probably won't be available "automatically" in the short term.  

So in the meantime, the approach you've taken, setting this up manually, is correct. I believe what's happening here from the screenshot you provided is that you're sending these tags to datadog logs intake in the format of, `named_tags.dd.trace_id`, but our logs ingestion pipelines are expecting them in the format of just `dd.trace_id`, not nested within `named_tags`.  It's possible to adjust your logs intake for a differently named trace_id attribute in the Datadog though, I believe if you follow the [guide here](https://docs.datadoghq.com/tracing/faq/why-cant-i-see-my-correlated-logs-in-the-trace-id-panel/?tab=jsonlogs#trace_id-option), all you would need to do is add `named_tags.dd.trace_id` as a `reserved attribute`. Example of where this would get added below:

![here](https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/8LunBJn8/Image%202020-11-19%20at%2010.43.33%20AM.png?v=4897df6316a0cad2238ba9e38fd8500e)

Can you give that a shot and let us know if that unblocks you here? If that doesn't work (it should), there's probably some other issue related to your logs pipeline, so then i'd suggest you [contact support](https://www.datadoghq.com/support/) and get a ticket opened and we can work through the specifics of your account setup. Feel free to reference this Issue on the support request if it gets to that point.

Cheers

**Comment by gingerlime** [comment]
We had a similar issue (also using Semantic Logger with DD), and we used a similar config + added remappers to Datadog log parsing

![CleanShot 2020-11-19 at 11 22 32](https://user-images.githubusercontent.com/524274/99654169-3e904e80-2a5a-11eb-8a10-729de3b75a3f.png)

![CleanShot 2020-11-19 at 11 22 53](https://user-images.githubusercontent.com/524274/99654183-43ed9900-2a5a-11eb-86d2-2e1026394dc3.png)

![CleanShot 2020-11-19 at 11 23 04](https://user-images.githubusercontent.com/524274/99654193-464ff300-2a5a-11eb-9a47-3c959d4e7f9f.png)

HTH

**Comment by truongnmt** [comment]
Thanks so much for your helps! Using remapper does work! 🎉 🎉 🎉
