### ISSUE TITLE
Error cause is not available in traces

### ISSUE THREAD

**Issue by bobvanderlinden** [DataDog/dd-trace-rb#1265]
Currently whenever an error is raised, you can only see the class, message and backtrace of that error. However, usually the error has an underlying `cause`, which is another error, so it also has a class, message and backtrace.

Example, the following code will raise `Wrapping exception`. The `.cause` of this exception is `Inner exception`:
```rb
begin
  raise StandardError.new("Inner exception")
rescue => e
  raise StandardError.new("Wrapping exception")
end
```
When running this in Ruby it'll output the full exception (including the nested causes):

```
Traceback (most recent call last):
example.rb:2:in `<main>': Inner exception (StandardError)
        1: from example.rb:1:in `<main>'
example.rb:4:in `rescue in <main>': Wrapping exception (StandardError)
```

The same happens when this is raised in Rollbar. However, whenever this is raised using dd-trace-rb, only the top-most exception is logged for the trace (`Wrapping exception`).

It would be nice to have all causes of an exception available whenever such an exception is raised.

**Comment by marcotc** [comment]
Thank you for reporting this issue @bobvanderlinden.

I agree that the top-most exception only is not enough information for proper debugging.

We'll work on augmenting the error reporting with each exception information.

**Comment by ericmustin** [comment]
👋  Hi, hope all is well, v0.49.0 is released if you'd like to upgrade and see if this resolves the issue. Cheers! https://github.com/DataDog/dd-trace-rb/releases/tag/v0.49.0
