### ISSUE TITLE
support https for DD_AGENT_HOST

### ISSUE THREAD

**Issue by akshah123** [DataDog/dd-trace-rb#1271]
It doesn't seem like this gem supports endpoints that require https.  Are there plans on supporting it?

**Comment by marcotc** [comment]
Hi @akshah123, you are correct that we don't currently support HTTPS endpoints for our communication with the agent.

In cases where we had this need in the past, we suggested running `ddtrace`'s requests through an HTTPS proxy. I understand that this is not convenient, but it's the way to go if you need this feature today.

Overall, we have plans to support more ways to ship traces from the application, but nothing planed for the short term.

**Comment by ivoanjo** [comment]
This is now supported! You can specify an https url via the `DD_TRACE_AGENT_URL` environment variable OR by passing the `ssl: true` flag when configuring [using `transport_options`](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#using-the-nethttp-adapter).

I'm going to go ahead and close this ticket, but please do reach out to us if we can help in any way :)
