### ISSUE TITLE
:enabled config variable only for staging and production servers

### ISSUE THREAD

**Issue by AlexLarra** [DataDog/dd-trace-rb#1288]
**config.ru**
```
ENV['SERVER_MODE'] = '1'
```

**config/initializers/datadog.rb**
```
Datadog.configure do |c|
  c.tracer enabled: ENV['SERVER_MODE'] == "1" && (Rails.env.staging? || Rails.env.production?)
  ...
end
```

I have set like this `enabled` in order to avoid sending data in development, testing or console when is from staging or production.
Is it there any way to do it simpler or working like that by default?

**Comment by marcotc** [comment]
Hey @AlexLarra, such conditionals are always needed, as per our experience with our clients.
What makes it hard to coordinate is that few production environments have the same logic: different ways to detect production/staging/QA/CI/development/console, for example, and these vary by what framework (if any) the application uses.

That being said, I do agree that there are some conditions that are universally desired: in a Rails application, a production server environment should generate traces by default. Also in a Rails application, a local development console should not generate traces by default.

We have an effort to improve our Rails integration ongoing, I'll capture this request there and I'll get back to you when we have some progress there.

On another note, I do have a suggestion on how you can detect if the application is running on a Ruby console. We use this logic in our tracer: https://github.com/DataDog/dd-trace-rb/blob/1f8551c2d3c64e2b7f37ff83db3095e7ce095e3e/lib/ddtrace/diagnostics/environment_logger.rb#L48-L52

**Comment by ivoanjo** [comment]
This ticket has been open for a long time. Nowadays we do have a quite improved auto-detection of development environments, and as a fallback `enabled` is always an option (we've even tweaking the docs further to make that clear in #4182).

Hopefully the current state of these tackle this issue; if not, please do open a ticket and let us know how we can improve :)
