### ISSUE TITLE
ActionCable Instrumentation

### ISSUE THREAD

**Issue by renchap** [DataDog/dd-trace-rb#132]
It would be great to have ActionCable instrumentation built into the gem.
There is an `perform_action.action_cable` notification emitted, I think it should not be very hard to hook into it.

**Comment by delner** [comment]
Hey @renchap , thanks for the suggestion! (And sorry for the crazy late reply.) Sounds like a good idea; we'll take a look at this in the next few weeks. We'll keep you posted!

**Comment by phlegx** [comment]
Hi @delner any news about this?

**Comment by delner** [comment]
Looks like weeks quickly turned into a year... sorry we haven't yet had a chance to look at this!

I would love to build this, however, it's unlikely I'll be able to dedicate any time to it in the immediate future. For what it's worth, we do have upcoming plans to overhaul the Rails integration, which will make it a lot easier to add in this ActionCable integration.

It's worth mentioning that we do regularly consider & merge pull requests that add new integrations like this. If this were submitted, it'd be much more likely to be prioritized and merged much sooner. These integrations are usually pretty quick to develop, and although we regrettably don't have contributing guidelines or many other aids, I did write [a brief description of how it works](https://github.com/DataDog/dd-trace-rb/issues/695#issuecomment-465740811).

In any case, I will raise it to our team that there's a lot of interest in this feature.

**Comment by marcotc** [comment]
Hi @renchap and @phlegx, we've just released ActionCable instrumentation in 0.31.0.

Give it try and let us know if you have any feedback!
