### ISSUE TITLE
postgres.query is missing from the operation mode toggle when using the same service name

### ISSUE THREAD

**Issue by mbarany** [DataDog/dd-trace-rb#1324]
When using the same service name for all of the integrations it seems that I can not select `postgres.query`. Additionally when I'm viewing the trace with that span I try to click on the link to go to `https://app.datadoghq.com/apm/service/myapp/postgres.query?env=staging`, but it just goes to the app screen with an empty state.

Other services that we have that use the Java agent allow the postgres spans to be selectable so that's why I think this is a Ruby specific issue.

```ruby
Datadog.configure do |c|
  app_name = "myapp"

  c.use(:rails, service_name: app_name, cache_service: app_name, database_service: app_name)
  c.use(:aws, service_name: app_name)
  c.use(:faraday, service_name: app_name)
  c.use(:http, service_name: app_name)
  c.use(:kafka, service_name: app_name)
  c.use(:rake, service_name: app_name)
  c.use(:redis, service_name: app_name)
  c.use(:sidekiq, service_name: app_name, client_service_name: app_name)
end
```

### My service's operation mode toggle:

![operation-1](https://user-images.githubusercontent.com/1434605/105529373-4ff11380-5cb4-11eb-8529-324408b6f1bb.png)
![operation-2](https://user-images.githubusercontent.com/1434605/105529374-4ff11380-5cb4-11eb-86f2-54cb387fc15f.png)

### As you can see in the trace that we have a `postgres.query` span

![Screen Shot 2021-01-22 at 1 19 48 PM](https://user-images.githubusercontent.com/1434605/105529535-8464cf80-5cb4-11eb-8687-c053f2e9ab19.png)

Please help! Thank you 😄

**Comment by marcotc** [comment]
Thanks for reaching out, @mbarany.

I'm curious: what service do you see when you click the `postgres.query` span?

For example, in this screenshot it would be `rails_app-postgres`:

![Screen Shot 2021-01-22 at 1 51 16 PM](https://user-images.githubusercontent.com/583503/105532535-f50deb00-5cb8-11eb-98ca-1762ca10f79b.png)

This will help us figure out what possible default service name value it's falling back to.

**Comment by mbarany** [comment]
@marcotc the service is the same name as everything else since I'm explicitly setting `database_service` to `appname`

**Comment by marcotc** [comment]
@mbarany With the service name of your `postgres.query` being `myapp`, and you not seeing it in the page, I don't see anything that the tracer is doing that is incorrect in this case. I think this is an issue in the backend/UI.

To help you further, I suggest you open a support ticket at https://www.datadoghq.com/support/, so our team can look specifically into your account with our internal support tools.

Feel free to link this GitHub issue to help with providing context to the support ticket.

**Comment by mbarany** [comment]
Closing the loop here. I received the following reply from support with a potential solution, but have not yet implemented it

> I have heard back from engineering regarding your case and have the following information to share with you.
>
> Currently, the Datadog UI and model for representing traces assumes that each Library or Operation within your application will have a different service. This is the most well supported way of representing traces within the Datadog Ecosystem at this time. Overall, as an organization, we recognize some users prefer to have fewer services, and there is active work in progress so that each Application or Process maps to exactly 1 service. However, at this time, while there are ways to accomplish this 1App => 1Service approach and not lose any metric granularity, there are still some areas of the UI that may behave in unintended or less-than-ideal ways, such as:
> The automatic selection of which span operation name (rack.request, postgresql.query, etc) gets chosen by default for a service.
> The visibility available within the service-map.
> the "type" that a service gets assigned.
>
>
> While we are actively working on improving this experience, for now if you are comfortable with some UI rough edges, such as what's listed above, it is possible to condense everything in your application into 1 service. 
>
> We also want to clarify how Trace Metrics work and are generated. The Datadog tracing system generates Trace-metrics in the case of a few scenarios. 
> First, if the span represent the "root" of a service. 
> Second, if the span has been explicitly marked as a span that we should always generate metrics for regardless of where it exists within the tree of a services. 
> Third, for Http-Client spans as well as Database Spans (or more broadly speaking spans which represent an external service), Tracing libraries will not automatically have Trace-Metrics generated for those spans, unless the user manually enables this setting on the Span. We are actively working on making this experience better align with a "1 service => 1 application" model, but for now, that is the current state.
>
> 3.Because of these details above, if a user wants to both combine all spans into 1 service within their app, and also get trace-metrics for each of those spans, because some of the spans in question are database spans, then they will have to manually mark those as spans that should generate trace metrics. 
>
> Fortunately, the Datadog Ruby Tracing Client (dd-trace-rb) provides an easy way to modify these spans manually, by using a span processor. Below is an example of how to configure a span processor to update all postgres.query to be marked for metric generation.
>
> ```ruby
> require 'ddtrace' 
> require 'ddtrace/contrib/analytics'
> 
>  Datadog::Pipeline.before_flush( 
>    # If span name is postgres, mark for metric generation
>    Datadog::Pipeline::SpanProcessor.new { |span| 
>    if span.name == "postgres.query" 
>      # Measure service stats on span
>      Datadog::Contrib::Analytics.set_measured(span) 
>    end    
>  })
> ```
>
> By applying this processor, you should be able to then combine your database service into the same service name (myapp) as their main web-app, but still have the postgres.query span name as a valid option in the service dropdown.
