### ISSUE TITLE
Configuring non Rails tracers.

### ISSUE THREAD

**Issue by whithajess** [DataDog/dd-trace-rb#138]
I am struggling to work out how I can recreate the same:

```
Rails.configuration.datadog_trace =
  {
    # may depend by your conditional env
    enabled: false
  }
```

For a non Rails app when adding something like the Rack Trace Middleware you can do: 
```
 Datadog::Contrib::Rack::TraceMiddleware, enabled: ['test','development'].exclude?(ENV['RACK_ENV'])
```
**UPDATE: this doesn't actually work either ^**

but when adding `Datadog::Monkey.patch_module(:active_record)` there is no option to disable this means when running in **test** or **development** modes  you get a whole bunch of:

```
E, [2017-06-16T11:28:51.774635 #92936] ERROR -- ddtrace: [ddtrace] (.rvm/gems/ruby-2.3.3/gems/ddtrace-0.7.2/lib/ddtrace/transport.rb:73:in `rescue in post') Failed to open TCP connection to localhost:8126 (Connection refused - connect(2) for "localhost" port 8126)
```
If it is documented somewhere I haven't been able to find it.

**Comment by whithajess** [comment]
Found you can just set Datadog.tracer.configure(enabled: ['test','development'].exclude?(ENV['RACK_ENV'])) will first patch documents to make this clear before closing this.

**Comment by ufoot** [comment]
Indeed, using `Datadog.trace.configure` is the way to go here. Thanks for reporting this.

**Comment by theasteve** [comment]
Should we replace the configuration on  ```datadog-tracer.rb``` file with ```Datadog.tracer.configure(enabled: ['test','development'].exclude?``` ?
