### ISSUE TITLE
http integration ignores connection errors in Net::HTTP.start

### ISSUE THREAD

**Issue by DocX** [DataDog/dd-trace-rb#1404]
The `http` integration for `Net::HTTP` does not track connection errors.

Example:

```rb
uri = URI('http://example.com/some_path?query=string')

Net::HTTP.start(uri.host, uri.port) do |http|
  request = Net::HTTP::Get.new uri

  response = http.request request # Net::HTTPResponse object
end
```

Note: This also affects the shortcut methods like `Net::HTTP.get_response` as they internally implement the same `start` block with `request` inside.

When there is error in the connection establishing part during the `start` method, like dns error, tcp error, etc, no span is reported

What is expected: Error span to be reported.

I can see from the code that the integration only patches the `request` method - which make sense, as there may be multiple requests during single connection. 

But would it make sense to catch errors in `start` and create span when there is an error?

**Comment by marcotc** [comment]
Welcome back @DocX! This report makes a lot of sense. I'm tagging it as a bug and we'll work on addressing it.

**Comment by DocX** [comment]
Hi @marcotc, thank you. I've spiked some implementation in the PR above. I'm just having some issues with the specs. If you want to you can continue on that.

**Comment by marcotc** [comment]
Thank you so much for the PR, @DocX. I'll follow up there.

**Comment by DocX** [comment]
No problem.

I gave it bit more thought and I am not 100% convinced it is the cleanest solution tho.

I've seen that in `nodejs` integration we have `tcp` tracing - which is layer below any http client. Given that this is also about issues on the TCP level, maybe the actual best solution would be to introduce tcp tracing for ruby. When enabled this would catch tcp errors in anything - including `Net::HTTP`.

What do you think?

**Comment by ivoanjo** [comment]
Closing this one as #1405 was also closed.
