### ISSUE TITLE
would calling a resque job via `Resque.enqueue` be supported?

### ISSUE THREAD

**Issue by jhtib** [DataDog/dd-trace-rb#1438]
I apologize for asking a tech-support type question but was struggling to find this information.

We have an older Rails app and would like to instrument the Resque jobs for it.

We call them like `Resque.enqueue(Jobs::PurgeCDNPageCache, url)` and have ran this several times but not seeing anything in our analytics. Is only `CleanupJob.perform_later(arg1, arg2)` format supported? 

If both are supported, do I need to specify all the jobs in the `workers` option hash(https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#resque)?  Or does an empty hash (the default) mean that all jobs should be instrumented?

**Comment by marcotc** [comment]
👋 @jhtib, you currently have to specific all Resque jobs that you'd like to instrument in the `c.use :resque, workers: []` array.

There's a PR up now from us to make it automatic, but still under review: https://github.com/DataDog/dd-trace-rb/pull/1400

Let us know if adding `Jobs::PurgeCDNPageCache` to the `workers` list still doesn't instrument that job.

**Comment by ivoanjo** [comment]
Hey @jhtib! Hopefully you're all set now, so I'm going to go ahead and close this issue. Please do reach out if we can help in any way :)
