### ISSUE TITLE
Can't get HTTP request queue times on Heroku

### ISSUE THREAD

**Issue by nateberkopec** [DataDog/dd-trace-rb#1448]
Here's my agent config:

```ruby 
  Datadog.configure do |c|
    c.use :rails, {
      analytics_enabled: true,
      service_name: 'myapp',
      log_injection: true
    }
    
    c.use :rack, {
      analytics_enabled: true,
      request_queueing: true
    }
  end
```

What am I doing wrong? I still don't see any queueing spans on traces.

**Comment by ericmustin** [comment]
👋 Hey @nateberkopec . That config generally looks good to me, a few next steps here / things to check so we can unblock you here:

1. tracer version? (i believe ur running 0.47 but just leaving this here for posterity)
2. have you added  `X-Request-Start` or `X-Queue-Start` request header to incoming requests? (per side convo, as you're deploying on heroku, you should get this "for free" afaik, but just mentioning this for posterity again).
3. Where are you adding this config? In a rails app it should only live within `config/initializers/datadog.rb`

On startup we log a big diagnostic blob that would contain information on whether this setting is being set correctly. If you want to restart the app and collect that log for us, and share it, that would be helpful (please be sure to remove any PII, or if you have concerns that PII may be contained in ur diagnostic info, open a support ticket at support@datadoghq.com to share any sensitive info). My suspicion is that perhaps there are multiple config blocks in your application, so seeing the diagnostic info would help us determine if the settings above are being taken into account.

Additionally, if you want to confirm that request header is added to incoming requests, you can simply modify config like:

```
c.use :rack, analytics_enabled: true, headers: { request: ['X-Request-Start'] }, request_queuing: true
```

Adding `headers: { request: ['X-Request-Start'] }` to your rack config will attach this header as a span tag to your rack spans if the request header is present on incoming requests.

Using heroku and 0.47.0 i tried to reproduce this issue and was unable to, see screenshot below, so i suspect it's something specific to your env or application:

![flamegraph](https://p-qkfgo2.t2.n0.cdn.getcloudapp.com/items/xQubvAb5/0365b2a8-1f00-4abd-8770-58adbdc4b4aa.png?v=c382f0d5359bc0485a39b96a8ff48b7e)

**Comment by nateberkopec** [comment]
> My suspicion is that perhaps there are multiple config blocks in your application

There are, but they don't overwrite each other - is that OK?

**Comment by ericmustin** [comment]
@nateberkopec off the top of my head I _believe_ if there's no overlap it should be ok, though it's not recommended and I don't think we have tests around that behavior. Are they both in the `/initializers/datadog.rb` file?

**Comment by nateberkopec** [comment]
@ericmustin No, they're in various `/initializers/`. I'm consolidating them now.

**Comment by ericmustin** [comment]
I think as long as it's in `initializers` it should be ok tbh. There's really no clear reason to me here why this isn't working, getting a debug diagnostic log from startup, as well as adding the `headers: { request: ['X-Request-Start'] }` portion to ensure`X-Request-Start` does in fact exist on these requests, would be the next steps here.

**Comment by ericmustin** [comment]
@nateberkopec just wanted to check in here and see if you were still blocked?

**Comment by nateberkopec** [comment]
No idea what fixed it here. I consolidated 3 separate config blocks (in /initializers/ as I said) and added `headers: { request: ['X-Request-Start'] }` to the `rack` integration block, and now it works 🤷
