### ISSUE TITLE
NoMethodError: undefined method `env=' for #<Datadog::Configuration::Settings:0x0000000007110510>

### ISSUE THREAD

**Issue by LoganBresnahan** [DataDog/dd-trace-rb#1482]
I'm getting this error:
`NoMethodError: undefined method `env=' for #<Datadog::Configuration::Settings:0x0000000007110510>`

My current config:
```
  # frozen_string_literal: true

  require "ddtrace"

  Datadog.configure do |c|
    c.use :rails, service_name: "my_app"
    c.use :graphql, schemas: [MyAppSchema], service_name: "my_app_graphql"
    c.use :aws, service_name: "my_app_aws"
    c.use :redis, service_name: "my_app_redis"
    c.analytics_enabled = true
    c.env = Rails.env
    c.tracer hostname: "datadog-agent", port: 8126
  end
```

According to these docs: https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#environment-and-tags
I should be able to set the env in this manner. I have not set the environment using `DD_ENV` anywhere.

After looking through the code in this file https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/configuration/settings.rb
I'm wondering if the following code needs the `on_set` option?
```
      option :env do |o|
        o.default { ENV.fetch(Ext::Environment::ENV_ENVIRONMENT, nil) }
        o.lazy
      end
```

Gem version: ddtrace (0.32.0)

**Comment by LoganBresnahan** [comment]
Didn't realize how out of date my `ddtrace` version was. Closing.

**Comment by ivoanjo** [comment]
Glad you were able to solve the issue, Logan! Don't hesitate to ping in the future if we can help :)
