### ISSUE TITLE
Regression: action_view spans are grouped different from version 0.43 to 0.44 for rails 5.2

### ISSUE THREAD

**Issue by sbeckeriv** [DataDog/dd-trace-rb#1486]
Dearest maintainer, 

During a recent gem upgrade I have found that action_view spans were not grouped the same. In version 0.43 they are grouped as their own item. In version 0.44 they are grouped under the main rails application.  I am running rails 5.2. There does appear to be a change for rails 6 here https://github.com/DataDog/dd-trace-rb/compare/v0.43.0...v0.44.0#diff-4e66cf9c7b7a11074f9a571d2b119ce8ecc435f902a326947d6e684ece54d0f8L13  github does not hot link the file and line number in that view. some commits are here.  https://github.com/DataDog/dd-trace-rb/commit/fb3f96eba4661d9b758f73d68656ebdca72e1ebf

0.43
https://app.datadoghq.com/apm/service/action_view/rails.render_partial
![image](https://user-images.githubusercontent.com/12170/116310881-69947200-a75f-11eb-8eec-e49a07f7f54d.png)

0.44
https://app.datadoghq.com/apm/service/[redacted]/rails.render_partial  
red block is the app name.
![image](https://user-images.githubusercontent.com/12170/116311066-a52f3c00-a75f-11eb-83d4-46d8794c3899.png)

this shows up more in the usage charts.  You can see the dark blue which was action view render calls is now part of the light blue.
![image](https://user-images.githubusercontent.com/12170/116311217-dc055200-a75f-11eb-8921-a0224cc36ec5.png)

The configuration is nothing to complex. I removed some other lib configurations.
```
options = {
  analytics_enabled: false,
}

Datadog.configure do |c|
    c.runtime_metrics_enabled = true
    c.analytics_enabled = true

    # This will activate auto-instrumentation for Rails
    c.use :action_pack, options
    c.use :action_view, options
    c.use :active_model_serializers, options
    c.use :active_record, options
    c.use :active_support, options
    c.use :rails, options
    c.use :rack, options.merge(
      analytics_enabled: true,
      request_queuing: true,
    )

end
```

Thank you for software and your time reviewing this issue. Please let me know if i can try something or provide more details.

Becker
Dictated but not reviewed.

**Comment by delner** [comment]
If I'm understanding this, the difference between the two versions is that ActionView spans are no longer in their own service, but have been rolled into the main service.

If this is correct, then this is intended behavior. We do want to give visibility into each layer of your application (Rack vs controller vs view vs DB, etc) but services are more equivalent to "application" not to "layer." It's our intention that in the future that all spans generated by an application belong to the same service.

There should be a means within the UI to get a breakdown of each layer, so you can see how much time was spent in each. I can double check with a product expert the best means to do this (I think it already should be possible.)

**Comment by sbeckeriv** [comment]
@delner  That is correct action view spans are not longer a service level thing. Please let me know how
