### ISSUE TITLE
Meaning of "app" in set_service_info?

### ISSUE THREAD

**Issue by ejholmes** [DataDog/dd-trace-rb#150]
This isn't really Ruby specific, but I can't find any docs that talk about the meaning of the `app` argument to [set_service_info](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/tracer.rb#L102):

```ruby
def set_service_info(service, app, app_type)
```

How is this used in the backend?

**Comment by ejholmes** [comment]
To somewhat answer my own question, it looks like this is used as a tooltip when you hover over the type in the web UI:

![](http://ejholmes.github.com.s3.amazonaws.com/JMoDR0DjKOBOqumKE7w85MpEiYDxnUZjKm.png)

I think a good example of how you might use this would be to distinguish different database types (e.g. `postgres`, `mongo`, `redis`, etc).

**Comment by ufoot** [comment]
Indeed, we need to rework our docs so that this is more explicit.

**Comment by palazzem** [comment]
Hello @ejholmes! As you wrote in a previous post, all service metadata are used only for UI-sugar, and are automatically handled by our integrations with the latest patch available here (#306). If you want more details about the terminology, you can check our documentation and FAQ available here: https://help.datadoghq.com/hc/en-us/articles/115000702546-What-is-the-Difference-Between-Type-Service-Resource-and-Name-

Feel free to reopen the issue if it's not enough to answer your questions!
