### ISSUE TITLE
Tracking request headers

### ISSUE THREAD

**Issue by mustela** [DataDog/dd-trace-rb#1525]
Hello there! Im trying to log some custom headers, but with no luck. I  can't find the way of doing it. I would basically like to see those headers under this view: 

![Screenshot 2021-05-27 at 10 07 51](https://user-images.githubusercontent.com/325222/119790166-fef86280-bed3-11eb-834e-26d3f1b67636.png)

Im using: 
```
dd-trace 0.34.2
faraday: 0.17.3
```

```
Faraday.new(url: base_url, ssl: { verify: verify_ssl }) do |conn|
      conn.authorization :Bearer, token
      conn.use :ddtrace, service_name: "my-service"
      conn.response :logger, Rails.logger
      conn.adapter :typhoeus
    end
```

Any idea?

Thanks a lot! 

EDIT: 
This isn't working neither

```
options = {
      service_name: "my-service",
      headers: { request: ["CORRELATION-ID"] }
    }
    Faraday.new(url: base_url, ssl: { verify: verify_ssl }) do |conn|
      conn.authorization :Bearer, token
      conn.use :ddtrace, options
      conn.response :logger, Rails.logger
      conn.adapter :typhoeus
    end
```

**Comment by ericmustin** [comment]
👋 Hey @mustela , thanks for reaching out. I don't think adding request `headers` is a supported feature within dd-trace-rb at the moment via the `Faraday` automatic instrumentation.

I think the appropriate way to do this at the moment would be by adding a Faraday middleware that adds the request header you'd like as a tag on the current active span

https://lostisland.github.io/faraday/middleware/custom

Some psuedo code of how that might work internally: 
```
def call(request_env)

  current_span = Datadog.tracer.active_span
  unless current_span.nil?
    current_span.set_tag = request_env[:request_headers][:<YOUR_EXAMPLE_REQ_HEADER>]
  end

  @app.call(request_env).on_complete do |response_env|
    # do something with the response
    # response_env[:response_headers].merge!(...)
  end
end
```

**Comment by mustela** [comment]
Thanks @marcotc, I'll take a look!

**Comment by mustela** [comment]
@marcotc it worked just fine! thanks for your help!
