### ISSUE TITLE
Failed to apply Datadog::Contrib::Aws::Patcher patch. Cause: uninitialized constant Aws::S3

### ISSUE THREAD

**Issue by brianlow** [DataDog/dd-trace-rb#1589]
### Description

Warning is logged when booting rails server starting with ddtrace `0.50`

### Steps to reproduce

1. `rails new ddtrace-sns`
2. add gem `gem 'aws-sdk-sns'`
3. add gem `gem 'ddtrace', '~> 0.50', require: 'ddtrace/auto_instrument'`
4. `bin/rails s`

**Expected**: rails starts with no warnings
**Actual**:
```
$ bin/rails s
=> Booting Puma
=> Rails 6.1.4 application starting in development 
=> Run `bin/rails server --help` for more startup options
E, [2021-07-12T18:22:28.227765 #44664] ERROR -- ddtrace: [ddtrace] (/Users/b/asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ddtrace-0.51.0/lib/ddtrace/contrib/patcher.rb:41:in `on_patch_error') Failed to apply Datadog::Contrib::Aws::Patcher patch. Cause: uninitialized constant Aws::S3 Location: /Users/b/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/ddtrace-0.51.0/lib/ddtrace/contrib/aws/patcher.rb:26:in `patch'
Puma starting in single mode...
* Puma version: 5.3.2 (ruby 3.0.1-p64) ("Sweetnighter")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 44664
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

Minimal repro:
https://github.com/brianlow/datadog-sns/

Affects: ddtrace `0.50`, `0.51`
Does not affect: ddtrace `0.48`, `0.49`

**Comment by ketiko** [comment]
It looks like it was introduced in https://github.com/DataDog/dd-trace-rb/pull/1494

**Comment by marcotc** [comment]
Thank you for the report @brianlow and the additional information @ketiko.

The issue seems straightforward, so I'm creating a fix now.

**Comment by marcotc** [comment]
👋 @brianlow and @ketiko. Version [`0.51.1`](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.51.1) is out and addresses this issue.
Let us know if the problem still persists with this new release.

**Comment by brianlow** [comment]
The fix works for us. Thanks @marcotc!
