### ISSUE TITLE
Datadog CI branch name incorrect for GitHub Actions push events

### ISSUE THREAD

**Issue by andrewhampton** [DataDog/dd-trace-rb#1621]
Our tests are showing up in Tests Runs, but not in Tests. The FAQs mention this is due to the git metadata being improperly set. When checking the metadata, I see everything except the branch name:

![image](https://user-images.githubusercontent.com/187061/127563746-a2d3c07c-e7f2-4a4f-85b5-6b718e978d65.png)

We're running in Github Actions. When [`extract_github_actions`](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/ci/ext/environment.rb#L203-L222) is figuring out the branch and tag name, it does this:

```ruby
branch, tag = branch_or_tag(env['GITHUB_HEAD_REF'] || env['GITHUB_REF'])
```

Additionally, according to [the docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context), `GITHUB_HEAD_REF` is only set when "the event that triggers a workflow run is either `pull_request` or `pull_request_target`." However, our CI is triggered by a `push` event. In our case, `GITHUB_HEAD_REF` is present, but empty:

![image](https://user-images.githubusercontent.com/187061/127563361-6c9765a9-1b29-4413-bfba-bceb5d6f316c.png)

I think the root cause here is empty strings are truthy in ruby. So I believe the first line of `extract_github_actions` is basically evaluating to `branch, tag = branch_or_tag("")`.

In my config file, I did `export GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-$GITHUB_REF}` before running rspec, which equivalent to `GITHUB_HEAD_REF ||= GITHUB_REF`. This fixed the problem. Things started showing up on both the Tests and Test Runs tabs. So I think the fix is to just change [line 204 of environment.rb](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/ci/ext/environment.rb#L204) to something like:

```ruby
ref = env['GITHUB_HEAD_REF']
ref = env['GITHUB_REF'] if ref.nil? || ref.empty?
branch, tag = branch_or_tag(ref)
```

**Comment by juan-fernandez** [comment]
this is a great find @andrewhampton! Thanks! We'll implement the fix 👍
