### ISSUE TITLE
Circular Require Considered Harmful

### ISSUE THREAD

**Issue by ivins** [DataDog/dd-trace-rb#1653]
Trying to upgrade Ruby to 3.0.2 in a project. 
Ran `bundle update` then ran the `rspec` tests. The tests executed but there were warnings.

The warnings that are coming up `warning: loading in progress, circular require considered harmful` for ddtrace when upgrading to '0.52.0'. When specifically set to '0.44.0' the warnings are no longer there. I tried all versions in between and they each have at least one of these errors. I won't include the full stack for each. I think the errors are clear. 

```
/Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: loading in progress, circular require considered harmful - /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ddtrace-0.52.0/lib/ddtrace.rb
```

```
/Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: loading in progress, circular require considered harmful - /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ddtrace-0.52.0/lib/ddtrace/profiling.rb
```

```
/Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: loading in progress, circular require considered harmful - /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ddtrace-0.52.0/lib/datadog/contrib.rb
```

```
/Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332: warning: loading in progress, circular require considered harmful - /Users/ivins/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ddtrace-0.52.0/lib/ddtrace.rb
```

**Comment by marcotc** [comment]
👋 @ivins, thank you for this report.

I wasn't able to figure our where the *circular* part of the lines you provided are: they all point to ActiveSupport loading `ddtrace` from [dependencies.rb:332](https://github.com/rails/rails/blob/v6.1.4/activesupport/lib/active_support/dependencies.rb#L332), but with no information about any circularity.

The possibility that I can think of (`ddtrace` loading `active_support`, or vice versa) doesn't seem to hold ground.

We have a few Rails applications running Ruby 3.0.2, but they don't emit such warning in our environment.

Would you be able to provide complete stack traces? I'm looking for anything that helps us find where the offending `require` statements are.

**Comment by ivins** [comment]
Hi @marcotc,
Thanks for the quick response. I have dug into it a bit more on our side and though I am not exactly sure what was happening under the hood. I have managed to change one of our require statements in our codebase and it looks like the errors are not occurring anymore. Errors was a bit misleading but it looks like this isn't an issue on your side after all.

Thanks for following up!
