### ISSUE TITLE
Number of opened connections over the WebSocket protocol

### ISSUE THREAD

**Issue by alexfedoseev** [DataDog/dd-trace-rb#1665]
Hi, sorry if it's a dumb question. I'm quite new to DataDog. I can't figure out if it's possible to implement a timeline with the number of opened connections over the WebSocket protocol (via ActionCable). Appreciate any pointers!

**Comment by marcotc** [comment]
Hey @alexfedoseev, you can do this using our metrics gem https://github.com/DataDog/dogstatsd-ruby. Specifically, a `gauge` metric: https://docs.datadoghq.com/metrics/dogstatsd_metrics_submission/#code-examples-1 

In a background thread, say every 10 seconds, you'd run:

```ruby
require 'datadog/statsd'
statsd = Datadog::Statsd.new('localhost', 8125)

Thread.new do
  loop do
    connection_count = ActionCable.server.connections.length
    statsd.gauge('action_cable.connection_count', connection_count, tags: ['env:prod', 'service:myservice'])
    sleep 10
  end
end
statsd.close
```

This falls a bit outside the scope of `ddtrace`, which deals with generating [traces](https://docs.datadoghq.com/tracing/visualization/#trace).
