### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by DubHunt** [DataDog/dd-trace-rb#167]
We added dd-trace-rb to a couple of applications across 6 servers the other day and within 24 hours we were receiving high memory utilization alerts for every server. Suspecting dd-trace-rb, we conditionally required it for only one of the 3 servers per application via an env var. Again, we began seeing high memory utilization, this time only on the instances where dd-trace-rb was required. 

All servers have the exact same OS and configuration and are running the same code. All are behind a load balancer and look to have been receiving the same volume of traffic, so it seems that dd-trace-rb might be the culprit. Memory is GCed, but utilization just seems too high. Is dd-trace-rb known to consume large amounts of memory? Any other info I can provide? Thanks.

baseline server w/o dd-trace-rb
<img width="538" alt="screen shot 2017-07-26 at 10 01 44 am" src="https://user-images.githubusercontent.com/1246137/28631477-9bebd3d2-71ea-11e7-9f9f-40e98731362f.png">

different server w dd-trace-rb, same timeframe as above
<img width="548" alt="screen shot 2017-07-26 at 10 02 36 am" src="https://user-images.githubusercontent.com/1246137/28631483-a05e3568-71ea-11e7-8961-be84aef59dd1.png">

**Comment by palazzem** [comment]
Thanks @DubHunt for reporting that! Performances (and memory usage) are critical and we'll investigate that one immediately. Can you open a ticket so that we can collect more details about your stack and how the tracer is instrumenting (or auto-instrumenting) your application?

Thank you a lot!

**Comment by DubHunt** [comment]
Thanks. I've uploaded logs for request #102561

**Comment by ponny** [comment]
Getting same issue.  Similar graph.  Removing ddtrace for now to see if it improves.

**Comment by palazzem** [comment]
@ponny thanks for reporting this! We've already found one possible cause where in some code paths Rails spans are not properly closed. As soon as the fix is in place and released, we contact you again. Thanks a lot for pointing out this critical issue!

**Comment by mgodwin** [comment]
Hey @palazzem - Has there been any update on this?  Thanks.

**Comment by palazzem** [comment]
Hi @mgodwin! We're working on it right now since it has the highest priority. At the moment, we're triaging Rails cases where a trace is not finished and flushed. Mostly, it should be related to code exceptions, or to our integration listeners that are not triggered by Rails. If this is the case, it's possible that the memory grows a lot in high traffic environments (it's not expected of course) because the tracing context holds an incomplete trace, that is not closed and removed from memory.

We'll keep you updated with this critical issues that is a huge stopper.

**Comment by DubHunt** [comment]
We ran 0.8.2-RC1 on one of our servers for 3 days and the memory utilization looked similar to all of our other servers. 👍

**Comment by palazzem** [comment]
that's great! thanks @DubHunt for the follow-up! we need to address another connected issue today, but we'll ship the 0.8.2 tomorrow whatever!

Thanks everyone for your precious feedback! Will update the issue when the release is out.

**Comment by palazzem** [comment]
Cool, @DubHunt we've released a new version that has the fix: https://github.com/DataDog/dd-trace-rb/releases/tag/v0.8.2

I suggest everyone involved in this issue to try this new version if it's solved or not. /cc @mgodwin @ponny
