### ISSUE TITLE
Add `Datadog::Span#[]=` to match OpenTelemetry.

### ISSUE THREAD

**Issue by ioquatix** [DataDog/dd-trace-rb#1670]
https://github.com/open-telemetry/opentelemetry-ruby/blob/cc28b8648e4085ff62e65e3db87ff45f82750cd1/api/lib/opentelemetry/trace/span.rb#L62

**Comment by marcotc** [comment]
This seem like a reasonable request, @ioquatix, thank you for bringing it up.

It is a small task, but we are in the middle of a `Datadog::Span` refactoring (https://github.com/DataDog/dd-trace-rb/pull/1675), so I'll schedule for us to tackle this after we finished that work.

**Comment by ioquatix** [comment]
The more alignment you get with OTEL the easier it would be for me, if you can check some of the other methods it would be 🤩

**Comment by ivoanjo** [comment]
I believe this is fixed by #2076 (which you also contributed, thanks!) so I'm going to mark this as done! :)
