### ISSUE TITLE
Tracing Sidekiq heartbeat, scheduler, and process job fetching

### ISSUE THREAD

**Issue by agrobbin** [DataDog/dd-trace-rb#1673]
I'm wondering what appetite there is for introducing additional tracing (i.e. new top-level spans) for parts of Sidekiq. Currently, dd-trace-rb hooks into Sidekiq's client/server middleware stack, which is great to track job pushes and job executions, but there are (at least) 3 other aspects of Sidekiq that are not wrapped in a high-level span, resulting in a *lot* of one-off Redis spans that are not related to one another.

The 3 areas that have jumped out to us (all from the open source version of Sidekiq) are:

* [heartbeat](https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/launcher.rb#L126-L189)
* [scheduler](https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/scheduled.rb#L78-L85)
* [process job fetching](https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/processor.rb#L94-L102)

It's possible there are additional aspects of Sidekiq Pro and Enterprise that could be traced, but that is not something I'm currently using, so I do not have much visibility into what those could be.

This naturally requires quite a bit more patching than is currently done for Sidekiq integration, so before I started going down the road of opening a PR with this kind of additional top-level span tracing, I wanted to take the team's temperature. Is this something dd-trace-rb would be open to accepting a PR for?

**Comment by marcotc** [comment]
I played around and verified that, currently, all the reported cases create a sole trace with a single Redis span, like so: 
![Screen Shot 2021-09-09 at 2 32 28 PM](https://user-images.githubusercontent.com/583503/132765473-511bf80a-6077-412b-993f-43d96f95af77.png)

Here are the Redis commands I was able to find that are being instrumented alone in such cases:

Scenario | Redis command being instrumented currently
--- | ---
[heartbeat](https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/launcher.rb#L126-L189) | https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/launcher.rb#L138-L154 & https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/launcher.rb#L161-L174
[scheduler](https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/scheduled.rb#L78-L85) | https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/scheduled.rb#L15-L33
[process job fetching](https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/processor.rb#L94-L102) | https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/fetch.rb#L47 & https://github.com/mperham/sidekiq/blob/ab90830e85e02304ac39dc29f8684c75564726de/lib/sidekiq/fetch.rb#L21-L23

Here's my take:

1. Do you see value in having these Redis commands traced at Datadog? If there's no reasonable action that can be taken from the information they provide, omitting them in `ddtrace` is an option. The possible Redis impact of heartbeat, scheduler, and job fetching would be omitted in this case, but that might be something that does not warrant fine grained information in the form of an APM trace like today. What do you think?
1. If you see such value, I highly encourage you to open a PR 🙇! Sidekiq is a very popular Ruby gem, thus additional visibility for it is always welcome, specially when it comes from users actively using it in production like yourself.

**Comment by agrobbin** [comment]
@marcotc great question, and I think it likely depends! I can definitely see folks wanting to see traces for scheduling/process job fetching, while heartbeat traces are probably less useful. Though, if tracing is added for 2 of the 3, the harm in adding the 3rd is probably pretty low.

Maybe an option that defaults to on but can be turned off, like `internal_traces`? I don't know if it's worth an option for *each* of these scenarios, particularly since it seems likely that there are others within Sidekiq Pro + Enterprise that could get added in the future, which could make for a messy integration. A single option though, could be useful! Does dd-trace have a way to temporarily disable tracing within a block?

If you're 👍🏻 on that, I'm happy to get a PR out that adds this kind of tracing. Testing it might be difficult, but I'm sure I can figure something out.
