### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mscrivo** [DataDog/dd-trace-rb#1682]
Hi,

I know this is rather vague report, but hoping it could help start a conversation and help us track down an issue together.

We've been successfully using APM for some time in our front end web services, and decided recently to turn it on for our background services as well (shoryuken, sidekiq workers, etc.).  At first, things seemed to be going ok, but after some time we noticed that one of our particularly heavy shoryuken jobs that takes many hours to run had not been completing.  Upon further inspection, it stopped working exactly when we enabled APM, and the cause was OOM killing the pods.  It took me quite a while to come to this realization, trying to hunt down the memory leak in our own code.  The only way I made the realization was after running the same job manually in a helper pod, which didn't have APM enabled and observing that memory usage was relatively constant.

For context, here's a bit more info about this job. Essentially, it's querying a bunch of large datasets, recombining the data into a different form, creating an array of hashes from that data and finally using Sequel to insert those hashes into a table in the DB.  To prevent memory overruns, we batch up the original queries and also batch up the inserts so that the array/insert statements never have more than 20k elements. (tried with lower limits as well, 10k for example and the memory leak still persisted). 

Here's memory usage of the exact same code running with APM off and on, respectively:

![image](https://user-images.githubusercontent.com/275524/133145381-02688d5c-d9d9-41ae-ba19-2c7b7eef3dbd.png)

![image](https://user-images.githubusercontent.com/275524/133145421-3f778ca8-8d92-4825-a0f3-60651d632b43.png)

Now, to be fair, this job is churning through tens of millions of records and objects, creating a table with hundreds of millions of records and it's not great at all. We have plans to get rid of it, but still, ddtrace should not be causing a memory leak like this. I've turned off APM for this job, but I'm wondering if this could be affecting workers too, to a lesser extent though.

Environment:

Ruby 3.0.2 running in bullseye-slim docker image
ddtrace-rb 0.52

**Comment by marcotc** [comment]
👋 @mscrivo,

> one of our particularly heavy shoryuken jobs that takes many hours to run

This might be less vague than you'd expect 🙂. Given your application is only accumulating memory with `ddtrace` enabled **and** this happens on a very long running job, I suggest you try [**partial flushing**](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#advanced-configuration):

```ruby
  c.tracer.partial_flush.enabled = false
```

This will break down very long traces into smaller chunks, and will flush such parts without having to wait until the whole job is finished. You memory usage (the part that is caused directly by `ddtrace`) should have a well-behaved ceiling with this option enabled.

Let us know if this improves the situation.

**Comment by mscrivo** [comment]
Thanks @marcotc! Will definitely give that a try.  Curious as to why that wouldn't be the default setting? Is there a downside?

**Comment by marcotc** [comment]
> Curious as to why that wouldn't be the default setting? Is there a downside?

Part of the built-in APM metrics (e.g `trace.rack.request.hits`, `trace.rack.request.errors`) are calculated in the Datadog agent. Because the agent receives partial traces when `partial_flush` is enabled, it thinks that the top-most span in the payload it receives from `ddtrace` is a top-level span and thus needs metrics calculated.

This causes sub-spans to have slightly inflated build-in metrics. But this **does not affect the top-level span** that you see in your service page, which accounts for the main metrics you see in your service page.

So, unless you are explicitly using sub-span metrics that are not advertised by the Datadog UI, you won't see any changes. Also, we have yet to receive any negative feedback from enabling `partial_flush`.

We have a plan in place to move metrics calculation from the agent to `ddtrace`, which will address this issue in the future.

**Comment by mscrivo** [comment]
Awesome, thanks for that info! Closing this out.

**Comment by marcotc** [comment]
@mscrivo, I'm assuming the issue was resolved with the earlier suggestion? I'm curious if the memory usage is now within acceptable limits for the job in question.

**Comment by mscrivo** [comment]
> 
> 
> @mscrivo, I'm assuming the issue was resolved with the earlier suggestion? I'm curious if the memory usage is now within acceptable limits for the job in question.

I've enabled partial flushing, but have not yet had a chance to observe the memory usage on that particular problematic job .. will let you know how it goes!

**Comment by mscrivo** [comment]
@marcotc Sadly, the partial flushing did not work, the pod still OOM'ed with it on.  I confirmed that the DDTRACE configuration did have: `"partial_flushing_enabled":true` in it.
