### ISSUE TITLE
Potential bug in DefaultContextProvider

### ISSUE THREAD

**Issue by apneadiving** [DataDog/dd-trace-rb#1691]
Hello!

I was browsing the `DefaultContextProvider` code and [read](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/context_provider.rb#L19):

```
    def context(key = nil)
      current_context = key.nil? ? @context.local : @context.local(key)
```
What looks suspicious is `@context.local(key)` because the `local` method expects a thread, not a key:
```
    def local(thread = Thread.current)
      thread[@key] ||= Datadog::Context.new
    end
```

I am unsure of the expected behavior so I can only leave the conclusion to you :)

**Comment by marcotc** [comment]
:wave: @apneadiving, thank you for raising this issue. I think what's confusing here is the naming of the argument `key`.

I've created a PR to rename this argument to `thread`, as this is the expected argument type for `#context`: https://github.com/DataDog/dd-trace-rb/pull/1692

**Comment by apneadiving** [comment]
thanks for the quick explanation/fix 🙂
