### ISSUE TITLE
ActiveJob service name prefix

### ISSUE THREAD

**Issue by dudo** [DataDog/dd-trace-rb#1703]
https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/rails/framework.rb#L135

We'd love to be able to override this service name, and tuck the AJ operation into the main service.

**Comment by marcotc** [comment]
👋 @dudo, https://github.com/DataDog/dd-trace-rb/releases/tag/v0.54.0 was just released, including this feature.
