### ISSUE TITLE
How to make this work with sidekiqswarm

### ISSUE THREAD

**Issue by justin808** [DataDog/dd-trace-rb#1705]
No matter how I order the commands, I get this error:

```
SIDEKIQ_PRELOAD_APP=1 SIDEKIQ_PRELOAD= CACHE_WARMER=true READ_ONLY_MAINTENANCE_MODE=true SIDEKIQ_MAXMEM_MB=1700 bundle exec ddtracerb sidekiqswarm -e $RACK_ENV -C config/sidekiq_cache_warmer.yml
Command 'sidekiqswarm' is not valid for ddtrace.
```

Reference: https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process

**Comment by justin808** [comment]
`bundle exec ddtracerb exec sidekiqswarm` works

**Comment by ivoanjo** [comment]
Glad you were able to figure it out! Feel free to reach out if you run into any other issue or have positive or negative feedback :)
