### ISSUE TITLE
Span information not available when tracing for GraphQL in Rails app

### ISSUE THREAD

**Issue by adrys-lab** [DataDog/dd-trace-rb#1741]
We are trying to add GraphQL Tracing Instrumentation to our new GraphQL API in a Rails application.

After configure the tracing under our schema as:

```
    module GraphQL
      class Schema < ::GraphQL::Schema
        use(::GraphQL::Tracing::DataDogTracing, {
          service: 'backend-graphql-api',
          analytics_enabled: true
        })
      end
    end
```

We don't see any SPAN information in the traces.

We correctly see the requested resource, the operation name, also the Hits and Latency in Datadog,

But we loose all the spans such as Database Queries, Redis....etc (which are present for all the rest of traces in the application).

![image](https://user-images.githubusercontent.com/35842560/139099269-2bac1086-26be-4ac8-b5e7-23a4f1ffa994.png)

We also tried to instrument it when the application bootstraps, on the Datadog.configure,
```
# Inside Rails initializer or equivalent
Datadog.configure do |c|
  c.use :graphql, schemas: [YourSchema], options
end
```

the problem we have there is that the `Datadog.configure` is triggered in a previous phase than the `Rails` boot phase, and as `schemas` is mandatory field, we can not provide it since the file/module has not been loaded yet.

can you please provide some insights on what can we be missing ?

**Comment by adrys-lab** [comment]
we Have updated the GEM version to 0.53 and the result is the same.

We see the APM Service data (requests, latency....etc)

![image](https://user-images.githubusercontent.com/35842560/139810248-69a1b61b-53d8-428f-9e71-ae50c245ffa2.png)


But as said, we still don't have SPAN details for each resource_name

![image](https://user-images.githubusercontent.com/35842560/139810320-86bf0e7f-ddc1-4e9b-a8f0-93d709d82239.png)

**Comment by ivoanjo** [comment]
Thanks for checking with 0.53.0; I was hoping it would help here. @marcotc I think we need your expert analysis :)

**Comment by adrys-lab** [comment]
we moved the `datadog` graphql configuration form the SCHEMA to the initializer.

`datadog-tracer.rb` with the rest of configurations we have (redis, aws, rake...etc).

```
require './components/platform/base/graphql/schema.rb'

require 'datadog/statsd'
require 'ddtrace'

....................

DATADOG_TAGS =
  {
    service_name: 'web',
    container_id: resolve_container_id,
    environment: Rails.env,
    revision: revision,
    framework: 'Rails',
    framework_version: Rails.version,
    component: ENV['BACKEND_API'].present? ? 'backend-api' : 'web'
  }

Datadog.configure do |c|
  service = 'web'
  hostname = resolve_datadog_hostname
  c.tracer(
    debug: true,
    env: Rails.env,
    priority_sampling: true,
    hostname: hostname,
    tags: DATADOG_TAGS,
    enabled: ENV['DATADOG_TRACER_ENABLED'].present?)

  c.diagnostics.debug = true

  c.runtime_metrics_enabled = true
  c.runtime_metrics(statsd: Datadog::Statsd.new(hostname, 8125))

  c.use(:rack)
  c.use(:rails, service_name: service, distributed_tracing: true)
  c.use(:sidekiq, analytics_enabled: true, service_name: "#{service}-sidekiq", client_service_name: "#{service}-sidekiq")
  c.use(:rake, analytics_enabled: true, service_name: "#{service}-rake", quantize: { args: { show: :all } })
  c.use(:aws, service_name: "#{service}-aws")
  c.use :redis, service_name: "#{service}-redis-cache"
  c.use :redis, describes: { host: ENV['REDIS_HOST'] }, service_name: "#{service}-redis-sidekiq"
  c.use(:elasticsearch, service_name: "#{service}-elasticsearch")

  c.use :graphql, schemas: [::Platform::Base::GraphQL::Schema], analytics_enabled: true, service_name: ENV['BACKEND_GRAPHQL_API'].present? ? 'backend-graphql-api' : 'web'

  Rails.logger.warn do
    {
      event: 'Configured Datadog with',
      message: c.pretty_inspect,
    }
  end

  Rails.logger.warn do
    {
      event: 'Tracer Configured',
      message: c.tracer.pretty_inspect,
    }
  end
end
````


There we had a problem because  using this way, we need to provide SHCEMAS parameter, 
But as this initialization happens before the rails initialization, the Schema file was not loaded yet,

that is why we had to add the explicit `require`:

require './components/platform/base/graphql/schema.rb'

**Comment by adrys-lab** [comment]
Any feedback in this issue @marcotc @ivoanjo ???

**Comment by marcotc** [comment]
👋 @adrys-lab, I took at look at your service page, and it looks like the GraphQL spans are being considered root spans, which could only happen if, for example, the `Graphql__Number__NUMBER_QUERY` query was performed outside of any web requests, sidekiq jobs or rake tasks, which seems unlikely:
![Screen Shot 2021-11-05 at 3 57 29 PM](https://user-images.githubusercontent.com/583503/140587226-d6db0911-7e09-40ba-a5bb-12e7c9ebaa8b.png)
(raw data)
![Screen Shot 2021-11-05 at 3 56 42 PM](https://user-images.githubusercontent.com/583503/140587166-ad752231-43a1-4440-8709-df98927063da.png)

I checked the trace retention control, just to be sure that no traces are being dropped by after they've been captured by `ddtrace`, but your retention rate seems to be at 100% for the service related to the GraphQL spans: (https://app.datadoghq.com/apm/traces/ingestion-control?env=staging&start=1634943122382&end=1636152722382&paused=false)

I also noticed that you have runtime metrics enabled, `c.runtime_metrics_enabled = true`, which is good, but I don't see any runtime metrics being successfully submitted, which is concerning, as this metric submission is unrelated to the tracing components of `ddtrace`: 
![Screen Shot 2021-11-05 at 3 53 45 PM](https://user-images.githubusercontent.com/583503/140587011-e574e476-6678-4265-ac09-12f35c01e0e4.png)

Given that you have a pretty standard setup (Rails application with GraphQL, Sidekiq, AWS, and ElasticSearch), but the tracing information and metrics information are simply not displaying as expected, I think this might be an issue involving more than `ddtrace`.

I suggest as the next step that you open a formal support ticket with our team, as they are better equipped to diagnose issues that span the whole Datadog data pipeline: https://www.datadoghq.com/support/

Please link them to this GitHub issue, so our team can get the context we've already discussed here, as to expedite the investigation.

**Comment by adrys-lab** [comment]
@marcotc thank you so much for your answer and detail.

This week, we opened already a Zendesk ticket in Datadog support.

Here you have it for more details, https://help.datadoghq.com/hc/en-us/requests/585512?page=1

just in case you can contribute there or provide them the information you found and correlate all.

thanks a lot

**Comment by TonyCTHsu** [comment]
Hi @adrys-lab , it looks like the issue has already been resolved by Datadog support. 

I am closing this issue for now, but feel free to reopen it if you require more help.
