### ISSUE TITLE
Git branch not detected from Buildkite CI environment

### ISSUE THREAD

**Issue by langsharpe** [DataDog/dd-trace-rb#1745]
Buildkite always includes the BUILDKITE_TAG environment variable, causing the branch to be overwritten.

HEAD is the only branch reported
<img width="187" alt="Screen Shot 2021-11-01 at 09 08 32" src="https://user-images.githubusercontent.com/365913/139604292-9f2a81da-1a5a-4725-bded-fdc7019ddc8a.png">

Buildkite environment including empty variables
![CleanShot 2021-11-01 at 09 03 44](https://user-images.githubusercontent.com/365913/139604490-e09833e4-2da1-4ca0-ae1f-d5e9d327ac03.png)

"".nil? is false, so the branch gets deleted

https://github.com/DataDog/dd-trace-rb/blob/735404e3c94b413bf9146b2986abcf95eae0da43/lib/datadog/ci/ext/environment.rb#L48

**Comment by delner** [comment]
I've forwarded this one to our CI team.

**Comment by marcotc** [comment]
👋 @langsharpe, https://github.com/DataDog/dd-trace-rb/releases/tag/v0.54.0 was just released, including a fix for this issue.
