### ISSUE TITLE
ddtrace is causing slowness in rspec

### ISSUE THREAD

**Issue by flovilmart** [DataDog/dd-trace-rb#1748]
Hi! 
We've encountered this issue when using ddtrace with rspec

When running with knapsack pro, a first pass with `--dry-run` is performed and this is a flamegraph that's produced when running a single of our spec files:

<img width="1263" alt="Screen Shot 2021-11-01 at 2 44 51 PM" src="https://user-images.githubusercontent.com/364568/139748075-00ebe47e-075b-451a-84b9-cdc8ce689e14.png">

We see that the CPU spends more time producing trace tags for git than anything else.
By caching the git tags this is what we get:

![image](https://user-images.githubusercontent.com/364568/139748277-a5323b76-43ed-4a9e-8fe7-0446b4095b22.png)

And the speed up
![image](https://user-images.githubusercontent.com/364568/139748798-35e837b7-3817-4fa4-a666-68c08295d1ca.png)

The [Environment](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/ci/ext/environment.rb#L431-L453) could be patched to cache the result of the `extract_local_git` so the library don't shell out as much.
My understanding is that those values should be the same for a single execution and are unlikely to change from one initialization to another.

Would that fix be acceptable?

**Comment by delner** [comment]
@flovilmart Thank you for the report and the suggestion! Caching might be a good way to go about this (as I doubt the git tags would change at all during a run in RSpec.) Just curious, what's the speed up gained by caching?

If you'd like to submit a PR for this, that would be most welcome. Otherwise we'll flag this for review and try to get something in for this.

**Comment by flovilmart** [comment]
we have 20000 tests; Without the fix it takes roughly 10 minutes to finish (our CI was timing out), with the fix, about 31 seconds (including 20.33s of file loading), as shown in the screenshot.

I can submit a PR, no problem!

**Comment by delner** [comment]
Quite significant then; this would be a big improvement. Looking forward to the PR!

**Comment by dannyrb** [comment]
Thanks for the report and PR, @flovilmart! We have a similarly sized code base and slowdown. Curious to see if this patch alleviates the issues we are experiencing.
