### ISSUE TITLE
Datadog/ci: callback for add_tags

### ISSUE THREAD

**Issue by dannyrb** [DataDog/dd-trace-rb#1759]
Hello! We recently started using DataDog's CI Test Instrumentation for a large RSpec suite (25k tests). We would like to add additional tags that are explicitly called out in the default DataDog Dashboard for "Test Runs"

Is there an easy way to, as a part of configuration, hook into the add_tags call for a given test or test suite run?

Is there a different existing approach that is preferred?

Or is the assumption that if additional tags are desired, that the extension should be forked to accommodate changes?

**Comment by marcotc** [comment]
👋 @dannyrb, if you are looking to add tags to all your spans during RSpec test runs, you can use the `DD_TAGS` environment variable (or `c.tags = { 'team' => 'qa'}` in your `Datadog.configure` if you'd prefer the programmatic approach): https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#environment-and-tags

Let us know if your case is different, and can't use global tags like this suggestion.

**Comment by dannyrb** [comment]
Thanks for the quick response, @marcotc! I think, ideally, we need something that is either `test` or `test suite` specific. We were hoping we could:

1. Use RSpec "tags" to add metadata to a test or test suite:

```rb
require "spec_helper"

describe ExampleService, dd_testowner: :some_team do
  # ...
end
```

2. Use RSpec metadata to set tag(s) for the test suite or test run

```rb
# spec/spec_helper.rb
RSpec.configure do |config|
  config.around(:dd_testowner) do |example|
    
    # Use this value to set tag for test run or test suite:
    # example.metadata[:dd_testowner]

    example.run
  end
end
```

We're in a bit of a massive monolith today, with oddities around how we split and run tests. Otherwise, we might use tags to only run a specific owner's tests, and set the tag globally before the run.

**Comment by marcotc** [comment]
@dannyrb nice to see you found a way!

Btw, I suggest you simplify how you retrieve the active_span, to use a better supported interface:
```diff
--- active_span = Datadog.configuration[:rspec][:tracer].active_span
+++ active_span = Datadog.tracer.active_span
```

For context, there only ever on trace in memory, so `Datadog.configuration[:rspec][:tracer] == Datadog.tracer`, and also we are removing `Datadog.configuration[:my_gem_name][:tracer]` in the future, so it makes your code more future proof.
