### ISSUE TITLE
Request: Nightly version, or more frequent releases

### ISSUE THREAD

**Issue by dannyrb** [DataDog/dd-trace-rb#1768]
It's been great to see the frequent activity and enhancements coming down the pipe for this library; however, I wish I could test them out in our codebase sooner rather than later. This would allow us to:

- Provide feedback on unreleased changes before they're published more broadly/formally
- Leverage new features/functionality sooner

 Would the creation of a new "nightly" CircleCI workflow be an enhancement y'all would consider for merge? Is there any guidance or discussion you would like to have before a PR is attempted to add the functionality?

**Comment by dannyrb** [comment]
Was not aware this would work OOTB:

```
gem "ddtrace", git: "https://github.com/DataDog/dd-trace-rb.git", ref: "9e75a24"
```

**Comment by marcotc** [comment]
Hey @dannyrb, we can actually do better here by having an official test release published frequently.

Today we do publish every commit that passes CI to our internal gem repository.
For example, the latest master commit, as of today, [was published by this CI job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/4658/workflows/3d039a92-e71b-42c8-83f9-e1c1854bca30/jobs/175870), and can be installed like so:
```ruby
source 'http://gems.datadoghq.com/prerelease-v2' do
  gem 'ddtrace', '0.53.0.master.175870'
end
```

This works great if you are looking to pin the version of `ddtrace` to a specific commit, but doesn't help you upgrade to a newer version if you'd like. It would be good to have something like:

```ruby
source 'http://gems.datadoghq.com/prerelease' do
  gem 'ddtrace'
end
```

That allows you to `bundle update ddtrace` when you'd like to upgrade it to the latest pre-release. (P.S. This snippet will technically install `ddtrace` today, but will install a very old version. Please don't use it 🙂)
