### ISSUE TITLE
Dalli::Server is deprecated, use Dalli::Protocol::Binary instead

### ISSUE THREAD

**Issue by nbibler** [DataDog/dd-trace-rb#1777]
Recent versions of [dalli](https://rubygems.org/gems/dalli) (v3.0.0+) have deprecated `Dalli::Server`. That class has been renamed to `Dalli::Protocol::Binary`, but otherwise I believe the interface is similar.

The usage of `Dalli::Server` in this library causes deprecation warning emissions at application start up, most likely from the following call:

https://github.com/DataDog/dd-trace-rb/blob/e391d2eb64d3c6151a4bdd2710c6a8c7c1d57457/lib/ddtrace/contrib/dalli/patcher.rb#L20-L22

**Comment by marcotc** [comment]
Thank you for the report, @nbibler. This seems like a straightforward issue to be addressed: use `Dalli::Protocol::Binary` for dalli >= 3 and `Dalli::Server` for dalli < 3.
