### ISSUE TITLE
Missing container id with cgroup v2 + docker 20.10 and up

### ISSUE THREAD

**Issue by lloeki** [DataDog/dd-trace-rb#1810]
Starting with Docker 20.10 and on a distro that supports cgroup v2 (e.g ArchLinux or Debian 11) it is not possible anymore to obtain the container id as it was with cgroup v1 (via either `/proc/$pid/cgroup` or `/proc/$pid/cpuset`).

The consequence [within the tracer](https://github.com/DataDog/dd-trace-rb/blob/0aeb038831e8ccf7efc58bdc56eeb2af5bdd98a6/lib/datadog/core/environment/cgroup.rb#L25-L48) is that the cgroup value is always `0::/` and thus `path` is `/` as far as I observed, and since no container id can be obtained the `Datadog-Container-ID` header is never set for the HTTP transport ([tracer](https://github.com/DataDog/dd-trace-rb/blob/0aeb038831e8ccf7efc58bdc56eeb2af5bdd98a6/lib/ddtrace/transport/http.rb#L70-L72), [profiler](https://github.com/DataDog/dd-trace-rb/blob/0aeb038831e8ccf7efc58bdc56eeb2af5bdd98a6/lib/ddtrace/profiling/transport/http.rb#L61-L63). This happens *completely silently*, save for system tests which tested for that in a test case that now fails on my ArchLinux VM.

See [this SO question](https://stackoverflow.com/questions/68816329/how-to-get-docker-container-id-from-within-the-container-with-cgroup-v2), which appears to be relevant, but I find the proposed answer to be somewhat brittle (looking at overlay2 type mounts and divining indirect values from that).

**Comment by knusbaum** [comment]
It looks like this will be very difficult to solve in the tracers. Please see this agent PR for an agent-side solution. It should only require that the tracer uses UDS to connect to the agent:
Please see: https://github.com/DataDog/datadog-agent/pull/11584

**Comment by ivoanjo** [comment]
Since this looks like it's going to be solved on the agent side, I'm going to go ahead and close it. @lloeki if you still prefer to track this from our side as well, please do reopen :)
