### ISSUE TITLE
Consider having a CHANGELOG, CHANGES file 

### ISSUE THREAD

**Issue by cabello** [DataDog/dd-trace-rb#186]
I was watching the memory issue issue and I see it got addressed on today's release 0.8.2, I wanted to broadcast to my team members what changes were included in this version and I couldn't find release notes/changelog/changes file, I know the gem is still under heavy development (being on version 0.X) but this would be highly beneficial for users of the gem.

Thanks for considering it.

**Comment by palazzem** [comment]
hello @cabello ! at the moment we're only using the GitHub release so all details about the changes are here: https://github.com/DataDog/dd-trace-rb/releases/tag/v0.8.2

I includes also a full changeset diff, but maybe it could be better to write it also in a CHANGELOG file?

**Comment by cabello** [comment]
That's actually great, thank you.

**Comment by palazzem** [comment]
@cabello you're welcome! feel free to create an issue whenever you think we can improve our process or our communications about important changes! it helps us a lot! thanks again!
