### ISSUE TITLE
Add support for WaterDrop and Karafka 2.0

### ISSUE THREAD

**Issue by mensfeld** [DataDog/dd-trace-rb#1877]
Hey,

I'm the author of WaterDrop and Karafka framework (https://github.com/karafka/karafka). I've been frequently requested and asked for a DD integration. I have DD integration for WaterDrop in progress (should be done in a week or so) but I would appreciate help in getting info on how to ship one for Karafka using dd-trace-rb presented here as well as some info on how can I ship my WaterDrop one here as well (standalone Kafka producer).

**Comment by delner** [comment]
Thanks for dropping a line @mensfeld ! Awesome to see that you'd like to add some instrumentation out of the box.

Generally speaking you have a few options when implementing instrumentation for your library, to share with the public:

1. **Create an integration within `ddtrace` and submit it in a pull request back to this repo**. Instrumentation will come out-of-the-box for any user of `ddtrace`. Upside is we will help maintain the Datadog portion of the instrumentation (use of API, conventions, etc), downside is that it must be updated here (as opposed to within your library) and is tied to our release schedule.
2. **Add instrumentation directly to your library itself**. Instrumentation will come out-of-the-box for any user of your library. Upside is you would have complete control over how it is configured, implemented and managed. Downside is we won't provide maintenance implicitly; you would be using `ddtrace` like you would any other library.
3. **Create a new repo and package that hosts just the instrumentation for Datadog + your library**. We haven't seen this practiced yet, but its another possibility.

Generally we recommend option (1) as it's easiest to maintain. Option (2) has been done (with GraphQL) but has been more difficult to work with.

Regarding implementation of the instrumentation itself, we recommend checking out our existing integrations for the closest analog to what your library does and more or less replicate it. We have a small section in [our development guide](https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md#writing-new-integrations) that describes general requirements for new integrations as well, if you decide to go with option (1).

Hope that helps! Please let me know if you have any other questions. We love to see contributions like this and are happy to support developers in any way we can.

**Comment by mensfeld** [comment]
Hey, going to close this. I created integration in libraries:

- https://github.com/karafka/waterdrop#datadog-and-statsd-integration
- https://karafka.io/docs/Monitoring-and-logging/#datadog-and-statsd-integration
