### ISSUE TITLE
ActiveRecord exec_params not reporting to APM

### ISSUE THREAD

**Issue by dilumn** [DataDog/dd-trace-rb#1879]
In my application, I am doing some manual query string generation & fetch data from my postgres db

```
query = "SELECT COUNT(*) FROM tablename"
conn = ActiveRecord::Base.connection.raw_connection
result = conn.exec_params(query)
```

But I noticed these queries are not available in APM services postgres stats.

Do I need to do any config changes to allow those queries appear in APM? or am I doing something wrong here

**Comment by delner** [comment]
If you've done `c.use :active_record` or `c.use :rails` in your configuration, then this should work. However, it is possible (if not likely) that if you're executing a raw query that ActiveRecord is not triggering the `sql` notification event, in which case a span will not be created. If this is the case, we would need to add more instrumentation hooks around the connection object itself.

**Comment by jennchenn** [comment]
Hi @dilumn! We recently added instrumentation to the `pg` gem in version `1.2.0`--using this version, you should be able to see `pg` spans generated from your code snippet, for example:
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/32009013/179795430-a5fd1137-3f05-4b5e-8b54-3c1736cd5a31.png">
Let me know if you get a chance to try it out and if it works for you!

**Comment by dilumn** [comment]
Hi @jennchenn thank you very much for reply. I will check it later. For now will close the issue
