### ISSUE TITLE
0.54.0 Broke App Analytics

### ISSUE THREAD

**Issue by buddhistpirate** [DataDog/dd-trace-rb#1905]
Heyo. So we are a customer that uses the App Analytics feature until a future single-span control system is in place.

We are on an older version of the client (0.50.0) with app analytics configured for our top level spans and a sampling rate of 15% specified otherwise. I upgraded to 0.54.2 in order to stay up to date. 

In my testing with 0.54.2 I found that I was only seeing 15% of requests via the Live 15m view compared to 0.50.0 where I would see 100% of the top level spans due to the app analytics configuration.

I ran the client in debug mode and saw a difference between the old version and new version:

Version 0.50.0:
```
Metrics: [   
_dd.rule_psr => 0.01,   
system.pid => 27978.0,   
request_queuing => 37.63291035461426,   
_dd1.sr.eausr => 1.0,  
 _dd.measured => 1.0,   
_sampling_priority_v1 => 0.0]
```

Version 0.54.2:
```
Metrics: [   
_dd.rule_psr => 0.01,   
system.pid => 28082.0,   
request_queuing => 2.9489923706054686,   
_dd1.sr.eausr => 1.0,   
_dd.measured => 1.0,   
_sampling_priority_v1 => -1.0]
```

The difference here is `_sampling_priority_v1 => -1.0` in 0.54.2. Looking at the code, this is the difference between a `USER_REJECT` and an `AUTO_REJECT`. My naive understanding from having looked at the code (and the comments) is that a `USER_REJECT` will prevent the agent from forwarding the trace, while an `AUTO_REJECT` gives more leeway to the agent to decide to send it. My guess is that `_dd1.sr.eausr => 1.0, _dd.measured => 1.0, ` along with `AUTO_REJECT` enables the agent to forward all spans marked as such, but with a `USER_REJECT` it will not.

I believe this change was introduced with #1769 in version 0.54.0.

For now we will stay at 0.53.0, but I wanted to call this out as it will blocked us from upgrading further.

**Comment by delner** [comment]
I think the purpose behind this change was to delineate user decisions (via sampling rules) from automatic decisions. Do you have sampling rules in place? What do those look like?

**Comment by buddhistpirate** [comment]
I believe these are the relevant configuration options.

```
Datadog.configure do |config|
  c.sampling.default_rate = 0.0.1
  c.use :rack, analytics_enabled: true
  c.use :sidekiq, tag_args: true, analytics_enabled: true
```

**Comment by marcotc** [comment]
👋 @buddhistpirate, if I understand your requirements correct, as "Capture 100% of Sidekiq traces. Other traces, capture 15%.", you can implement this ingestion control using the following configuration:

```ruby
# ddtrace 0.x series
Datadog.configure do |c|
  c.tracer.sampler = Datadog::PrioritySampler.new(
    post_sampler: Datadog::Sampling::RuleSampler.new(
      [Datadog::Sampling::SimpleRule.new(name: /\Asidekiq\./, sample_rate: 1.0)],
      default_sample_rate: 0.15
    )
  )
end
```

```ruby
# ddtrace 1.x series
Datadog.configure do |c|
  c.tracing.sampler = Datadog::Tracing::Sampling::PrioritySampler.new(
    post_sampler: Datadog::Tracing::Sampling::RuleSampler.new(
      [Datadog::Tracing::Sampling::SimpleRule.new(name: /\Asidekiq\./, sample_rate: 1.0)],
      default_sample_rate: 0.15
    )
  )
end
```

This configuration will apply a sampling rate of `1.0` (100%) to all spans with a `name` that starts with `sidekiq.`, which represents all spans created by the Sidekiq integration of ddtrace. For all other spans, the default sampling rate is set to 0.15 (15%).
Notice that the first argument to `RuleSampler.new` is an array. This is an ordered list of sampling rules to be applied to each trace. Here we have the single Sidekiq related rule, and if no rules match, we use the `default_sample_rate` provided.
Feel free to tweak this as needed.

Let me know if I interpreted the configuration you desire incorrectly, or if you need any other help regarding this GH issue.

**Comment by buddhistpirate** [comment]
Hi @marcotc . We have our normal sample rate set to 1% for both our web requests and our sidekiq jobs. The breakage here is now the App Analytics configuration no longer works as it is overridden by the normal sampling. We had our App Analytics rate set to 100% for `rack` and `sidekiq`. The breakage for us means we will be sending the full trace (all the spans) for every request, since we want to index 100% of the top level spans if we want to keep our current functionality. This will cost us a ton of money in ingestion costs. 

The way it worked for us before the referenced PR changed it:
Send 100% of the top level spans to then be retained via Retention Filters
Send 1% of our traffic as full traces. (the normal sampling rate)

The relevant parts of our configuration:

```
Datadog.configure do |c|
  c.sampling.default_rate = 0.01
  c.use :rack, analytics_enabled: true
  c.use :sidekiq, analytics_enabled: true
end
```

Does that clarify the issue?

**Comment by buddhistpirate** [comment]
Closing this issue as we have upgraded to v1+ and are now using Single Span Sampling to get this behavior. Thanks!
