### ISSUE TITLE
sample code of Sinatra integration  does not work with classic style application

### ISSUE THREAD

**Issue by okazu-dm** [DataDog/dd-trace-rb#1935]
I found sample code of Sinatra integration does not work if application is classic style.

I mean [This sample code](https://github.com/DataDog/dd-trace-rb/blob/5c316c0cabdc24cbe80136fdbbada0f3ed2bd8f9/docs/GettingStarted.md#sinatra) has a problem.
Sinatra classic style application start in at_exit 
 https://github.com/sinatra/sinatra/blob/2b5d1b45097f67c06a2345f0d8c30db2b38030bf/lib/sinatra/main.rb#L45
and `Datadog::Writer.stop_worker` method is called in at_exit
  https://github.com/DataDog/dd-trace-rb/blob/v0.54.2/lib/ddtrace/writer.rb#L97 

So current sample code means following execution order
1. Datadog::Writer.stop_worker is executed
2. Sinatra::Application.run!

(at_exit handlers are executed in reverser order of registration https://ruby-doc.org/core-3.1.1/Kernel.html#method-i-at_exit)

https://gist.github.com/okazu-dm/480f6188d2be7573b07c364cfac14194

**Comment by delner** [comment]
Thanks for the report!

I haven't dug into Sinatra's internals yet. Do you know why this `at_exit` hook exists in Sinatra code? I can see how the order issue causes problems, but it's not clear why 1) Sinatra is using this to start(?) an application and 2) why `at_exit` is triggered at all while starting up an application.

It's also surprising to me that this slipped through our unit tests. Something worth looking at why.

**Comment by TonyCTHsu** [comment]
👋 @okazu-dm , have you resolved this issue? Recently, we have introduced a bunch of improvement at [`1.6.0`](https://github.com/DataDog/dd-trace-rb/pull/2217) for Sinatra, give it a try and tell us about it 😉
