### ISSUE TITLE
Elasticsearch integration is not compatible with the latest elastic-transport gem

### ISSUE THREAD

**Issue by h6ah4i** [DataDog/dd-trace-rb#1950]
The `Elasticsearch::Transport::Client` class has been renamed to `Elastic::Transport::Client` and it breaks the dd-trace-rb integration.

ref.) https://github.com/elastic/elastic-transport-ruby#example-usage

**Comment by ivoanjo** [comment]
Hello @h6ah4i and thanks a lot for the report!

You are very right. It looks like the gem even got renamed -- it was previously called [`elasticsearch-transport`](https://rubygems.org/gems/elasticsearch-transport) and the new one is just called [`elastic-transport`](https://rubygems.org/gems/elastic-transport). This also explains why our CI didn't pick up this incompatibility.

We'll look into updating this, but if you'd like to take a stab, patches are very welcome.

**Comment by delner** [comment]
Seems like we need to support both gems; for those using the new version, and legacy applications still using the old.

We could likely add this as a part of the existing `elasticsearch` integration, so it's seamless for `ddtrace` users already instrumenting this (it will patch either `elaticsearch-transport` or `elastic-transport` depending on what's available.)

We currently don't have bandwidth to implement this, but we can add it to our TODO list. Contributions are always welcome as well.
