### ISSUE TITLE
1.0.0 regression: can't override configuration for httpx

### ISSUE THREAD

**Issue by HoneyryderChuck** [DataDog/dd-trace-rb#2002]
I'm having issues upgrading [httpx datadog adapter to the recent 1.0 release](https://gitlab.com/honeyryderchuck/httpx/-/compare/master...fix-datadog-1.0?from_project_id=4750239) , where overriding configuration parameters in test mode's not overriding anything. Here's an example which is reproducible in the console from the dev branch:

```ruby
require "ddtrace"
require "https/adapters/datadog"

> Datadog.registry[:httpx].configuration.to_h
# {:analytics_enabled=>false,
# :analytics_sample_rate=>1.0,
# :enabled=>true,
# :service_name=>"httpx",
# :distributed_tracing=>true,
# :split_by_domain=>false,
# :error_handler=>#<Proc:0x00007fcef23dc2a0 /home/httpx/lib/httpx/adapters/datadog.rb:174 (lambda)>}
Datadog.configure do |c|
  c.tracing.instrument(:httpx, {enabled: false})
end
Datadog.registry[:httpx].configuration[:enabled] #=> true
```

Anything obvious in the diff I should be doing instead?

**Comment by marcotc** [comment]
👋 @HoneyryderChuck, thank you for reaching out, and for upgrading your gem to ddtrace v1.0.0 so quickly. 🙇 

I found the main issue you are encountering. This breaking change took place in v1.0.0:

```ruby
--- a/lib/httpx/adapters/datadog.rb
+++ b/lib/httpx/adapters/datadog.rb
@@ -240,7 +240,7 @@ module TRACING_MODULE # rubocop:disable Naming/ClassAndModuleCamelCase
           super && version >= MINIMUM_VERSION
         end

-        def default_configuration
+        def new_configuration
           Configuration::Settings.new
         end
```

It's documented in our [UpgradeGuide](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#breaking-changes), but hard to find amongst the whole table of breaking changes.
I suggest you take a look at the other [`Category: Integrations` breaking changes in this table ](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#breaking-changes), there's only a few and I think your gem is doing all the other ones correctly.

I'll see if I can draw more attention to these breaking changes for external integration maintainers.

Please let us know if the issue still persists. We can reopen this issue if that's the case.

**Comment by HoneyryderChuck** [comment]
Thx for the help, I've managed to make it work. I'll leave here a link to the [Merge Request](https://gitlab.com/honeyryderchuck/httpx/-/merge_requests/202), in case you have some final suggestions. Will merge and release tomorrow.
