### ISSUE TITLE
There's no continue_from! method

### ISSUE THREAD

**Issue by nothrow** [DataDog/dd-trace-rb#2014]
[Documentation suggests to use `continue_from!`](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md?plain=1#L468). However, there is no such a method (not even in source code). I'm not sure if the documentation is not up-to-date, or the method disappeared for some other reason.

**Comment by ivoanjo** [comment]
Oooops! This should be `Datadog::Tracing.continue_trace!`. We'll fix the docs, thanks for pointing it out!
