### ISSUE TITLE
Prefer `require_relative`.

### ISSUE THREAD

**Issue by ioquatix** [DataDog/dd-trace-rb#2077]
Not only is it more efficient, it's also more predictable.

**Comment by marcotc** [comment]
Hey @ioquatix, we are looking into working this issue.

We can measure that it is more efficient, but would you have more information about the increased predictability?

**Comment by ioquatix** [comment]
Because it works without `$LOAD_PATH` being set up correctly.

**Comment by ioquatix** [comment]
Wow awesome!

**Comment by ivoanjo** [comment]
Marco is on a coding spree! :D
