### ISSUE TITLE
Mongo plugin not showing up in Datadog

### ISSUE THREAD

**Issue by KieranP** [DataDog/dd-trace-rb#2083]
Using latest version, configuring Mongo plugin does not show up in Datadog web UI.

```ruby
Datadog.configure do |c|
  c.service = ENV['company_key']

  ...snip...

  c.tracing.instrument :mongo,
    service_name: "#{c.service}-mongodb"

  ...snip...
end
```

I would expect a mongodb service to show up in Datadog UI but it doesn't.

All my other services have (AWS, rails, memcache, redis, sidekiq, net/http, etc), but not MongoDB

Is the mongo integration currently non-functioning after the 1.0 upgrade?

**Comment by delner** [comment]
I don't have any reason to believe Mongo isn't working in 1.0: our CI builds are passing. However, if they're missing for you, I certainly want to make sure it's not a bug.

I will try to replicate on my end with an app. However, it's usually more effective if we can narrow things down first with an app that presents the issue. Anything you can provide that can help me reproduce/diagnose this will be helpful (config, logs, etc)

**Comment by KieranP** [comment]
@jennchenn None of the mongo operations/traces are making their way to Datadog. All the other instruments (rails, aws, dalli, redis, etc all work). Just mongo traces not working.

Ruby 2.7.5
Rails 5.2.6
Mongo 2.17.1
Mongoid 6.4.8
ddtrace 1.1.0

Full Datadog initializer:

```
if defined?(Datadog)
  require 'aws-sdk-s3'
  require 'dalli'
  require 'excon'
  require 'faraday'
  require 'mongo'
  require 'net/http'
  require 'redis'
  require 'rest_client'

  require 'datadog/tracing'

  Datadog.configure do |c|
    c.service = ENV['company_key']
    c.env = Rails.env.to_s

    revision_path = Rails.root.join('REVISION')
    if revision_path.exist?
      version = revision_path.read
      c.version = version.strip.first(7)
    end

    c.tracing.enabled = c.service.present?

    c.tracing.instrument :rails,
      service_name: "#{c.service}-rails"

    c.tracing.instrument :active_support,
      cache_service: "#{c.service}-cache"

    c.tracing.instrument :rack,
      web_service_name: "#{c.service}-nginx",
      request_queuing: true

    c.tracing.instrument :aws,
      service_name: "#{c.service}-aws"

    c.tracing.instrument :dalli,
      service_name: "#{c.service}-memcache"

    c.tracing.instrument :excon,
      service_name: "#{c.service}-excon"

    c.tracing.instrument :faraday,
      service_name: "#{c.service}-faraday"

    c.tracing.instrument :http,
      service_name: "#{c.service}-http"

    c.tracing.instrument :mongo,
      service_name: "#{c.service}-mongodb"

    c.tracing.instrument :redis,
      service_name: "#{c.service}-redis"

    c.tracing.instrument :rest_client,
      service_name: "#{c.service}-restclient"

    c.tracing.instrument :sidekiq,
      service_name: "#{c.service}-sidekiq-server",
      client_service_name: "#{c.service}-sidekiq-client"
  end
end
```

**Comment by jennchenn** [comment]
@KieranP thanks for providing additional details! I have now set up a simple rails app that connects to a Mongo database, but I'm unfortunately still unable to reproduce your issue. Do you mind taking a look at how I have things configured/invoked, and see if you spot anything that is different in your application that could be causing the difference in behavior? It would be incredibly useful as well if you could share an example of how you're invoking `mongo` in your application so I can try to reproduce the same behavior.

### Versions
* `ruby 2.7.5`
* `rails 5.2.6`
* `mongo 2.17.1`
* `mongoid 6.4.8`
* `ddtrace 1.1.0`
* I'm running the database locally via Docker (using the image `mongo:latest`). 

### Initializer `datadog.rb`:
```ruby
if defined?(Datadog)
  require 'mongo'

  # require 'datadog/tracing'
  require 'ddtrace'

  Datadog.configure do |c|
    c.service = ENV['company_key']
    c.env = Rails.env.to_s

    c.tracing.enabled = c.service.present?

    c.tracing.instrument :rails,
      service_name: "#{c.service}-rails"

    c.tracing.instrument :mongo,
      service_name: "#{c.service}-mongodb"
  end
end
```
I use `require 'ddtrace'` in the initializer, but I tried using `require 'datadog/tracing'` as you have written in your comment as well; both seem to produce the same behavior in this case. However, I believe our tracer setup docs include the tracer with `require 'ddtrace'`.

### Controller using Mongo Client `basic_controller.rb`
```ruby
require 'mongo'

class BasicController < ApplicationController
  def index
    client = Mongo::Client.new([ "#{ENV['TEST_MONGODB_HOST']}:#{ENV['TEST_MONGODB_PORT']}" ], :database => "#{ENV['TEST_MONGO_INITDB_DATABASE']}")
    db = client.database
    db.collections  # "operation"=>"listCollections"
    collection = client[:dogs]
    collection.insert_one({ name: 'Bits' })  # "operation"=>"insert"
    @dogs = collection.find({ name: 'Bits'}).first  # "operation"=>"find"
  end
end
```

### Controller using mongoid (autogenerated) `people_controller.rb`
I also tried using `mongoid` by following the setup instructions [here](https://www.mongodb.com/docs/mongoid/current/tutorials/getting-started-rails/) (i.e. running `bin/rails g scaffold Person name:string`):

```ruby
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name)
    end
end
```

**Comment by jennchenn** [comment]
Hi @KieranP, I haven't heard back from you in a while so hopefully this is no longer an issue for you! I will be closing this for now, but if you're still experiencing the same problem feel free to re-open it and I can work with you to get it fixed.
