### ISSUE TITLE
Datadog is not working on the CI - issue with require'ing files 

### ISSUE THREAD

**Issue by michal-samluk** [DataDog/dd-trace-rb#2084]
Docker build fails after running `rake assets:precompile` with error: 
```
LoadError: cannot load such file -- datadog/core/git/ext
```

Everything is working properly locally. Currently I do not see any meaningful differences between local and CI environment. 
Disabling zeitwerk and/or bootsnap did not fix the issue.

**Comment by ivoanjo** [comment]
Hopefully you're all sorted Michał! Do feel free to reach out to us or support if you run into any issues :)
