### ISSUE TITLE
Rails traces not assigned any names (after moving from <1 to 1.1.0)

### ISSUE THREAD

**Issue by viraptor** [DataDog/dd-trace-rb#2092]
**Current behaviour**

I'm seeing traces under the configured service name as `GET 200` only and the real names under plain `webserver`.

The visible spans look like this:
![Screen Shot 2022-06-17 at 4 50 55 pm](https://user-images.githubusercontent.com/188063/174242154-8413bcc1-3c16-4428-9e97-260ca8eb6402.png)

**Expected behaviour**

The rails application is listing the controllers/methods again, or the new webserver resource is named with the service prefix.

**Steps to reproduce**

Configuration change during upgrade:
```
 Datadog.configure do |c|
-  c.tracer.enabled = Rails.env.production?
+  c.tracing.enabled = Rails.env.production?
 
-  c.tracer.sampler = Datadog::RateSampler.new(0.1)
+  c.tracing.sampling.default_rate = 0.1
 
@@ -19,10 +19,12 @@ Datadog.configure do |c|
   c.version = GitInfo.instance.revision
   c.runtime_metrics.enabled = Rails.env.production?
   c.env = Rails.env
-  if Rails.env.production?
-    c.use :rails, service_name: 'marketplace'
-    c.use :rack, request_queuing: true
-    c.use :delayed_job, service_name: 'marketplace-delayed-job'
-    c.use :sidekiq, service_name: 'marketplace-sidekiq'
-  end
+  c.tracing.instrument :rails, service_name: 'marketplace'
+  c.tracing.instrument :rack, request_queuing: true
+  c.tracing.instrument :delayed_job, service_name: 'marketplace-delayed-job'
+  c.tracing.instrument :sidekiq, service_name: 'marketplace-sidekiq'
+  c.tracing.instrument :faraday, service_name: 'marketplace-faraday'
+  c.tracing.instrument :http, service_name: 'marketplace-http'
+  c.tracing.instrument :aws, service_name: 'marketplace-aws'
+  c.tracing.instrument :rake, service_name: 'marketplace-rake'
```

**Environment**

* **ddtrace version:** 1.1.0
* **Ruby version:** 2.7
* **Operating system:** linux

**Comment by viraptor** [comment]
It turns out that `rack` is really `web-server`. To make the issue more explicit, I expected the naming to go the opposite way: rack knows about `GET 200`, but rails knows about `UserController#show` - same as we've seen in 0.53

**Comment by delner** [comment]
There are two parts to this:

First, you should be able to rename the http server `service` name with Rack's `web_service_name` option. You can set that to whatever you like.

Second, the Rails application is still reporting the Rails resource (controller name). However, the Rails instrumentation is setting the controller as the `trace.resource`: this value is always copied onto the root span. What has happened here is by enabling the HTTP queuing, it has added a new root span, which absorbed this resource name, whereas it previously decorated the Rack span.

This is technically correct, although behavior was slightly different in 0.x. It's allowing the resource on the Rack span to be preserved. It just so happens the Rack's default resource name is `<verb> <status>`. 

Generally speaking, each span from each part of the application should describe itself, and information (resource names) shouldn't leak from one level to another (e.g. from Rails to Rack/HTTP server). Users really should see the controller name only appear on the controller span. However, for the sake of convenience of display in the UI, we do this resource copying to aid users in identifying what traces certain spans belong to.

I'd still like to explore how this experience might be improved, and I suspect this is chiefly a UX issue. Can you share any screenshot of the UI of where you see these `GET 200` where you would hope to see the Rails controller name instead?

**Comment by viraptor** [comment]
Ok, so let me concentrate on one specific case here. I've got the `ApiChunk` resource set via:
```
Datadog::Tracing.active_span&.resource = "ApiChunk:#{transaction_name}"
```
That happens in a standard controller inheriting `ApplicationController` in a `before_action`.

What I end up with in the UI (in the rails service using the primary operation: rack.request) is:
![Screen Shot 2022-06-20 at 4 14 07 pm](https://user-images.githubusercontent.com/188063/174536589-7ca3badd-cbba-4ff2-9c64-2e1646cb778e.png)

If I explicitly switch it to `action.controller`, I can't see any resource containing `ApiChunk`.

If I go to the rack service, I see these resources by default (http_server.queue is the default operation):
![Screen Shot 2022-06-20 at 4 17 27 pm](https://user-images.githubusercontent.com/188063/174537054-56d1ffc8-607b-4a16-8417-a74c275bb3e6.png)
But again, in this view `ApiChunk:user` does not exist as a resource.

Looking at a request using the `ApiChunk` naming, this is the structure:
![Screen Shot 2022-06-20 at 4 18 53 pm](https://user-images.githubusercontent.com/188063/174537275-75befd78-da3b-4953-ad36-93ed0bba6ea7.png)

My expectations without thinking about how ddtrace works internally and ignoring what I learned here: (to be clear, I'm not ignoring you, just wanted to convey what was my expectation seeing the 1.0 APM results for the first time)
- The rack service should shows GET / POST / ... resources
- The rails service should shows the controller names / methods as resources
- When I name the active span in a controller's `before_action`, the controller name should be overridden and the name should be seen in the same view where other `controller#method` entries are

I'm happy to provide more info / screenshots if needed. Thanks!

**Comment by viraptor** [comment]
Confirmed, before/after are not included in the controller's span, but I'll raise that as a separate bug so we can concentrate on the "classification into categories is unexpected in the UI" part here.

**Comment by nudded** [comment]
@delner This change is a bit of a problem for us as well, we have a ton of dashboards built around being able to filter the correct resource on the `rack.request` metric/span. Having to redo that simply because we want to have `request_queueing` enabled seems like a bug, as without it, we'd be able to upgrade and our dashboards would continue to work.

I don't think it makes sense to have different behaviour for the resource name depending on the `request_queueing` flag.

**Comment by TomNaessens** [comment]
I'm not fully convinced this bug is caused by the `request_queueing` flag. We hit this issue when upgrading from 0.48.0 to 1.1.0 as well. Before, the `resource` on the `rack.request` consisted of `Controller#action`, while now it displays `HTTP_method HTTP_status`. Setting `requests_queuing` to `false` did not change this behaviour. Could it be that we're hitting another bug than the one described above, with similar symptoms?

Some debug traces (gathered with `DD_TRACE_DEBUG=true DD_TRACE_STARTUP_LOGS=true rails s`).

0.48.0 with request queueing (`c.use(:rack, request_queuing: true, web_service_name: "ingress-#{service_name}")`):

```
 Name: rack.request
Span ID: 4317082376594138645
Parent ID: 0
Trace ID: 1898648836762598626
Type: web
Service: unknown
Resource: Admin::FirmsController#index
Error: 0
Start: 1657781615056292096
End: 1657781615835366912
Duration: 0.7790760000352748
Allocations: 106254
Tags: [
   runtime-id => fcc017c1-c9b7-4010-af85-886e8281a8b4,
   env => sf-development,
   http.method => GET,
   http.url => /stacks/development-stack/admin/firms,
   http.base_url => http://localhost:3000,
   http.status_code => 200,
   http.response.headers.content_type => text/html; charset=utf-8,
   http.response.headers.x_request_id => 23f4f9f4-9c09-48c5-9e5c-1182af1edeff]
Metrics: [
   _dd.agent_psr => 1.0,
   system.pid => 21170.0,
   _dd.measured => 1.0,
   _sampling_priority_v1 => 1.0],
```

1.1.0 with request queuing (`c.tracing.instrument(:rack, request_queuing: true, web_service_name: "ingress-#{service_name}")`):

```
 Name: rack.request
Span ID: 3870890570777500187
Parent ID: 0
Trace ID: 4110528118742187493
Type: web
Service: unknown
Resource: GET 200
Error: 0
Start: 1657781823362450944
End: 1657781824459053056
Duration: 1.0966040000203066
Tags: [
   env => sf-development,
   component => rack,
   operation => request,
   http.method => GET,
   http.url => /stacks/development-stack/admin/firms,
   http.base_url => http://localhost:3000,
   http.status_code => 200,
   http.response.headers.content-type => text/html; charset=utf-8,
   http.response.headers.x-request-id => a18d30e1-6ae9-45ca-9f13-c0dd030369ef]
Metrics: [
   _dd.measured => 1.0]]
```

1.1.0 without request queuing (`c.tracing.instrument(:rack, request_queuing: false, web_service_name: "ingress-#{service_name}")`):

```
 Name: rack.request
Span ID: 1982575354140730814
Parent ID: 0
Trace ID: 1509403170190362713
Type: web
Service: unknown
Resource: GET 200
Error: 0
Start: 1657782036607424000
End: 1657782037505192960
Duration: 0.8977670000167564
Tags: [
   env => sf-development,
   component => rack,
   operation => request,
   http.method => GET,
   http.url => /stacks/development-stack/admin/firms,
   http.base_url => http://localhost:3000,
   http.status_code => 200,
   http.response.headers.content-type => text/html; charset=utf-8,
   http.response.headers.x-request-id => 51f6d22d-fdce-49d6-9e96-b576d29ee195]
Metrics: [
   _dd.measured => 1.0]]
```

**Comment by mikelustig** [comment]
My team has experienced this using v1.2.0 as well.
With request_queuing: false we get the  <controller>#<action> resource names that we rely on.
With request_queuing: true they display as <verb> <status> which is not as useful for us.
We'd like to be able to enable request_queuing without losing the descriptive resource names at the rack.request level.

**Comment by TonyCTHsu** [comment]
👋 `1.3.0` has released! It includes a change to overwrite rack span resource by nested app. 

This would be provide a better descriptive user experience!

**Comment by TomNaessens** [comment]
Thank you, @TonyCTHsu! We updated to 1.3.0 and this resolves the issue we have.
