### ISSUE TITLE
faraday trace headers

### ISSUE THREAD

**Issue by walterking** [DataDog/dd-trace-rb#210]
I dont use faraday, but shouldn't 
https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/faraday/middleware.rb#L59
be
            Ext::DistributedTracing::HTTP_HEADER_PARENT_ID => span.span_id
like http/patcher.rb?

**Comment by palazzem** [comment]
@walterking good catch! Yes the header is called `*_parent_id` but of course it should be related to the current `span.span_id` (since that one will be the parent of the other service root span).

Making a PR immediately! thanks!
