### ISSUE TITLE
Grape API traces do not have `request_queuing` time

### ISSUE THREAD

**Issue by pbstriker38** [DataDog/dd-trace-rb#2116]
**Current behaviour**
Grape request traces do not have `http_server.queue` operation

**Expected behaviour**
Grape requests should have the queue time

**Steps to reproduce**
Enable rack `request_queuing`

**Environment**

* **ddtrace version:** 1.1.0
* **Configuration block:**
```ruby
Datadog.configure do |c|
  c.tracing.instrument :rails
  c.tracing.instrument :grape
  c.tracing.instrument :rack, {
    web_service_name: ENV['DD_SERVICE'],
    request_queuing: true,
    headers: {
      request: %w[
        X-Forwarded-For
        X-Envoy-Attempt-Count
      ]
    }
  }
  c.tracing.log_injection = false
  c.tracing.instrument :faraday
  c.tracing.instrument :rest_client
  c.tracing.instrument :aws
  c.tracing.instrument :sidekiq, { service_name: 'sidekiq' }
  c.runtime_metrics.enabled = true
end
```
* **Ruby version:** 3.1.0
* **Operating system:** Linux
* **Relevant library versions:**
Rails 7.0.3
Grape: 1.6.2
Rack 2.2.3.1

**Comment by delner** [comment]
Thanks for the report. Rack instrumentation should enable this behavior, as you listed above. As long as the Rack instrumentation runs first, this should produce the http server span as intended.

**Comment by delner** [comment]
@karlentwistle Thanks for the detail! We'll try to reproduce this on our end.

**Comment by TonyCTHsu** [comment]
@pbstriker38 @karlentwistle , Thanks for again for the reporting. 

Could you move the request_queuing option to Rails instrumentation?  
```
Datadog.configure do |config|
  ...
  config.tracing.instrument :rails, { request_queuing: true }
  ...
end
```

**Comment by karlentwistle** [comment]
@TonyCTHsu, thanks very much! That fixed for the issue for me 👍
