### ISSUE TITLE
Clashing with google-apis-drive_v3

### ISSUE THREAD

**Issue by neilmiddleton** [DataDog/dd-trace-rb#2129]
We have a Rails 7 application (Ruby 3.1.2) which is passing specs just fine.  This application uses the gem `google-apis-drive_v3`.

However, today we tried adding `ddtrace` and specs that specifically test the Drive stuff have started failing.  For instance, the following:

```ruby
::Google::Apis::DriveV3::DriveService.new.list_files(q: query
```
now consistently raises in a spec when we're looking at the response:
```ruby
#<NoMethodError: undefined method `status' for #<Thread::Queue:0x000000011aa267d0>
```
Given this is occurring in a spec (we've not tried running it yet) it's hard to backtrace.  I'm almost 100% certain something in `ddtrace` is causing the problem here as flipping back to master lets the spec work just fine.

Without reading a bunch of gem code we're stuck, but I sense this should be a non-issue and potentially points at a bug

**Comment by delner** [comment]
Looking through [the Google code](https://github.com/googleapis/google-api-ruby-client/blob/main/google-api-client/generated/google/apis/drive_v3/service.rb#L1194), I don't see anything obvious.

There is a Ruby object [`Thread::Queue`](https://ruby-doc.org/core-3.1.0/Thread/Queue.html) which shares a name with our `Datadog::Core::Workers::Queue` module. Maybe there's some kind of reference that is ambiguously namespaced?

The error in question is expecting an object that responds to `status` but is getting a `Thread::Queue` instead. This isn't enough to go on, unfortunately. We need a backtrace/location, as how it's contextually invoked matters. Can you share this?

**Comment by delner** [comment]
Also worth mentioning: from your backtrace, it looks like tracing has been disabled. Not sure if that should be an issue, but just worth noting as a variable.

**Comment by neilmiddleton** [comment]
```
[1] pry(main)> ::HTTPClient.ancestors
=> [HTTPClient,
 HTTPClient::Util,
 ActiveSupport::Dependencies::RequireDependency,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Object,
 IceNine::CoreExt::Object,
 PP::ObjectMixin,
 ActiveSupport::Tryable,
 JSON::Ext::Generator::GeneratorMethods::Object,
 Kernel,
 BasicObject]
```
Let me try and get a full backtrace

**Comment by delner** [comment]
I don't see the Datadog tracing instrumentation in this chain (where I'd expect to see it). Was it disabled when you ran this?

**Comment by neilmiddleton** [comment]
No - this is installed vanilla as per the instructions.  We've purely installed the gem, and then added an empty `Datadog.configure` block in the initialisers

**Comment by neilmiddleton** [comment]
Actually, I've had another look and got this:
```
[Datadog::Tracing::Contrib::Httpclient::Instrumentation::InstanceMethods,
 Datadog::Tracing::Contrib::HttpAnnotationHelper,
 HTTPClient,
 Datadog::Tracing::Contrib::Httpclient::Instrumentation,
 HTTPClient::Util,
 ActiveSupport::Dependencies::RequireDependency,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Object,
 IceNine::CoreExt::Object,
 PP::ObjectMixin,
 ActiveSupport::Tryable,
 JSON::Ext::Generator::GeneratorMethods::Object,
 Kernel,
 BasicObject]
```

**Comment by delner** [comment]
@neilmiddleton I saw you closed the issue. Did you find an explanation for the issue?

**Comment by marcos-sandim** [comment]
@neilmiddleton We're facing the same issue here. Were you able to find a solution for this?

**Comment by ciscou** [comment]
Got the same issue here (with google calendar APIs instead of google driver APIs but it's the same stuff)

It's a buggy combination of HTTPClient + Webmock + ddtrace and I think it depends on the load order of those 3 libraries somehow.

Ended up "fixing" it by adding this to `config/initializers/datadog.rb`

```
if Rails.env.test? # only needed when using Webmock
  module Datadog
    module Tracing
      module Contrib
        module Httpclient
          module Instrumentation
            module InstanceMethods
              # https://github.com/DataDog/dd-trace-rb/issues/2129
              # https://github.com/nahi/httpclient/blob/4658227a46f7caa633ef8036f073bbd1f0a955a2/lib/httpclient.rb#L1024-L1027
              def annotate_span_with_response!(_span, _response)
                # no-op
              end
            end
          end
        end
      end
    end
  end
end
```
