### ISSUE TITLE
Unable to selectively disable active_support

### ISSUE THREAD

**Issue by rahul342** [DataDog/dd-trace-rb#2190]
**Current behaviour**
I have `rails` integration enabled, I am trying to disable `active_support` selectively but from my logs, I see it still emitting spans.
Full config below
I have this in my initializer to print span details in development
```ruby
  Datadog::Pipeline.before_flush do |trace|
    trace.each do |span|
      puts span.name, span.duration, span.resource, span.span_type
      puts
    end
  end
```
On my rails console
```ruby
[8] pry(main)> Datadog.configuration[:active_support][:enabled]
=> false
[9] pry(main)> cache = ActiveSupport::Cache::MemoryStore.new
=> <#ActiveSupport::Cache::MemoryStore entries=0, size=0, options={}>
[10] pry(main)> cache.read('city')
=> nil
rails.cache
0.013911000452935696
GET
cache
```

**Expected behaviour**
Shouldn't see `rails.cache` spans

**Steps to reproduce**
Noted above

**Environment**
Rails 6.0.5.1
macos 12.4 (dev env)
Haven't tried to see it in production yet.

**ddtrace version:**
0.54.2

**Configuration block (`Datadog.configure ...`):**
```ruby
require 'ddtrace'

# Count the total number of spans in a trace and
# stores that information in the 'total_spans' tag of
# the root span.
module DatadogSpanCountTracker
  def reset(options = {})
    @total_spans = 0
    super
  end

  def close_span(span)
    @total_spans += 1

    span.set_tag('total_spans', @total_spans) unless span.parent
    super
  end
end
Datadog::Context.prepend(DatadogSpanCountTracker)

# Enable Datadog APM Rails auto-instrumentation
Datadog.configure do |c|
  main_app_name = ENV['SERVICE_NAME']
  enable_tracer = true 
  c.use :active_support, enabled: false
  c.use :rails, service_name: main_app_name
  c.use :sidekiq, service_name: main_app_name
  c.use :redis
  c.use :faraday
  c.use :grpc, service_name: main_app_name if ENV['GRPC_ENABLED'].present?
  c.use :sequel
  c.use :active_model_serializers
  c.use :aws
  c.use :rack, quantize: { query: { show: :all } }
  c.runtime_metrics_enabled = true
  c.runtime_metrics statsd: DatadogHelper.statsd
  c.analytics_enabled = Rails.env.production?

  c.tracer enabled: enable_tracer,
           hostname: ENV['DD_AGENT_SERVICE_HOST'],
           port: ENV['DD_AGENT_SERVICE_PORT']
  c.tracer.partial_flush.enabled = System.service_sidekiq?
  c.diagnostics.health_metrics.enabled = true

  c.use :httprb, split_by_domain: true
  c.use :http, split_by_domain: true
  c.use :http, describes: /api\.fonoatech\.com/ do |http|
    http.service_name = 'fonoa'
    http.split_by_domain = false
  end

  c.env = Rails.env
  # Version examples: "primary", "canary", etc.
  c.tags = { 'version' => ENV['SERVICE_VERSION'] || 'primary' }
end

  Datadog::Pipeline.before_flush do |trace|
    trace.each do |span|
      puts span.name, span.duration, span.resource, span.span_type
      puts
      # Remove memory store span look ups like settings etc
      next unless span.span_type == Datadog::Ext::SQL::TYPE

      # Use old name to maintain history
      span.name = 'defaultdb.query'
    end
  end
```

* **Ruby version:** 
ruby 2.7.5

* **Operating system:**
macos 12.4

* **Relevant library versions:**
--

**Comment by marcotc** [comment]
👋, your configuration looks good. I found a bug in the disabling logic for `active_support` that we need to address.
I'll circle back here when the fix is out.

**Comment by rahul342** [comment]
🙋🏽‍♂️
Thank you!

**Comment by marcotc** [comment]
A fix has[ been merged](https://github.com/DataDog/dd-trace-rb/commit/f6813a1e36fd3fe1d420980eecca8e546fde34c8), we'll let you know when it's released. 🙇

**Comment by TonyCTHsu** [comment]
👋 @rahul342 `1.3.0` has released!

**Comment by rahul342** [comment]
@TonyCTHsu is possible to release this on 0.x?

**Comment by delner** [comment]
@rahul342 0.x is in maintenance mode, and we only provide it backports for critical security issues.

However, in this instance, we can provide a "pre-release" gem (a specially versioned gem) by applying these changes to a feature branch based on 0.x. Once built, you should be able to install it like any other gem.

Does that work for you?

Long term, to receive ongoing feature work/support, we'd encourage you to use this "pre-release gem" as a stepping stone to upgrade your application to 1.x. If that's not possible or desirable, we'd like to hear from you on how we could improve the upgrade path to enable this.

**Comment by rahul342** [comment]
Sure thing, thank you, much appreciated.

**Comment by rahul342** [comment]
Regarding 
>  If that's not possible or desirable, we'd like to hear from you on how we could improve the upgrade path to enable this
Have been working @marcotc on a support issue we have. Just to keep the variables low, we decided to stick to 0.x. I will upgrade to 1.x soon.
