### ISSUE TITLE
Profile not working due to `pkg-config` system tool is missing

### ISSUE THREAD

**Issue by fraserxu** [DataDog/dd-trace-rb#2226]
**Current behaviour**
I'm trying to follow the official guide to setup Profile for a Rails app https://docs.datadoghq.com/profiler/enabling/ruby/?tab=environmentvariables

Getting the following warning message from the log

> Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the Continuous Profiler because the `pkg-config` system tool is missing.

I've found the source code for where this message come from https://github.com/DataDog/dd-trace-rb/blob/master/ext/ddtrace_profiling_native_extension/native_extension_helpers.rb#L133

I can confirm that `pkg-config` is available.

```
dyno@dyno-517b401b-84dc-4757-ba23-48e6fe3df1ff:~$ pkg-config --version
0.29.1
```

**Expected behaviour**
Profile to work

**Environment**

* **ddtrace version:** `1.3.0` and `1.2.0`
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:** `3.1.2`
* **Operating system:** `ubuntu-20.04`
* **Relevant library versions:**

**Comment by ivoanjo** [comment]
Hello! Sorry that you ran into this, it's definitely unexpected that invoking `pkg-config` fails if it's installed as you've shown.

If possible, could you run

```bash
$ DD_PROFILING_FAIL_INSTALL_IF_MISSING_EXTENSION=true gem install ddtrace
```

and share both:

* 1️⃣ the output you get from the `gem` command
* 2️⃣ the `mkmf.log` log fail that it's expected to generate upon failing

This will help us dig further into what's happening with the `pkg-config` invocation.

**Comment by fraserxu** [comment]
Thanks for getting back to me, @ivoanjo 
 
1. Output from `gem command`

```
$ DD_PROFILING_FAIL_INSTALL_IF_MISSING_EXTENSION=true gem install ddtrace
Fetching ddtrace-1.3.0.gem
Fetching libdatadog-0.7.0.1.0-x86_64-linux.gem
Successfully installed libdatadog-0.7.0.1.0-x86_64-linux
Building native extensions. This could take a while...
ERROR:  Error installing ddtrace:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ddtrace-1.3.0/ext/ddtrace_profiling_native_extension
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/3.1.0 -r ./siteconf20220818-15-l9ubhq.rb extconf.rb

+------------------------------------------------------------------------------+
| ** Preparing to build the ddtrace profiling native extension... **           |
|                                                                              |
| If you run into any failures during this step, you can set the               |
| `DD_PROFILING_NO_EXTENSION` environment variable to `true` e.g.              |
| `$ DD_PROFILING_NO_EXTENSION=true bundle install` to skip this step.         |
|                                                                              |
| If you disable this extension, the Datadog Continuous Profiler will          |
| not be available, but all other ddtrace features will work fine!             |
|                                                                              |
| If you needed to use this, please tell us why on                             |
| <https://github.com/DataDog/dd-trace-rb/issues/new> so we can fix it :)      |
|                                                                              |
| Thanks for using ddtrace! You rock!                                          |
+------------------------------------------------------------------------------+

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
/usr/local/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:624:in `block in try_compile'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:571:in `with_werror'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:624:in `try_compile'
	from /usr/local/lib/ruby/3.1.0/mkmf.rb:688:in `try_cflags'
	from extconf.rb:73:in `add_compiler_flag'
	from extconf.rb:84:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/3.1.0/ddtrace-1.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/ddtrace-1.3.0 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/3.1.0/ddtrace-1.3.0/gem_make.out
```

2. `mkmf.log` output
 
```
LD_LIBRARY_PATH=.:/usr/local/lib "gcc -o conftest -I/usr/local/include/ruby-3.1.0/x86_64-linux -I/usr/local/include/ruby-3.1.0/ruby/backward -I/usr/local/include/ruby-3.1.0 -I. -I/usr/local/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef  -fPIC conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -L/usr/local/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby  -lm  -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

**Comment by ivoanjo** [comment]
Thanks for this information.

It looks like this environment is missing the support for building Ruby native (C) extensions.

What I'm curious about if that I'd expect the error you shared to happen regardless of the `DD_PROFILING_FAIL_INSTALL_IF_MISSING_EXTENSION` setting (e.g., even with it set to `false`).

Would you mind providing the following info?

* 1️⃣ Share the output of running `gcc -v`.
  * If `gcc` is not installed, `sudo apt install build-essential` should do the trick (since you mentioned you're on Ubuntu)

* 2️⃣ Share the output of running `gem install msgpack`
  * `msgpack` is a dependency of `ddtrace` that also uses a Ruby native extension. Let's see if it can be successfully installed, or if the issue also affects it.

* 3️⃣ Can you share how are you installing Ruby? Are you using a prebuilt docker image, or a Heroku-provided Ruby, or installing it manually, or possibly some other option?

Hopefully with this information I'll be able to debug this installation issue :)

**Comment by fraserxu** [comment]
Hi @ivoanjo , I was getting `command not found` when I try to `gcc -v`. So I followed your instruction 

1. installed it(as part of our Docker image). Now I can see `gcc` is installed

```
dyno@dyno-4b0864c9-24c7-40c8-a92f-904fffa7edc6:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
```

So I tried to check if I can install `ddtrace` gem and it seems to install fine now

```
dyno@dyno-4b0864c9-24c7-40c8-a92f-904fffa7edc6:~$ DD_PROFILING_FAIL_INSTALL_IF_MISSING_EXTENSION=true gem install ddtrace
Fetching ddtrace-1.3.0.gem
Building native extensions. This could take a while...
Successfully installed ddtrace-1.3.0
Parsing documentation for ddtrace-1.3.0
Installing ri documentation for ddtrace-1.3.0
Done installing documentation for ddtrace after 4 seconds
1 gem installed
```

2. I can also see `msgpack` can be installed fine

```
dyno@dyno-4b0864c9-24c7-40c8-a92f-904fffa7edc6:~$ gem install msgpack
Fetching msgpack-1.5.4.gem
Building native extensions. This could take a while...
Successfully installed msgpack-1.5.4
Parsing documentation for msgpack-1.5.4
Installing ri documentation for msgpack-1.5.4
Done installing documentation for msgpack after 0 seconds
1 gem installed
```

But when I check our logs, I can see the same error message about `pkg-config`

```
W, [2022-08-19T11:58:51.308452 #11]  WARN -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-1.3.0/lib/datadog/core/configuration/components.rb:359:in `startup!') Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the Continuous Profiler because the `pkg-config` system tool is missing. This issue can usually be fixed by installing: 1. the `pkg-config` package on Homebrew and Debian/Ubuntu-based Linux; 2. the `pkgconf` package on Arch and Alpine-based Linux; 3. the `pkgconf-pkg-config` package on Fedora/Red Hat-based Linux. For help solving this issue, please contact Datadog support at <https://docs.datadoghq.com/help/>. You can also check out the Continuous Profiler troubleshooting page at <https://dtdg.co/ruby-profiler-troubleshooting>.
```

I can confirm again that `pkg-config` is installed 

```
dyno@dyno-4b0864c9-24c7-40c8-a92f-904fffa7edc6:~$ pkg-config --version
0.29.1
```

3. We are using a prebuilt docker image based on the offical Ubuntu docker image

```dockerfile
# FROM BASE_UBUNTU

# Install Ruby
ARG UBUNTU_VERSION
ARG RUBY_VERSION
ARG RUBYGEMS_VERSION
COPY script/install_ruby.sh /usr/local/bin/install_ruby.sh
RUN install_ruby.sh && rm /usr/local/bin/install_ruby.sh

ENV BUNDLE_SILENCE_ROOT_WARNING 1

# Set a default place to install gems
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_APP_CONFIG $GEM_HOME
RUN mkdir -p $GEM_HOME
```

**Comment by ivoanjo** [comment]
Thanks for the info! 😄 

It's very weird that `DD_PROFILING_FAIL_INSTALL_IF_MISSING_EXTENSION=true gem install ddtrace` works but that then it fails when booting the application.

This would point to something being cached/left over OR done differently when ddtrace gets installed for your application vs when installing it via the terminal as you've shown above.

* 1️⃣ Can you try setting `ENV DD_PROFILING_FAIL_INSTALL_IF_MISSING_EXTENSION true` in your docker file, so that we can hopefully capture the error and mkmf.log file during the `bundle install` step for your application?
  * (This is expected to break the gem installation, so I recommend doing it in a staging/testing environment)

* 2️⃣ Can you check if there's some kind of gems cache while setting up your application inside the docker image? Or is the `bundler install` step always fetching and install the gems?
  * I'm thinking that there may be some old installed version being left over and even though we're changing the environment (such as installing gcc/build-essential), the gem may not be reinstalled and thus the same old error is being left behind.

**Comment by fraserxu** [comment]
Oh great point @ivoanjo It's totally that by the time we install our gems, the dependencies are not installed.

At a later stage in our Dockerfile is where I had build tools and pkg-config installed, that explains why things works in terminal. 

I can see data coming through in the dashboard now, thank you so much for your help 🙇 .

**Comment by ivoanjo** [comment]
Awesome, glad you're now happily getting data!

Feel free to reach out with any feedback or if there's anything we can help out with :)
