### ISSUE TITLE
ddtrace >1.0.0 doesn't work with Ruby 2.3 anymore

### ISSUE THREAD

**Issue by anatoli-klamer** [DataDog/dd-trace-rb#2284]
**Current behaviour**
ddtrace >1.0.0 doesn't work with Ruby 2.3 anymore

**Expected behaviour**
documentation says I can use the latest ddtrace with 2.3

**Steps to reproduce**

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version:**
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:**
* **Operating system:**
* **Relevant library versions:**

**Comment by marcotc** [comment]
Hey @anatoli-klamer, do you see any error output when using ddtrace 1.x with Ruby 2.3?

**Comment by TonyCTHsu** [comment]
👋 @anatoli-klamer , it seems like you have it resolved, I am closing it for now
