### ISSUE TITLE
delayed job tracker no longer works after upgrading to 1.4 in APM services

### ISSUE THREAD

**Issue by lubosch** [DataDog/dd-trace-rb#2285]
Logs from delayed job before upgrade (0.53) monitored all jobs and theirs duration, now all I can see is Delayed::Backend::ActiveRecord::Job resource and no jobs.

I've changed

```
  Datadog.configure do |c|
    c.use :delayed_job, analytics_enabled: nil
  end
```

to

```
  Datadog.configure do |c|
    c.tracing.instrument :delayed_job, analytics_enabled: nil
  end
```

but the logs completely changed, I can no longer see delayed_job service and I needed to downgrade

**Comment by marcotc** [comment]
👋 @lubosch, is `delayed_job` the only information you noticed was missing when you upgraded to 1.4, or other spans are also missing?

What version of the `delayed_job` gem you are using? And what [backend](https://github.com/collectiveidea/delayed_job/wiki/Backends) do you use? Do you see backend spans in your application after the upgrade (e.g. ActiveRecord database queries to fetch `delayed_job` tasks, if you are using the ActiveRecord backend)?

Also, which of the `delayed_job` spans did you notice missing: `delayed_job`, `delayed_job.enqueue`, `delayed_job.reserve_job`?

**Comment by lubosch** [comment]
Hey, I am using now [delayed_job_active_record](https://github.com/collectiveidea/delayed_job_active_record)
delayed_job (4.1.11)
Ruby 3.2
rails (7.0.4.2)
ddtrace (1.8.0)

now I use
`c.tracing.instrument :delayed_job, analytics_enabled: nil, service_name: 'delayed_job'`

I can see delayed_job service and inside is only `delayed_job.reserve_job` resource

previously I could see delayed_job-client with detailed info about the jobs

**Comment by lubosch** [comment]
nvm figured it out
