### ISSUE TITLE
Memory running away with ddtrace on heroku

### ISSUE THREAD

**Issue by seannives** [DataDog/dd-trace-rb#2343]
**Current behaviour**
I have a rails app running on Heroku, using the [Datadog Heroku Buildpack](https://github.com/DataDog/heroku-buildpack-datadog) for my Datadog Agent.  When I add a `config/initializers/datadog.rb` file which only requires 'ddtrace' and then spend even a few minutes navigating my site, memory rises drastically and continues to climb, eventually overwhelming the system.

**Steps to reproduce**
I have a single web dyno running the app with ample memory to typically run the application (2.5 GB) under normal test load.  I've tried this using a production grade server (14 GB) and the same issue occurs, eating all the available memory.
We do use sidekiq but I don't have any workers running for this test scenario.

I've got a simple `/datadog/prerun.sh` file which disables the Datadog Agent based on dyno type
```
#!/usr/bin/env bash

if [ "$DYNOTYPE" == "run" ] || [ "$DYNOTYPE" == "scheduler" ] || [ "$DYNOTYPE" == "release" ]; then
  DISABLE_DATADOG_AGENT="true"
fi
```

and a very simple config:
```
require 'ddtrace'

if Rails.env.production?
  Datadog.configure do |c|
    c.profiling.advanced.code_provenance_enabled = false 
    c.diagnostics.startup_logs.enabled = true
  end
end
```
I've tried setting code_provenance_enabled both true and false, based on info from [an older memory related issue](https://github.com/DataDog/dd-trace-rb/issues/2045), but it doesn't seem to make an impact.

That's all it takes!  Any guidance would be greatly appreciated and thanks very much for your time!

**Environment**

* **ddtrace version:**
```
+    ddtrace (1.5.0)
+      debase-ruby_core_source (>= 0.10.16, <= 0.10.17)
+      libdatadog (~> 0.7.0.1.1)
+      libddwaf (~> 1.3.0.2.0)
+      msgpack
+    debase-ruby_core_source (0.10.17)
+    libdatadog (0.7.0.1.1)
+    libdatadog (0.7.0.1.1-x86_64-linux)
+    libddwaf (1.3.0.2.0)
+      ffi (~> 1.0)
+    libddwaf (1.3.0.2.0-x86_64-darwin)
+      ffi (~> 1.0)
+    libddwaf (1.3.0.2.0-x86_64-linux)
+      ffi (~> 1.0)
```
* **Ruby version:**
`ruby 2.7.5p203`, `rails (6.0.4.7)`

* **Operating system:**
`heroku-20 (Ubuntu 20.04)`, `Datadog Agent 7.39.0-1`

* **Env vars:**
```
APPNAME:                                     sofar-test-1
DD_AGENT_MAJOR_VERSION:                      7
DD_API_KEY:                                  REDACTED
DD_APM_ENABLED:                              true
DD_DYNO_HOST:                                true
DD_ENV:                                      sofar-test-1
DD_HEROKU_DYNO:                              false
DD_LOGS_ENABLED:                             false
DD_LOGS_INJECTION:                           false
DD_LOG_LEVEL:                                ERROR
DD_RUNTIME_METRICS_ENABLED:                  true
DD_SERVICE:                                  sofar-main
DD_SITE:                                     datadoghq.eu
DD_TRACE_DEBUG:                              true
DD_TRACE_ENABLED:                            true
DD_TRACE_STARTUP_LOGS:                       true
```

And logs with a ddtrace startup log attached for good measure.  Thanks again!
[ddtrace-logs-10.31.22.txt](https://github.com/DataDog/dd-trace-rb/files/9902243/ddtrace-logs-10.31.22.txt)

**Comment by TonyCTHsu** [comment]
Hi @seannives , the environment variable `DD_TRACE_DEBUG` is typically used for debugging. It will output a lot of debugging information. 

Have you consider set it as `false`?

**Comment by TonyCTHsu** [comment]
It looks to me that datadog agent could be disabled by your `/datadog/prerun.sh`. However, the tracer is enabled on Rails'
`production` mode and could not connect to the agent. 

Could you make sure the tracer is enabled only when the agent is enabled?

**Comment by marcotc** [comment]
👋 @seannives, from the file `ddtrace-logs-10.31.22.txt` you linked, I see you have the following gems instrumented by `ddtrace`:
```
action_cable
action_mailer
action_pack
action_view
active_job
active_model_serializers
active_record
active_support
aws
concurrent_ruby
dalli
elasticsearch
excon
faraday
graphql
http
httpclient
httprb
pg
rack
rails
rake
redis
sidekiq
sinatra
```

Given your `config/initializers/datadog.rb` doesn't list them, I'm assuming you are using auto instrumentation (e.g. `gem 'ddtrace', require: 'ddtrace/auto_instrument'`) correct? This means that `Datadog.configure` was invoked for you, with all the gems you have installed that can be instrumented, which is totally fine.

In that case, unrelated to the issue reported here, your `datadog.rb` should be modified if you want to disable instrumentation in non-`Rails.env.production?` environments:
```ruby
Datadog.configure do |c|
  datadog_enabled = Rails.env.production?

  c.tracing.enabled = datadog_enabled
  c.profiling.advanced.code_provenance_enabled = false 
  c.diagnostics.startup_logs.enabled = datadog_enabled
end
```

Can you try this snippet, and disable the `datadog_enabled` variable in the environment you are testing, just so we can understand if the issue persists even if tracing is set to disabled? This is just to get a baseline, as there are a few internal components that are still running even if we set `datadog_enabled == false`.

**Comment by arapulido** [comment]
Hello! 

Can you send us your slug build logs, please? Also, what version of the buildpack are you using? 

Thanks!

**Comment by seannives** [comment]
Oh boy, I think I've found the answer.  In evaluating Datadog, we disabled our New Relic integration but it seems we didn't do so properly.  I'm nearly positive that the memory leak is coming from that so I'll close this issue.  
Thank you all for your help!  I've certainly learned more about Datadog going through this and the support you folks have shown has been tremendous.  I really appreciate it!

**Comment by ljuster** [comment]
> Oh boy, I think I've found the answer. In evaluating Datadog, we disabled our New Relic integration but it seems we didn't do so properly. I'm nearly positive that the memory leak is coming from that so I'll close this issue. Thank you all for your help! I've certainly learned more about Datadog going through this and the support you folks have shown has been tremendous. I really appreciate it!

Hi Sean! Mind providing any other information on what went wrong with the disabling of your New Relic integration? We're on a similar memory leak hunt and wonder what the interaction between DD and NewRelic are (if any)?

**Comment by seannives** [comment]
Hi @ljuster, I have some suspicions but don't want to lead you down a false path.  I'm hoping to spend some more time on this later today or tomorrow and can provide better detail then!

**Comment by seannives** [comment]
Hi @ljuster, to follow up, one of our engineers who had started our DD test integration had run into issues with DD and New Relic running simultaneously (I don't have great info beyond that at the moment, but let me know if it'd be helpful to dig up more detail there).  We removed from our puma config's `on_worker_boot` block: 
```
  require 'newrelic_rpm'
  NewRelic::Agent.manual_start
```
and made the incorrect assumption that doing so would remove New Relic from our app.  That lead to us assuming DD was causing memory issues.  Digging deeper, we found that we were including the `NewRelic::Agent::MethodTracer` in our BaseSerializer and New Relic GraphQL tracing in our APISchema.  🤦 
We ripped all that out and have been running Datadog with no memory issues on a simple test system since, with a very bare bones DD setup.  So far so good!

**Comment by ljuster** [comment]
> Hi @ljuster, to follow up, one of our engineers who had started our DD test integration had run into issues with DD and New Relic running simultaneously (I don't have great info beyond that at the moment, but let me know if it'd be helpful to dig up more detail there). We removed from our puma config's `on_worker_boot` block:
> 
> ```
>   require 'newrelic_rpm'
>   NewRelic::Agent.manual_start
> ```
> 
> and made the incorrect assumption that doing so would remove New Relic from our app. That lead to us assuming DD was causing memory issues. Digging deeper, we found that we were including the `NewRelic::Agent::MethodTracer` in our BaseSerializer and New Relic GraphQL tracing in our APISchema. 🤦 We ripped all that out and have been running Datadog with no memory issues on a simple test system since, with a very bare bones DD setup. So far so good!

Doh! More than anything, I greatly appreciate that you went out of your way to provide a follow-up. We ourselves tried a hotfix removing any trace of Datadog AND newrelic and still memory kept on a climbin'. On the plus side, it made us reorganize how we handle api and other traffic and somehow the redistribution of traffic to containers has helped slow the leak/bloat 🤷‍♀️
