### ISSUE TITLE
racecar.consume #<Class:0x00007f372ab498e0>

### ISSUE THREAD

**Issue by paulofabiano** [DataDog/dd-trace-rb#2351]
Hey guys!
My operation_name: **racecar.consume** is presenting as resource_name this **#<Class:0x00007f372ab498e0>** string. This is basically a Kafka consumer that upsert information in the database.

The **kafka.topic**, **message.kafka.partition** span tags are blank.

I researched a lot but didn´t figure out how to fix or adequately set this up.

Stack: ruby 3.1.2 and rails 7.0.4

Can anyone help me with this?

Best,
Paulo

**Comment by marcotc** [comment]
👋 @paulofabiano, could you post the code for your consumer class?

Also, what version of `racecar` and `rdkafka` is your application using?

> The kafka.topic, message.kafka.partition span tags are blank.

Are "topic" and "partition" always blank for all your kafka spans, or only for this specific consumer?

**Comment by TonyCTHsu** [comment]
👋 @paulofabiano it seems like you could have already figured out. I would close it for now.
