### ISSUE TITLE
Sinatra request path does not include script name

### ISSUE THREAD

**Issue by jamiehodge** [DataDog/dd-trace-rb#236]
The sinatra tracer currently omits the script name from the request path. This means that all subclasses of Sinatra::Base occupy the same path namespace. 

Given subclasses Foo and Bar, `/foo/:id` should not be conflated with `/bar/:id`

**Comment by palazzem** [comment]
Hey @jamiehodge! we've addressed this issue with the latest beta release (https://github.com/DataDog/dd-trace-rb/pull/283 is the reference PR). Closing this issue since it wasn't properly tracked in the PR.

Thank you very much!
