### ISSUE TITLE
No issue on error tracking for HTTP requests

### ISSUE THREAD

**Issue by gjhenrique** [DataDog/dd-trace-rb#2361]
Hi,

I'm integrating one of our Rails apps, and we would like to use the error tracking more proactively.
Receiving notifications, muting issues, etc.

I'm facing an issue that no HTTP errors from this app are currently generating an issue in the error tracking.

According to the [docs](https://docs.datadoghq.com/tracing/error_tracking/#use-span-tags-to-track-error-spans), the error tags should be in the service entry span.

The [component managing the span  rails.action_controller](https://github.com/DataDog/dd-trace-rb/blob/0bb9690f5cdbab72f2eb17bad87b0ed4a82a94fd/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb#L77) inserts the error tags is a child of the service entry span.

The [parent span](https://github.com/DataDog/dd-trace-rb/blob/0bb9690f5cdbab72f2eb17bad87b0ed4a82a94fd/lib/datadog/tracing/contrib/rack/middlewares.rb#L228) (`rack.request`) sets the status as an error, but no error tags. An issue would appear if this class set the error tags from children in the active span.

We could probably insert a rack middleware right after `TraceMiddleware` class and bubble up the error tags ourselves. Still, this is a behavior that many of your library's consumers could benefit from.

What do you think? Is there another alternative I can take a look at?

![image](https://user-images.githubusercontent.com/2664596/201053672-6779dc2c-3405-4532-8d10-930ef07804c6.png)

Thanks

\cc @skaes

**Comment by marcotc** [comment]
👋 @gjhenrique, would this be the information you are missing in the `rack.request` span https://github.com/DataDog/dd-trace-rb/pull/1124?

It looks like we addressed this issue before, but we might have a regression.
Is you issue that we don't have message, stack or type in the `rack.request` span, but do have it in the `rails.action_controller` span?

**Comment by gjhenrique** [comment]
Hi @marcotc 

That's exactly my issue.

The PR you sent would solve the issue. But it's not present anymore in the `action_pack` instrumentation today.

It looks like https://github.com/DataDog/dd-trace-rb/pull/1162/ tried to fix another problem and moved this logic to a `rescue` in a rack middleware. But having an error in the "rails land" doesn't mean it raises an exception in the rack middleware. It raises just if there is an error in another rack middleware. 

Maybe we could move this logic to outside `rescue`. Taking into account that we don't introduce a regression with the stale exceptions on `rescue_from`?
https://github.com/DataDog/dd-trace-rb/blob/b478593574063cb71ad967513faa353b75fb2b2c/lib/datadog/tracing/contrib/rails/middlewares.rb#L28-L38

**Comment by gjhenrique** [comment]
Let me take a look if some gem is swallowing my application exception before reaching the middleware.

**Comment by gjhenrique** [comment]
After some debug session, I found that an internal gem rescues the error and formats the response. In consequence, your middleware doesn't set the tags.

>  But having an error in the "rails land" doesn't mean it raises an exception in the rack middleware. Instead, it raises just if there is an error in another rack middleware.

My statement is not valid. If there is no `rescue_from` that swallows the exception to format the response, then the middleware receives the error and sets the tags. If there is an exception in a rack middleware, it's not even rescued, so I was wrong twice :disappointed: 

Shall we do something on this gem for these cases, or shall I adapt the internal gem to set the tags of this span?

**Comment by marcotc** [comment]
> I found that an internal gem rescues the error and formats the response.

If this is a proprietary gem, I advise you add the logic you linked above to it: https://github.com/DataDog/dd-trace-rb/blob/48de53ca71ea4447ee09de74f8de88974d408331/lib/datadog/tracing/contrib/rails/middlewares.rb#L27-L38

We can't automatically control for these scenarios as we don't know if your custom middleware wants to fix the Rails controller error, thus making it a true OK, or if it wants to swallow the error for convenience while still returning OK. Because the change here is in the internal middleware you mentioned, I suggest the snippet should be added around it.

If the gem you are using was public we could add support for it, but we unfortunately can't help with a private implementation.

**Comment by gjhenrique** [comment]
Hi @marcotc 

You're correct. I also don't see how this gem would help us in this case

I just wanted to check if there would be an additional idea from your side :+1: 

I'm closing this one. Thanks for the insights
