### ISSUE TITLE
FrozenError from Redis patcher #initialize

### ISSUE THREAD

**Issue by KJTsanaktsidis** [DataDog/dd-trace-rb#2369]
**Current behaviour**
When instantiating a Redis client using the current master branch of dd-trace-rb, and passing in a frozen options hash, an exception is raised:

```
FrozenError: can't modify frozen Hash: {:url=>"redis://localhost:6379", :timeout=>1.0}
    /home/runner/vendor/bundle-52/ruby/2.7.0/bundler/gems/dd-trace-rb-f387e1747a44/lib/datadog/tracing/contrib/redis/patcher.rb:24:in `initialize'
```

**Expected behaviour**
It should not raise an exception :) This was broken a few days ago in https://github.com/DataDog/dd-trace-rb/pull/2363 I believe

**Steps to reproduce**

`Redis.new({}.freeze)` should do it I think?

**How does `ddtrace` help you?**

It rocks! Really looking forward to rolling out the new native profiler implementation.

**Environment**

* **ddtrace version: Git master, ref `f387e1747a44` **
* **Configuration block doubt this is relevant?:**
* **Ruby version: 2.7.6**
* **Operating system: Ubuntu 18.04**
* **Relevant library versions: N/A**

**Comment by TonyCTHsu** [comment]
@KJTsanaktsidis 👋  I just released `1.6.1`, this would fix the frozen input. Will be working on redis 5 instrumentation next!
