### ISSUE TITLE
Add support for grape middleware tracing

### ISSUE THREAD

**Issue by Cheunn-Panaa** [DataDog/dd-trace-rb#2396]
**Is your feature request related to a problem? Please describe.**

Currently when one starts using a standalone [grape](https://github.com/ruby-grape/grape) api with datadog's trace and logging recommandations he ends up not being able to correlate middleware logs and app logs.
For example whenever you try to log incoming requests, usually done with [grape-logging](https://github.com/aserafin/grape_logging) or [grape-middleware-logger](https://github.com/ridiculous/grape-middleware-logger) no trace is generated. Thus it makes it clunky to correlate what i would call "application" logs, and "requests" logs.

**Describe the goal of the feature**

The goal would be to generate datadog's trace when the middlewares are created rather than when the "endpoint" starts
It would help people using only grape to use datadog's features effectively.

**Additional context**

There is a workaround for people using [grape-logging](https://github.com/aserafin/grape_logging) that consists of fetching datadog's trace manually and injecting it to the middleware logger. (you need to inject it in your formatter aswell, i didnt provide the code for that)
```ruby 
class App < Grape::API
  # Initialize Datadog logging and tracing
  logger Datadog.logger
  correlation_logger = Helpers::Loggers::TraceCorrelation.new
  before do
    correlation_logger.correlation = Datadog::Tracing.correlation
  end
  helpers do
    def logger
      App.logger
    end
  end

  insert_before Grape::Middleware::Error, GrapeLogging::Middleware::RequestLogger, {
    logger: App.logger,
    include: [
      correlation_logger,
      GrapeLogging::Loggers::FilterParameters.new,
      GrapeLogging::Loggers::ClientEnv.new,
      GrapeLogging::Loggers::RequestHeaders.new,
    ],
  }
  version "v1", using: :path
  mount Resources::Posts

end
```

```ruby
  module Helpers
    module Loggers
      class TraceCorrelation
        KEY = :grape_datadog_trace_logging_correlation
        def correlation
          Thread.current[KEY]
        end

        def correlation=(correlation)
          Thread.current[KEY] = correlation
        end

        def before
          self.correlation = nil
        end

        def parameters(_, _)
          { KEY => correlation }
        end

        def after
          self.correlation = nil
        end
      end
    end
  end
```

current instrumentation patches Grape::Endpoint.run [lib/datadog/tracing/contrib/grape/instrumentation.rb](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/grape/instrumentation.rb)
while in the grape gem middlewares are generated right before the run [/lib/grape/endpoint.rb
](https://github.com/ruby-grape/grape/blob/master/lib/grape/endpoint.rb#L280)

**Comment by marcotc** [comment]
👋, to get to understand the scenario more: after all is configured, what kind of object is returned by `logger` when invoked in an endpoint?
e.g. 
```ruby
post '/test' do
  puts logger.inspect
end
```

**Comment by erwanst** [comment]
We solved our problem by explicitly using the `Datadog::Tracing::Contrib::Rack::TraceMiddleware` middleware at the bottom of our middleware stack, as suggested here: https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#rack.

Apart maybe from highlighting a bit more the use of ddtrace outside a Ruby On Rails application in the documentation, there's probably nothing more to do here and the issue should probably be closed, thanks.
