### ISSUE TITLE
patch level release for resque tracing error

### ISSUE THREAD

**Issue by drewbailey** [DataDog/dd-trace-rb#240]
I was curious when the next release of ddtrace will be? A patch level release including https://github.com/DataDog/dd-trace-rb/pull/223 would be helpful and very much appreciated!

**Comment by palazzem** [comment]
Hello @drewbailey ! we're going to release a new bugfix patch today or tomorrow! I'll updated this issue when it's done!

**Comment by palazzem** [comment]
@drewbailey want to inform you that the gem is out!
* https://rubygems.org/gems/ddtrace/versions/0.9.1
* https://github.com/DataDog/dd-trace-rb/releases/tag/v0.9.1

Going to close this thread! thanks for your contribution!
