### ISSUE TITLE
Fail on manual distributed tracing for sidekiq

### ISSUE THREAD

**Issue by adrys-lab** [DataDog/dd-trace-rb#2411]
We are trying to apply distributed tracing when enqueuing a `sidekiq` job in our application.

We want to see, WHO is enqueuing the async jobs.

For that, we add a middleware, BEFORE the sidekiq push, and AFTER the sidekiq pull.

BEFORE --> Extract correlation from current span/correlation
```
    class SidekiqClientTraceCorrelator
      def call(_worker_class, job, _queue)
        correlation = Datadog::Tracing.correlation
        current_trace = {
          'x-datadog-trace-id' => correlation.trace_id,
          'x-datadog-parent-id' => correlation.span_id
        }

        job['current_trace'] = current_trace
        yield
      end
    end
```

AFTER --> inject correlation in current span
```
    class SidekiqServerTraceCorrelator
      def call(_worker_class, job, _queue)
        current_trace = job['current_trace']
        if current_trace.present?
          Datadog::Tracing.active_span.set_tag('x-datadog-trace-id', current_trace['x-datadog-trace-id'])
          Datadog::Tracing.active_span.set_tag('x-datadog-parent-id', current_trace['x-datadog-parent-id'])
        end

        yield
      end
    end
```

But this is causing no effect, we think there is an error on trying to manually inject trace_id and parent_id,
but we can not find doumentation about it.

Maybe the way of injecting `trace_id` and `parent_id` is not using `set_tag` ?

dd-trace version `1.4.1`

**Comment by adrys-lab** [comment]
i think its

```
job['current_trace'] = Datadog::Tracing.active_trace.to_digest
```

and


```
if job['current_trace']
  Datadog::Tracing.continue_trace!(job['current_trace']) do
  yield
end
```

**Comment by TonyCTHsu** [comment]
👋 @adrys-lab , have you tried the implementation @marcotc suggested? 
https://github.com/DataDog/dd-trace-rb/issues/2295#issuecomment-1261450099

**Comment by marcotc** [comment]
> 👋 @adrys-lab , have you tried the implementation @marcotc suggested?
https://github.com/DataDog/dd-trace-rb/issues/2295#issuecomment-1261450099

@adrys-lab, I second @TonyCTHsu's comments and, if it works for your case, we'll document it as an official way to propagate, and work on streamlining the API in the future as well.

**Comment by adrys-lab** [comment]
i have been adding more logs, to see what is the path and outcome, and i came up with this:

**CLIENT**
```
require 'datadog/tracing/distributed/metadata/datadog'

module Sidekiq
  module Middleware
    class SidekiqClientTraceCorrelator
      def call(_worker_class, job, _queue, _redis_pool)
        active_trace = {}
        Datadog::Tracing::Distributed::Metadata::Datadog.inject!(Datadog::Tracing.active_trace&.to_digest, active_trace)

        # Set the 'active_trace' as Metadata of the current JOB
        job['current_trace'] = active_trace

        WebLogger.info(
          event: 'sidekiq_middleware',
          message: 'client - proceed',
          args: { active_trace: active_trace }
        )

        yield
      end
    end
  end
end
```

**SERVER**
```
require 'datadog/tracing/distributed/metadata/datadog'

module Sidekiq
  module Middleware
    class SidekiqServerTraceCorrelator
      def call(_worker_class, job, _queue)
        # Set the 'active_trace' from the 'who' pushed this 'sidekiq' job to continue the trace
        if job['current_trace'].present?
          WebLogger.info(
            event: 'sidekiq_middleware',
            message: 'server - current_trace',
            args: { current_trace: job['current_trace'] }
          )
          Datadog::Tracing.continue_trace!(
            Datadog::Tracing::Distributed::Metadata::Datadog.extract(job['current_trace'])
          ) do
            WebLogger.info(
              event: 'sidekiq_middleware',
              message: 'server - continue_trace!',
              args: { current_trace: job['current_trace'] }
            )

            yield
          end
        else
          WebLogger.info(
            event: 'sidekiq_middleware',
            message: 'server - ELSE proceed'
          )
          yield
        end
      end
    end
  end
end
```

Notice that in the server now i do `Datadog::Tracing.continue_trace!() do yield` (but it does not work neither)

i can confirm, the path is the correct one, look at the output of the logs.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/35842560/203768724-21ce0da3-000d-4863-9f5d-19084f5b7267.png">
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/35842560/203771032-de653b4e-59c1-45b7-b571-258b496f9061.png">

**Comment by TonyCTHsu** [comment]
@adrys-lab , what is your sidekiq version? We are currently working to support the later version of sidekiq.

**Comment by adrys-lab** [comment]
it is not the last one.

```
sidekiq (6.4.2)
```

**Comment by adrys-lab** [comment]
i don't really get it as i see based on LOGS that all data is pushed using same method than @marcotc suggested...

**Comment by TonyCTHsu** [comment]
@adrys-lab Thanks for providing the details. Distributed tracing for background jobs is definitely something we want to support. I will bring back to our team and put it on our road map to officially support it.

**Comment by jenakan** [comment]
@adrys-lab I had success with your implementation. It might have to do with the order of the middlewares. [Here's](https://gist.github.com/jenakan/759a4ec8c6f8649ffc9b799b831c4346) my gist.

**Comment by adrys-lab** [comment]
it worked well @jenakan thanks a lot !!

**Comment by sled** [comment]
fyi, here's an updated middleware for the new dd-trace API: https://github.com/DataDog/dd-trace-rb/issues/2295#issuecomment-1468077941
