### ISSUE TITLE
undefined local variable or method `payload`

### ISSUE THREAD

**Issue by billeisenhauer** [DataDog/dd-trace-rb#243]
https://github.com/DataDog/dd-trace-rb/blob/587f9a8c440ba688a7557c52e21cab1a4572e083/lib/ddtrace/contrib/rails/core_extensions.rb#L229

One of our specs blew up and so I'm wondering if `payload` should really be `raw_payload` in this case and in other cases in this file.  It seems like this may have been copied from a method where `payload` was defined.

Here is a partial stacktrace with some details elided:

```
       expected RuntimeError with message matching <elided details here> cache value: id=, name/, got #<NameError: undefined local variable or method `payload' for #<ActiveSupport::Cache::MemoryStore:0x007fbd3f009638>> with backtrace:
         # /Users/beisenhauer/.rvm/gems/ruby-2.3.1@minx/gems/ddtrace-0.9.1/lib/ddtrace/contrib/rails/core_extensions.rb:229:in `rescue in fetch'
         # /Users/beisenhauer/.rvm/gems/ruby-2.3.1@minx/gems/ddtrace-0.9.1/lib/ddtrace/contrib/rails/core_extensions.rb:224:in `fetch'
```

/cc @palazzem

**Comment by palazzem** [comment]
Thanks for spotting this @billeisenhauer ... going to fix that immediately!

**Comment by palazzem** [comment]
This should fix the problem https://github.com/DataDog/dd-trace-rb/pull/244 ; I've also added a test for the specific case. Going to merge and release a `0.9.2`.

**Comment by palazzem** [comment]
@billeisenhauer bug solved and PR released with the new version: https://github.com/DataDog/dd-trace-rb/releases/tag/v0.9.2 ... can you confirm the problem has been solved? thanks a lot!

**Comment by billeisenhauer** [comment]
@palazzem Problem looks to be solved on our end.  Thanks for the quick turnaround!

**Comment by palazzem** [comment]
Nice! you're welcome @billeisenhauer ! feel free to reach us whenever you have a feedback! Thanks again!
