### ISSUE TITLE
Testing appraisal `install_appraisal_gemfiles` broken for Ruby 2.3 docker image

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/dd-trace-rb#2444]
**Current behaviour**

While working on releasing `ddtrace` 1.7.0 (https://github.com/DataDog/dd-trace-rb/pull/2442) I observed bundler failing in some Ruby 2.3 appraisal groups because they required bundler 1.x and we upgraded the Ruby 2.3 image to use bundler 2.x.

I needed to hack the `install_appraisal_gemfiles` step on 2.3 to work around this and use the older bundler:

```diff
@@ -24,13 +12,13 @@ task :install_appraisal_gemfiles do |_task, args|
   versions.each do |version|
     sh [
          "docker-compose run -e APPRAISAL_GROUP --no-deps --rm tracer-#{version} /bin/bash -c ",
-         "'rm -f Gemfile.lock && gem update bundler && bundle install && ",
+         "'rm -f Gemfile.lock && gem update bundler && bundle _1.17.3_ install && ",
          # Appraisal runs `bundle check || bundle install` on `appraisal install`. This skips `bundle install` \
          # if the `Gemfile.lock` is satisfied by installed gems, even if there are `Gemfile` changes to be processed. \
          # Adding the `--without` option forces Appraisal to skip `bundle check` and always run `bundle install`. \
          # `--without` has a small side-effect of getting saving in the local bundler env, but we do not persist \
          # these changes outside of the current container. \
-         "bundle exec appraisal install --without force-appraisal-to-always-run-bundle-install'"
+         "bundle _1.17.3_ exec appraisal install --without force-appraisal-to-always-run-bundle-install'"
        ].join
   end
 end
```

**Expected behaviour**

Updating appraisals for Ruby 2.3 should not fail (which means it should probably use bundler 1.x automatically).

**Steps to reproduce**

Run `bundle exec rake install_apraisal_gemfiles`.

**How does `ddtrace` help you?**

(N/A)

**Environment**

(N/A)

**Comment by TonyCTHsu** [comment]
Actually, we should remove `gem update bundler` in those tasks, since the `bundler` from the images are already been updated to the adequate version.

For ruby 2.1 and 2.2, `gem update bundler` would not be successful.
For ruby 2.3, even we could update bundler, we should not. Because old version of Rails depends on old bundler

**Comment by marcotc** [comment]
Agreed that `gem update bundler` should not be run in that rake task.
