### ISSUE TITLE
How to create sampling rule to not sample delayed_jobs?

### ISSUE THREAD

**Issue by stevenroach14** [DataDog/dd-trace-rb#2484]
Hello! I have a Rails application that is using the dd-trace-rb library. Previously, I was using version 0.54.2 but I recently upgraded to 1.6. After upgrading, I noticed in the APM service catalog that the delayed job service went away and I started seeing these traces under the main application with the operation set as delayed_job. It seems like this is explained in https://github.com/DataDog/dd-trace-rb/issues/2303 and I can understand the argument that the delayed_job is not actually an external service.

However, I would now like to turn off tracing for the delayed_job but since the service is now part of our main application, I don’t know how to write a sampling rule to accomplish this and I haven’t found any similar examples in the DataDog documentation. How can I disable tracing for just the delayed jobs and not the rest of my application? Do the sampling rules allow for an operation attribute? Alternatively, I wouldn’t mind making the delayed job be its own service if there is an easy way to accomplish that. Cheers!

**Environment**

* **ddtrace version:** 1.6
* **Configuration block (`Datadog.configure ...`):**
```
Datadog.configure do |c|
  c.service = 'my_app'
  c.tracing.sampling.default_rate = 1.0
  c.tracing.partial_flush.enabled = true

  # Enable manual instrumentation
  c.tracing.instrument(:rails)
  c.tracing.instrument(:aws)
  c.tracing.instrument(:delayed_job)
   ...
```
* **Ruby version:** 2.7.1
* **Relevant library versions:** Rails 6

**Comment by marcotc** [comment]
👋 @stevenroach14, if I understand your problem correctly, removing the `:delayed_job` integration should work, like so:
```diff
Datadog.configure do |c|
  c.service = 'my_app'
  c.tracing.sampling.default_rate = 1.0
  c.tracing.partial_flush.enabled = true

  # Enable manual instrumentation
  c.tracing.instrument(:rails)
  c.tracing.instrument(:aws)
- c.tracing.instrument(:delayed_job)
  ...
```

Let me know if the issue is actually different, or if this does not yield the desired traces for your use case.

**Comment by stevenroach14** [comment]
I can give this a try but my previous understanding was that `c.tracing.instrument(:delayed_job)` just adds some delayed job specific instrumentation (https://github.com/DataDog/dd-trace-rb/blob/a335fb1f1e08eac1b84bb149d89e1b349b9887f7/lib/datadog/tracing/contrib/delayed_job/plugin.rb) but that without this line, general tracing will still be enabled.

**Comment by stevenroach14** [comment]
I tested removing `c.tracing.instrument(:delayed_job)` and I am still seeing traces from the delayed jobs so I think the removing that line removes some delayed job specific instrumentation but doesn't actually disable tracing in the delayed jobs.

**Comment by stevenroach14** [comment]
@marcotc I think my original questions are still relevant here. It seems like it should be relatively trivial to disable tracing for a component of the application which can be easily distinguished on an attribute (in this case, the operation attribute). Alternatively, I could use the by-service sampling rate configuration if there is a way in dd-trace-rb 1.x to specify delayed jobs as their own service. 

 Can you please advise? Thank you!

**Comment by marcotc** [comment]
👋  @stevenroach14,
#### 1
Are your `delayed_job` jobs run in a separate Ruby process from your main application?
If so, can completely disable `ddtrace` at that process' initialization step, for example:
```ruby
unless ENV['DELAYED_JOB_WORKER'] == 'true'
  Datadog.configure do |c|
    # ... 
  end
end
```
This will prevent any spans from being generated in that Ruby process.

#### 2
If `delayed_job` jobs run in the same process as your main application, then you can assign a service name to `c.tracing.instrument(:delayed_job)` and filter that out in sampling:
```ruby
  c.tracing.instrument(:delayed_job, service_name: 'delayed_job')
```
Then set up a sampling rule to drop these traces, by setting the environment variable `DD_TRACE_SAMPLING_RULES=[{"service": "delayed_job", "sample_rate": 0.0}]`. More information about [Sampling Rules here](https://docs.datadoghq.com/tracing/trace_pipeline/ingestion_mechanisms/?tab=ruby#in-tracing-libraries-user-defined-rules).
This will only work if the `delayed_job` span is the top-most span, which is probably the case, given it's an async job.

I recommend approach `1` if applicable, given it will completely remove the need for your to be concerned with how `ddtrace` interacts with your `delayed_job`s, as it simply will not interact if it was never enabled.

**Comment by stevenroach14** [comment]
@marcotc Including the service_name argument in the instrument method for the delayed job was exactly what I was looking for. Cheers!
