### ISSUE TITLE
Add the ability to define a custom error handler for Net/HTTP

### ISSUE THREAD

**Issue by caramcc** [DataDog/dd-trace-rb#2492]
**Is your feature request related to a problem? Please describe.**
The applications I'm instrumenting make a lot of API calls to external services using Net/HTTP. Since the services are user-configured, we expect a relatively large volume of these requests to fail with 4xx or 5xx status codes. As a result, we end up ingesting a lot of traces due to `ingestion_reason:error` that we don't consider to be an error and don't otherwise care about.

**Describe the goal of the feature**
Having the ability to configure a custom `error_handler` for the Net/HTTP service similar to the one configured for Faraday would allow us to configure which responses we want to treat as an error. The status quo is [using the hard-coded `response code in 400...599`](https://github.com/DataDog/dd-trace-rb/blob/e5bb0eb9892ac9474f0887d703052eb55d3b1e6b/lib/datadog/tracing/contrib/http/instrumentation.rb#L98-L101) configuration for errors.

**Describe alternatives you've considered**
Even being able to configure which net/http response codes we want to treat as an error would be a big improvement over the status quo.

**Comment by delner** [comment]
Thanks for sharing!

Although I like the idea of custom handlers, there are some challenges with designing a feature and committing to supporting it as a public API. If our hope is to support Ractors in the future, custom blocks like this won't work (they will raise isolation errors). I think there are ways around this, but we just need to be a bit careful.

In the interim, I think configuring error code ranges should be a good stop gap measure, and generally more easy to control from a deployment perspective. We already do this for the web frameworks (like Rails), so there's a well worn path for implementation and support there. This is the fastest way to get some improvement.

 We don't have capacity right now for taking this on in the short term, but we will certainly track it on our own TODO list. If anyone from the community would like to make a contribution to add this, we'd be happy to guide & support that effort as well!

**Comment by caramcc** [comment]
Thank you for the advice! Totally makes sense about Ractor support.

I added a PR to make the HTTP status codes configurable, since that would be a huge help for us as a stop-gap measure.

**Comment by TonyCTHsu** [comment]
👋 @caramcc  , `1.9.0` has been released, give it a try!

**Comment by caramcc** [comment]
Awesome, thanks for the update!
