### ISSUE TITLE
Feature Request: ActionMailer instrumentation

### ISSUE THREAD

**Issue by webandtech** [DataDog/dd-trace-rb#250]
Would be interested in seeing metrics such as emails sent, errors, etc

**Comment by webandtech** [comment]
I was able to get something like this going using an `around_action` in my base mailer. Could use some additional improvement then included in the base Rails instrumentation.

```
class ApplicationMailer < ActionMailer::Base
  around_action :datadog_trace

  def datadog_trace
    Datadog.tracer.trace('actionmailer.email') do |span|
      span.service = 'actionmailer'
      span.resource = "#{self.class.name}##{action_name}"
      yield
    end
  end
end
```

**Comment by delner** [comment]
Great suggestion, @webandtech ! This is on our radar; we'll take a deeper dive into it in the coming weeks. I'll keep you posted!

**Comment by dasch** [comment]
Any update on this?

**Comment by delner** [comment]
This is on our backlog, but we have particular interest in instrumenting more Rails packages out-of-the-box, so I anticipate this one will be handled sooner rather than later.

**Comment by ivoanjo** [comment]
This was added in #1280 but we totally forgot to close the issue, oops! I'm going to go ahead and close this, please do reach out to us if we can help in any way :)
