### ISSUE TITLE
`NoMethodError: undefined method 'ntuples' for` with `PG#exec` when used with a block parameter

### ISSUE THREAD

**Issue by beauraF** [DataDog/dd-trace-rb#2505]
**Current behaviour**

When using `PG#exec` with a block parameters, `ddtrace` PG auto instrumentation is crashing with:

```
NoMethodError: undefined method `ntuples' for 1:Integer

              span.set_tag(Contrib::Ext::DB::TAG_ROW_COUNT, result.ntuples)
                                                                  ^^^^^^^^
from /Users/beauraf/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/ddtrace-1.7.0/lib/datadog/tracing/contrib/pg/instrumentation.rb:163:in `annotate_span_with_result!'
```

**Expected behaviour**

No crash. Auto instrumentation working well, and reporting metrics.

**Steps to reproduce**

```ruby
PG::Connection.open(host: 'localhost', port: '5432', dbname: 'dbname').exec("SELECT count(*) FROM pg_stat_activity where state not like \'%%idle%%\';") { 1 }
```

**Analysis**

Issue happen here https://github.dev/DataDog/dd-trace-rb/blob/ac49c557df3fbdc372b64176c65d9083a6132122/lib/datadog/tracing/contrib/pg/instrumentation.rb#L104, because it expect that `result` is a `PG::Result` but, when used with a block parameters `PG#exec` return the result of the block.

**Environment**

* **ddtrace version:** 1.7.0
* **Ruby version:** 3.1.3
* **pg version:** 1.4.5

**Comment by delner** [comment]
Interesting. Didn't realize `exec` takes blocks? Why would an application pass a block to this function?

I suppose the simplest fix is if the result isn't a `PG::Result`, then don't tag the row count. Alternatively, we can capture the block, wrap it, and use the wrapper to intercept the `result` arg given to the block. The latter is probably better than the prior.

**Comment by beauraF** [comment]
>  Why would an application pass a block to this function?

Prior `pg` 1.1 `PG::Result` weren't garbage collected. You had to call `#clear` on it. Since 1.1 memory informations are pass to `GC`. But (and I'm not 100% sure of what I'm saying here), it's still better to call `#clear` on it.

By passing a block, your block will be executed with the result as context, and at the end of the block `pg` will take care of free the memory used by the `PG::Result`.

**Comment by TonyCTHsu** [comment]
👋 @beauraF , `1.9.0` has been released with the fix, give it a try!
