### ISSUE TITLE
Custom exception controller overriding root trace resource

### ISSUE THREAD

**Issue by timonv** [DataDog/dd-trace-rb#2611]
**Current behaviour**
In Rails it's possible to configure a custom exception controller using `exceptions_app` in the application configuration. When an exception is raised elsewhere, the final handler is this Rack application. Often and in our case this is a Rails controller.

In datadog the root resource name of the trace is set to the exception controller. Like this:
![image](https://user-images.githubusercontent.com/49373/218048267-9faa56a0-c941-4f55-bcda-f85ad448fa8c.png)

**Expected behaviour**
This behaviour is problematic, as it obfuscates monitors and SLOs with the wrong resource. I'd expect the original controller to be the resource instead.

![image](https://user-images.githubusercontent.com/49373/218048591-ae944bd7-c803-4947-b511-be27eda6cd00.png)

In this case that would be `StatusController#error`.

Unfortunately not with any success.

**Steps to reproduce**
1. Create an ExceptionController like:

```
class ExceptionController < ActionController::Base
...
def server_error
  render text: 'Woopsie'
end
```

2. Configure Rails to use it
```
# In application.rb
config.exceptions_app = self.routes

# In routes
get '/500', to: 'exception#server_error'

```

3. Trigger an exception elsewhere

**How does `ddtrace` help you?**
I'd expect the exception_controller config in the rails instrumentation (frankly also the autodetection) to pick this up. But it doesn't seem to work. It does set `exception_controller?` in the payload in the rack instrumentation, but I'm not sure if that's used.

I also tried some hacking around in the custom error controller like:

```
        trace = Datadog::Tracing.active_trace
        original_resource = trace.instance_variable_get('@spans').find { |s| s.resource =~ /Controller/ }&.resource
        # Does set it but doesn't seem to affect dd
        trace.resource = original_resource

        # Set it on the root span directly
        # Also doesn't seem to work
        trace.send(:root_span).resource = original_resource
```

**Environment**

* **ddtrace version:**  1.9.0
* **Configuration block (`Datadog.configure ...`):**
```
if defined?(Datadog)
  Datadog.configure do |c|
    # If we want to trace a service separately, treat it as a separate root
    # span with it's own errors we name it different from the deployed service.
    # Otherwise inherit from deployed. Additionally, if it's an interface to
    # a remote service (database, cache, api), useful to have a separate service name
    # *unless* this puts the error on the wrong root span
    #
    # This will activate auto-instrumentation for Rails
    c.tracing.instrument :rails, service_name: ENV["DD_SERVICE"], middleware_names: true
    # Graphql instrumentation is on the schema
    c.tracing.instrument :sidekiq, tag_args: true, service_name: ENV["DD_SERVICE"]
    c.tracing.instrument :http, service_name: ENV["DD_SERVICE"]
    c.tracing.instrument :faraday, service_name: ENV["DD_SERVICE"]
    c.tracing.instrument :ethon, service_name: ENV["DD_SERVICE"]
    c.tracing.instrument :httpclient, service_name: ENV["DD_SERVICE"]
    c.tracing.instrument :grape, service_name: ENV["DD_SERVICE"]
    c.tracing.instrument :rest_client, service_name: ENV["DD_SERVICE"]


    # Own service names
    # Active record also traces the query and pg is a factor more on AR
    # This reduces the ingested spans by 60%, enabling us to ingest more
    # meaningful spans instead
    c.tracing.instrument :pg, enabled: false
    c.tracing.instrument :active_record, service_name: ENV["DD_SERVICE"]
    # c.tracing.instrument :redis

    c.profiling.advanced.force_enable_new_profiler = true

    # c.tracing.instrument :graphql, schemas: [GraphqlApi::AppSchema, GraphqlApi::AuthenticationSchema, GraphqlApi::PublicSchema], service: 'graphql'


    if defined?(Datadog::Statsd)
      c.runtime_metrics.enabled = true
    end
  end

end
```
* **Ruby version:** 2.7.4
* **Operating system:** Linux container
* **Relevant library versions:**

````
rails 6.1.5
```

**Comment by TonyCTHsu** [comment]
👋 @timonv , Thanks for sharing this. I think this is similar with this [issue](https://github.com/DataDog/dd-trace-rb/issues/2567). I have provided a [patch](https://github.com/DataDog/dd-trace-rb/issues/2567#issuecomment-1401641827) to mitigate this, perhaps you could give it a try and give me some feedback about this approach.

**Comment by timonv** [comment]
@TonyCTHsu The approach put us in the right direction. However, that would keep the initial service the error occured in, while in most case we want the resource name to be that of the root service (i.e. rails controller/action, possibly graphql as well but can also be handled on the service level). 

```ruby
   trace.resource = span.resource unless exception_controller?(payload)
```

This actually seems to work, we're running it in production right now with zero noise :tada:
