### ISSUE TITLE
Errors added in the current span do not appear in Error Tracking

### ISSUE THREAD

**Issue by LeandroSNunes** [DataDog/dd-trace-rb#2616]
**Current behaviour**
Errors added from the current span do not appear in the Error Tracking of the Datadog application
The errors are sent from SpanOperation#set_error

```ruby
 # In controller
  def get_percentage
    raise StandardError.new('My Error')
  rescue => e
    ErrorTracker.notify(e, foo: 'bar')
  end
```
```ruby
# The notify method
    def self.notify(error, content = {})
      resource_name = Datadog::Tracing.active_trace&.resource || DEFAULT_RESOURCE_NAME
      span_name = Datadog::Tracing.active_span&.name || DEFAULT_ERROR_NAME
      span = Datadog::Tracing.trace(span_name, service: Datadog.configuration.service, resource: resource_name)
      span.set_error(error)
      span.set_tags(content)
      span.finish

      nil
    end
```
The error appears in APM Trace perfectly
![Screenshot from 2023-02-13 19-58-25](https://user-images.githubusercontent.com/656458/218594398-912d528e-d2b4-47c0-9f99-51db9aca6a52.png)

![Screenshot from 2023-02-13 19-59-05](https://user-images.githubusercontent.com/656458/218594521-335e156a-03ed-4083-a22e-cb3f627a2cf6.png)

The SpanOperation object is instantiated correctly with the meta attributes as per documentation https://docs.datadoghq.com/tracing/trace_explorer/trace_view/?tab=spantags#more-information

```shell
span.to_hash[:meta]                                                                                                                                               
{"env"=>"development", "error.type"=>"StandardError", "error.message"=>"My Error", "error.stack"=>"/home/engenharia/Dev/ucc/app/controllers/setup_guide_groups_controller.r
b:20:in `get_percentage': My Error (StandardError)\n\tfrom /home/engenharia/.rvm/gems/ruby-2.7.6/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb
:6:in `send_action'\n\tfrom /home/engenharia/.rvm/gems/ruby-2.7.6/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:215:in `process_action'\n\tfrom /home/engenharia/.
```

**Expected behaviour**
I would like some errors handled in my application to also appear in Error Tracking

**Environment**

* **ddtrace version:*0.14.0*
* **Configuration block (`Datadog.configure ...`):*
```ruby
Datadog.configure do |c|
  c.agent.host = ENV['DD_AGENT_IP'] || nil
  c.service = 'BLA'
  c.env = ENV['RAILS_ENV']

  c.tracing.enabled = ENV["DD_ENABLED"]
  c.tracing.partial_flush.enabled = true
end
```

* **Ruby version:*2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]*

**Comment by LeandroSNunes** [comment]
resolved passing a custom name to the service :-P

```ruby
span = Datadog::Tracing.trace(span_name, service: 'custom', resource: resource_name)
```

**Comment by ayemos** [comment]
For those encountering a similar issue and seeking a solution, refer to Datadog's documentation on error tracking:

https://docs.datadoghq.com/tracing/error_tracking/

> The Datadog tracers collect errors through integrations and the manual instrumentation of your backend services’ source code. Error spans within a trace are processed by Error Tracking if the error is located in a service entry span (the uppermost service span). This span must also contain the error.stack, error.message, and error.type [span tags](https://docs.datadoghq.com/tracing/visualization/trace/?tab=spantags#more-information) to be tracked.

If a span contains the name of a descendant span and service, Error Tracking may not process it. However, by altering the service name, you can effectively convert the span into a service entry span. This is achieved by making it unrelated to the upstream trace, allowing it to be captured and displayed in Error Tracking.

**Comment by acsbendi** [comment]
@ayemos Thanks for explaining this, I've never seen a correct explanation anywhere else. What would you suggest if you don't want the `service` tags of errors to differ from those of other logs from the same service? In other words, is there another way of bringing traces to the top level?

Also, when it comes to log-based error tracking, that does not seem to work either, I'm guessing for the same reason (the trace is not top-level).
