### ISSUE TITLE
Support for opensearch gem

### ISSUE THREAD

**Issue by segiddins** [DataDog/dd-trace-rb#2628]
**Is your feature request related to a problem? Please describe.**
No
**Describe the goal of the feature**
DataDog can trace the `opensearch` gem out of the box

**Describe alternatives you've considered**
None

**Additional context**

https://github.com/opensearch-project/opensearch-ruby is a fork of elasticsearch-ruby. ddtrace has a tracer built in for elasticsearch, but it is hardcoded to the elasticsearch constants, and therefore does not support the opensearch gem.

**Comment by TonyCTHsu** [comment]
👋 @segiddins , I think it make sense to have `opensearch` being traced. Currently our team has other prioritized subjects but we are opened to community contribution for this 😄
