### ISSUE TITLE
[Sinatra][Rack] Connect Logs and Traces

### ISSUE THREAD

**Issue by nvh0412** [DataDog/dd-trace-rb#2666]
**Is your feature request related to a problem? Please describe.**
Given a Sinatra web app, we turned on the AMP to get app traces and push logs to our DD successfully, the problem is when we tried to connect our logs and traces, here is the context:

By default, Sinatra app is a rack application and rack came longs with its [Rack::CommonLogger](https://github.com/rack/rack/blob/main/lib/rack/common_logger.rb), when we configure a Logger for this CommonLogger, we got these logs:

![Screenshot 2023-03-06 at 9 36 13 pm](https://user-images.githubusercontent.com/1973623/223086436-5aef161e-627e-4159-9fee-3092e4d72f0e.png)

How did we configure a logger for this Rack::CommonLogger middleware?

![Screenshot 2023-03-06 at 9 37 46 pm](https://user-images.githubusercontent.com/1973623/223086891-3675a0a3-897f-42d7-acb9-5cd9e91e73be.png)

In general, it's working and nothing wrong with it, but the problem appeared when we want to connect these logs to traces. To investigate some performance issues, we all know that we don't have some users/requests/useragent... inside traces, but in our logs, so link traces and logs action is a must-have if we want to trace the problem.

The thing is this Rack::CommonLogger middleware is added out of the DD rack/sinatra middleware scope, it makes  `Datadog::Tracing.correlation` to returns nil.

**Describe the goal of the feature**
At the moment, I only can think about doing a monkey patch to patch this block

https://github.com/DataDog/dd-trace-rb/blob/3514f9f30c7b6159e645e62e30802674837ba117/lib/datadog/tracing/contrib/sinatra/patcher.rb#L31-L34

Then I'm able to push my Editted CommonLogger middleware to before/after these Datadog middleware, so I will have the `correlation` data to link the log and trace together.

So would it be possible for you to help me figure out a proper way to link this CommonLogger's log and trace together without doing a monkey patch like this? 

**Describe alternatives you've considered**
- Turn off that CommonLogger by using [Sinatra:: QuietLogger](https://github.com/sinatra/sinatra/blob/main/sinatra-contrib/lib/sinatra/quiet_logger.rb#L36), and then using another logger to wrap up the app and log the request info. But this is a hacky way to solve this problem because I have to use a `quiet_logger_prefixes` config to filter out all of the logs come from Sinatra and Rack by default. Then re-implementing them with another logger with a custom middleware to ensure that middleware is covered by DD middleware.

**Additional context**
N/A

**How does `ddtrace` help you?**
Connect Logs and Traces

**Comment by marcotc** [comment]
Hey @nvh0412, thank you for the report.

A middleware order issue seems like the correct assessment here.

Could you show us your Rack middleware stack after your application is fully initialized? I know the output is long, so feel free to trim it.

For our Sinatra integration, we try to make sure to insert our middleware at the very top (first to run) of the stack: https://github.com/DataDog/dd-trace-rb/blob/0810273c21bff7ea04511db4b2ef573a82275d73/lib/datadog/tracing/contrib/sinatra/framework.rb#LL34C27-L34C27
If you application does not end up with the Datadog middleware running before "Rack::CommonLogger", I can see this being a problem.

**Comment by nvh0412** [comment]
Hello @marcotc 

thank you for following up on this issue. Here is what I have

## Middlewares
![Screenshot 2023-03-08 at 12 51 02 pm](https://user-images.githubusercontent.com/1973623/223599599-221cc0d7-ffab-4e30-b24d-abff7d22498b.png)

=> Rack::CommonLogger is being put at the end of the order.

## When that Rack::CommonLogger was called
![Screenshot 2023-03-08 at 12 56 45 pm](https://user-images.githubusercontent.com/1973623/223599693-bb10920c-3bbc-45da-bd42-806b00416c7a.png)

## Here is what I've got in my stdout
![Screenshot 2023-03-08 at 12 57 17 pm](https://user-images.githubusercontent.com/1973623/223599823-4a6f5720-4107-4b4d-a73f-12f6edac6f51.png)

## Datadog configuration

```ruby
  Datadog.configure do |c|
    c.tracing.instrument :semantic_logger
    c.tracing.instrument :sinatra
    c.diagnostics.debug = true
  end

```

**Comment by mwoskowicz** [comment]
@nvh0412 Did you fix the issue? We're having the same problem :)

**Comment by ivoanjo** [comment]
@mwoskowicz feel free to/please do open either a support ticket or an issue in dd-trace-rb if you'd like us to look into any issues you're having :)
