### ISSUE TITLE
Duplicate and contradictory sections in GettingStarted.md

### ISSUE THREAD

**Issue by coneill-enhance** [DataDog/dd-trace-rb#2670]
I'd recommend separating these sections into their own files, being in one file huge file makes it much easier for these issues to occur unnoticed.

Looking at the code it looks like `query:` isn't an option supported under `:quantize`. See: https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/rake/instrumentation.rb#L80

I'll open a PR for this.

https://github.com/DataDog/dd-trace-rb/blob/5dfea5e43e990189802641b960bb6f95e81b5b9d/docs/GettingStarted.md?plain=1#L1527-L1623

https://github.com/DataDog/dd-trace-rb/blob/5dfea5e43e990189802641b960bb6f95e81b5b9d/docs/GettingStarted.md?plain=1#L1662-L1730

**Comment by ivoanjo** [comment]
Thanks anyway for caring enough to let us know about it :)
