### ISSUE TITLE
Is there documentation for adding instrumentation in contrib?

### ISSUE THREAD

**Issue by Aqualon** [DataDog/dd-trace-rb#2680]
The existing instrumentations for different services are in https://github.com/DataDog/dd-trace-rb/tree/master/lib/datadog/tracing/contrib but I couldn't find documentation on how to add a new one there. Is there any documentation or are people just copying one of the existing ones and try to make it work somehow?

**Comment by TonyCTHsu** [comment]
👋 @Aqualon are you looking for [this](https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md#writing-new-integrations)? Or you were asking for something else?

**Comment by Aqualon** [comment]
Thanks @TonyCTHsu it is, somehow overlooked this.

> Integrations should implement the configuration API for easy, consistent implementation. (See existing integrations as examples of this.)

Maybe what could be useful, would be a documentation of this configuration API, but if people so far managed to add new integrations by copy&paste&adapt, maybe it's also not needed.

**Comment by ivoanjo** [comment]
Also, do feel free to open a draft PR with your work if there's something you're not quite figuring out -- we'll help out :)
