### ISSUE TITLE
Disable instrumentation when tracing is disabled

### ISSUE THREAD

**Issue by josh-coderpad** [DataDog/dd-trace-rb#2693]
**Current behaviour**
`DD_APM_ENABLED=false` doesn't disable tracing fully, resulting in lots of log noise. Note that per [the docs](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#additional-configuration), this is a known limitation:
> If set to false instrumentation will still run, but no traces are sent to the trace agent.

**Expected behaviour**
`DD_APM_ENABLED=false` disables tracing fully

**Steps to reproduce**
1. Follow [these steps](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/) to set up tracing (I'm using [the Heroku buildpack](https://github.com/DataDog/heroku-buildpack-datadog) and `gem "ddtrace", require: "ddtrace/auto_instrument"`
2. Follow steps necessary for settings to take effect (e.g. this var specifically requires a slug rebuild/new deploy to take effect)
3. See lots of stack traces, e.g. `Internal error during Datadog::Transport::HTTP::Client request. Cause: Errno::ECONNREFUSED Failed to open TCP connection`

Unless there's some utility in leaving tracing enabled without sending the traces, I think this would be beneficial both in terms of reading existing errors/logs, as well as log volume.

**Comment by delner** [comment]
Unfortunately not possible. For two reasons:

1. You can't remove modules/method patches once you inject them in Ruby code. The hooks are there permanently, until you restart your app or reload the affected constants.
2. The nature of the trace API does not safely allow code to be skipped; the critical section and trace annotation are part of the same block. There's no way to "skip" right to the wrapped code safely, and injecting in a fake span/mock could still result in errors.

We have some ideas on how to improve this in the future (using a new instrumentation hook API), but we're a ways off from implementing this just yet. Happy to update this once this improvement is in place.

In the interim, if you anticipate you want to disable tracing via ENV flag, I would not use `auto_instrument` and add conditional logic to your Datadog configuration file instead. Sorry for the inconvenience.

**Comment by josh-coderpad** [comment]
Yeah our plan is to conditionally load the file (looked into not using auto_instrument but it seems like substantially more config if we do that). This check could also go in the auto_instrument file, as the env var is present before the app starts. Anyway thanks for your response.
