### ISSUE TITLE
The gem documentation link in the README responds 404.

### ISSUE THREAD

**Issue by nyagato-00** [DataDog/dd-trace-rb#2749]
**Current behaviour**

The gem documentation link in README.md of the following revision responds 404.
https://github.com/DataDog/dd-trace-rb/tree/fd508339623f6468a2ba1442c3ebda14f18dc8d0

**Expected behaviour**

I expect to be able to view the documentation in the gem documentation link in the README.md.

**Steps to reproduce**

1. open README.md of the following revision
2. go to the Getting started chapter
Select the gem documentation link or go to the link
4. you will get a 404 response

https://github.com/DataDog/dd-trace-rb/tree/fd508339623f6468a2ba1442c3ebda14f18dc8d0

**How does `ddtrace` help you?**

<img width="926" alt="スクリーンショット 2023-04-05 11 24 14" src="https://user-images.githubusercontent.com/12161701/229964893-2b8f7ecc-e3fb-4825-bfc7-85e0a7831656.png">

Select the `YARD documentation` link under `API documentation`.

https://github.com/DataDog/dd-trace-rb/blob/fd508339623f6468a2ba1442c3ebda14f18dc8d0/docs/GettingStarted.md

<img width="1098" alt="スクリーンショット 2023-04-05 11 20 16" src="https://user-images.githubusercontent.com/12161701/229964657-d70860c7-3fcf-4ee8-981e-2a438e9bdd72.png">

Select `gem documentation` under `YARD documentation` link
https://www.rubydoc.info/gems/ddtrace/

<img width="1149" alt="スクリーンショット 2023-04-05 11 20 23" src="https://user-images.githubusercontent.com/12161701/229964665-7db659cb-2be4-4d15-a749-f519ac3a83aa.png">

The `gem documentation` link could be browsed.
https://s3.amazonaws.com/gems.datadoghq.com/trace/docs/index.html

**Environment**

* **ddtrace version: 1.10.1
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:**
* **Operating system:**
* **Relevant library versions:**

**Comment by ivoanjo** [comment]
Thanks @nyagato-00 for the report! Indeed you've caught us part-way through a migration, but we'll prioritize fixing that since having the API docs available is pretty important :sweat_smile:

**Comment by marcotc** [comment]
The documentation has been published to https://datadoghq.dev/dd-trace-rb/. Thank you for the report, @nyagato-00!
