### ISSUE TITLE
Add query source to ActiveRecord spans

### ISSUE THREAD

**Issue by tradiff** [DataDog/dd-trace-rb#2779]
**Is your feature request related to a problem? Please describe.**
The problem is tracking down the Rails code responsible for a particular query. This often comes up when reviewing the trace for a slow HTTP request or worker run. Often these reveal N+1 queries or long running queries. When these traces are very complex, it can be easy to find the bad query in Datadog, but a lot of effort to correlate this to our actual source code.

**Describe the goal of the feature**
Include the filename and line number responsible for executing the query.

**Describe alternatives you've considered**
* Add DataDog spans around important code, which helps narrow things down if the query happens to be within a span.
* Execute the endpoint or worker locally where you have verbose_query_logs enabled.
* Browse the code manually trying to locate what's running the query.

**Additional context**
Rails has a setting to output this information to the logs: `ActiveRecord.verbose_query_logs = true`. This simply outputs the filename and line number after each query. It would be very helpful to have this information in datadog traces. If it helps, here is the source for the rails implementation:
https://github.com/rails/rails/blob/bcc2e0c4e4c5eb2d706a7b9515ecd52265845c29/activerecord/lib/active_record/log_subscriber.rb#L137-L139

**Comment by ivoanjo** [comment]
The team discussed this again today, and we recommend using profiling for this feature, instead of adding it to tracing, where it would have a negative impact on overhead.

Hopefully this makes sense, and do feel free to open/reopen if needed!
