### ISSUE TITLE
Upgrade to ddtrace 1.7.0 from 0.16.1 removes rails sub-service rails-postgres and rails-cache on service page

### ISSUE THREAD

**Issue by tianxingliu** [DataDog/dd-trace-rb#2793]
Hello there! I'm having issue after upgrading to ddtrace 1.7.0 version to have some of the rails sub services to show up in the service page. 

**Current behaviour**
This is my current configuration (using ddtrace 1.7.0):
```
config.tracing.instrument :aws,       service_name: "<my-service-name>-aws"
config.tracing.instrument :http,      service_name: "<my-service-name>-http"
config.tracing.instrument :rails,     service_name: "<my-service-name>-web"
config.tracing.instrument :rake,      service_name: "<my-service-name>-rake"
config.tracing.instrument :redis,     service_name: "<my-service-name>-redis"
config.tracing.instrument :sidekiq,   service_name: "<my-service-name>-worker"
```

And this is the previous configuration (using ddtrace 0.16.1):

```
config.use :aws,       service_name: "<my-service-name>-aws",       distributed_tracing: false
config.use :http,      service_name: "<my-service-name>}-http",      distributed_tracing: false
config.use :rails,     service_name: "<my-service-name>-web",       distributed_tracing: false
config.use :rake,      service_name: "<my-service-name>-rake",      distributed_tracing: false
config.use :redis,     service_name: "<my-service-name>-redis",     distributed_tracing: false
config.use :sidekiq,   service_name: "<my-service-name>-worker",    distributed_tracing: false
```

After using the current configuration, I no longer see the rails sub-services, `<my-service-name>-web-postgres` and `<my-service-name>-web-cache`,  in my service page. For example, the postgres requests, `postgres.query`, were now sending to the generic `postgres` service now instead of  `<my-service-name>-web-postgres`.

I tried to add the following configurations for them specifically: 

```
config.tracing.instrument :pg,     service_name: "<my-service-name>-web-postgres"
config.tracing.instrument :active_support,   cache_service: "<my-service-name>}-web-cache"
```

But they were no longer receiving data specific to `:rails` but rather receiving data for the entire apps now. For example, using the old configuration (with ddtrace 0.16.1), I can see the specific query that being send to "<my-service-name>-web-postgres" in the resources section, but with` instrument: pg` I'm no longer receiving that. I would like to have Datadog to stick to the same behavior as using the old configuration.

**Expected behaviour**
I should see `operation: postgres.query` being send to `<my-service-name>-web-postgres` and `opeartion: rails-cache` being send to `<my-service-name>-web-cache`

**Steps to reproduce**
Upgrading ddtrace fomr 0.16.1 to 1.7.0

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version: 1.7.0**
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:2.5.3**
* **Operating system:**
* **Relevant library versions:**

**Comment by TonyCTHsu** [comment]
👋 @tianxingliu Upgrading ddtrace from 0.16.1 to 1.7.0 is quite a huge leap. 

Have you checked out our [upgrading guide for service naming](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#service-naming)? Generally speaking, I would recommend to upgrade to the latest 0.x version to see if everything make sense and then addressing other breaking changes for 1.x.

**Comment by TonyCTHsu** [comment]
> I tried to add the following configurations for them specifically:
>
> config.tracing.instrument :pg,     service_name: "<my-service-name>-web-postgres"


👋 @tianxingliu Have you try to change 
```
config.tracing.instrument :pg,     service_name: "<my-service-name>-web-postgres"
```
to
```
config.tracing.instrument :active_record,     service_name: "<my-service-name>-web-postgres"
```

**Comment by cristian-rivera** [comment]
@tianxingliu you are right, I'm running into the same issue. When using the `rails` instrumentation, no service name is provided to the `active_record` config that is instrumented for you.

https://github.com/DataDog/dd-trace-rb/blob/bc4b71683dd093960128d449fb9be54883d1e5da/lib/datadog/tracing/contrib/rails/framework.rb#L122

Other instruments like `action_mailer` do set the service name:
https://github.com/DataDog/dd-trace-rb/blob/bc4b71683dd093960128d449fb9be54883d1e5da/lib/datadog/tracing/contrib/rails/framework.rb#L88

I'm not sure if this is intentional or not, but I personally prefer prefixing my `active_record` traces with the service name!

**Comment by tianxingliu** [comment]
Hi all, sorry for the late reply and thank you all for the helpful comments! 

I was able to follow @TonyCTHsu 's suggestion to set :active_record as for the postgres service and similarly for the cache service.
