### ISSUE TITLE
How best to use custom span tags

### ISSUE THREAD

**Issue by aenand** [DataDog/dd-trace-rb#2799]
Hello! I am working on adding support for custom span tags to my organizations ruby on rails application. We are an API based company and I am setting some custom span tags to help us better track requests. I have been following this [guide](https://docs.datadoghq.com/tracing/guide/add_span_md_and_graph_it/) so an example of my reporting looks like `Datadog::Tracing.active_span&.set_tag('transaction.key', self&.token)`. 

My question is can I report this to the `Service Entry Span` rather than the lowest active span? The reason being is that in our APM traces view I'd like to be able to see the API status code alongside my custom span tags. Let me know if this isn't the right place to ask questions or if there is another guide I should be using!

**Comment by delner** [comment]
Hi @aenand!

Identifying and tagging a "service entry span" can be a bit tricky, and we don't really have any APIs built around this specific abstraction on purpose. The reasons for such are nuanced, but largely revolve around potential inconsistency in trace structure and the accessibility of trace data (sometimes the desired span has already been flushed from memory.)

In Ruby, we have our own abstraction we call "trace tags": it would look like `Datadog::Tracing.active_trace&.set_tag('transaction.key', self&.token)`. This should effectively apply the tag to the "local root span", aka the first span of a trace within a process. This might or might not be the same as a "service entry span" depending on how your spans are tagged.

Give that a shot, and let me know if that works for you.

**Comment by aenand** [comment]
Hi @delner ah rats. I guess the way you mentioned will have to do! One follow up question after doing the way you mentioned, How does APM determine the Status of `OK/Error` for a type of trace operation? (in this case `rails.action_controller`)

**Comment by aenand** [comment]
Great thank you!!

**Comment by delner** [comment]
Not entirely sure on the answer to this one. I will ask the team, see if I can get a clear response on it.

**Comment by aenand** [comment]
Thank you! I can also provide you with the clear cut use cases if that helps 😄

**Comment by delner** [comment]
Here's the response I got:

> You get all ingested data available for querying and analytics for 15 minutes and then what you only decide to retain with retention filters for 15 days.

![retention](https://user-images.githubusercontent.com/3237131/233460617-21c0ece7-67bd-4f6c-86f9-ca7600099e5c.png)

**Comment by aenand** [comment]
Gotcha so it's still up to the ingestion sampling rules. Thank you!

I've learned so much in this thread and I keep coming up with more questions but I don't want to bombard you 😄
