### ISSUE TITLE
New telemetry and remote config features breaking webmock-enabled tests

### ISSUE THREAD

**Issue by HoneyryderChuck** [DataDog/dd-trace-rb#2823]
**Current behaviour**

[httpx tests datadog and webmock integrations in the same scope](https://gitlab.com/os85/httpx/-/tree/master/integration_tests). It was never a problem until yesterday, when [the CI started complaining due to unrelated missing stubs for net-http](https://gitlab.com/os85/httpx/-/tree/master/integration_tests). 

**Expected behaviour**

The tests shouldn't have had problems, like they never had so far.

I suspect it didn't happen because:

* webmock tests are wrapped with "enable!/disable!"; so it shouldn't have impacted datadog tests, as wemock is supposed to be disabled. [I opened a ticket here](https://github.com/bblimke/webmock/issues/1025) for that.
* The telemetry feature being enabled by default means that the request is performed every time by default, even during tests, where I think it shouldn't. This, coupled with the  webmock bug above, exposed both situations.

I've since set `DD_INSTRUMENTATION_TELEMETRY_ENABLED=false`.

**Steps to reproduce**

```
# within the httpx repo
> bundle install
> bundle exec rake integration_tests
```

**Environment**

* **ddtrace version:**: 1.11.0
* **Configuration block (`Datadog.configure { |c| c.tracing.instrument(:httpx, options, &blk) }`):**
* **Ruby version:**: 3.2.1
* **Operating system:** Mac latest

**Comment by delner** [comment]
@HoneyryderChuck Thanks for the report here.

Is tracing enabled in CI for the purposes of just testing the `httpx` instrumentation? Or are you using the CI tracing feature here?

If for the prior, you may want to use a "test friendly" configuration instead. The goal would be to pipe traces and spans into a buffer that can be inspected/reset by the test, as a a replacement of the background worker that writes traces to HTTP.

We have a "test mode" feature: see https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#additional-configuration for a description. Though it may not fully satisfy what you're looking for here... (we built it mostly for the CI visibility case mentioned above.)

I think this could be a good feature request: "add a test suite friendly mechanism to pipe spans to buffer instead of HTTP." If that sounds like that fits the bill, I'd be happy to consider its implementation.

**Comment by HoneyryderChuck** [comment]
> If for the prior, you may want to use a "test friendly" configuration instead.

I based the current test configuration on existing ones for similar http clients in the ddtrace contrib. I'm not sure yet how it was fixed for `ddtrace` test suite, but I assume that a similar `DD_INSTRUMENTATION_TELEMETRY_ENABLED=false`? 

> We have a "test mode" feature

thx, will try that out next time.

> "add a test suite friendly mechanism to pipe spans to buffer instead of HTTP." If that sounds like that fits the bill, I'd be happy to consider its implementation.

I wouldn't go as far, as long as those spans are meaningful. FWIW the current "way of testing" is [buffering the spans and fetch them for assertions](https://gitlab.com/os85/httpx/-/blob/master/integration_tests/datadog_test.rb#L307)

**Comment by TonyCTHsu** [comment]
👋 @HoneyryderChuck , thanks for reporting. I can reproduce it with 

```
  it do
    WebMock.disable_net_connect!

    Datadog.configure do |c|
      c.telemetry.enabled = true
    end
  end
```
As far as I know, the current `test_mode` configuration might not be helpful. So far, we do not have other means to disable it other than configuring it explicitly, through environment variable or configuration block. But I will bring this back to our team to discuss about it.

**Comment by phantomwhale** [comment]
I've been having this problem; in the end I had to remove:

`gem "ddtrace", require: "ddtrace/auto_instrument"`

And change to just `gem "ddtrace"` and then manually specify all my instrumentations in a rails initializer file, and then specify `DD_TRACE_ENABLED=false` in my test env vars.

This is the only combination that fixed up my issues of (a) getting errors in my test logs about can't connect to agent, and (b) my Webmock test no longer failing when it tries to access an unexpected ENV var (`DD_TRACE_AWS_SERVICE_NAME`) which I hadn't mocked out (probably shouldn't be mocking ENV, but that's how the test is for now)

**Comment by louiscb** [comment]
As mentioned in the other issue, I fixed this by just turning off the tracing in my Datadog initialiser. I didn't have to change the gem file.

```
  if ::Rails.env.test?
    c.telemetry.enabled = false
  end
```

**Comment by louiscb** [comment]
Is there a way to turn off the tracing logs for development at least? E.g I see a very long message on startup in our application, even if I set the telemetry enabled flag to false. The log looks like

```
 ddtrace: [ddtrace] DATADOG CONFIGURATION - {"date":"2023-07-14T12:22:12+00:00","os_name":"x86_64-pc-linux-gnu","version":"1.12.1".......
```

**Comment by tim-wovn** [comment]
When I upgraded to v1.11.0 I had the same problem as above and solved it as others did with
```
  Datadog.configure do |c|
    c.telemetry.enabled = false
  end
```

today I attempted to upgrade to v1.13.0 and now I'm getting the same issue even with telemetry disabled.

**Comment by peterfication** [comment]
Stubbing it with the following worked:

```ruby
    stub_request(:get, "http://dd-agent:8126/info").to_return(
      status: 200,
      body: {endpoints: ["/v0.7/config"]}.to_json,
    )
    stub_request(:post, "http://dd-agent:8126/v0.7/config").to_return(
      status: 200,
      body: {}.to_json,
    )
```

But this is annoying to do ...

**Comment by lloeki** [comment]
`/v0.7/config` is an endpoint for the remote configuration feature, for your spec runs you might consider setting either one of:

```
DD_REMOTE_CONFIGURATION_ENABLED=false
```

or

```
Datadog.configure do |c|
  c.remote.enabled = false
end
```

**Comment by peterfication** [comment]
Thanks a lot @lloeki 🙏 This resolved my issue! 😊

**Comment by tim-wovn** [comment]
Your post resolved the issue for me as well!  Thank you @lloeki ! 🙇

**Comment by ivoanjo** [comment]
Thanks y'all for the feedback! dd-trace-rb 1.13.1 automatically detects test environments and disables these features so you don't have to! See #3039 for details :)

**Comment by tim-wovn** [comment]
@ivoanjo Thanks for your work on this!  Unfortunately, after upgrading to 1.13.1, if I try to remove my ddtrace config for tests, tests fail:

```
Real HTTP connections are disabled. Unregistered request: GET http://127.0.0.1:8126/info with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Datadog-Client-Computed-Top-Level'=>'1', 'Datadog-Container-Id'=>'f410e64833816ae1fad333abe62854c2bd764f9890d1fa26e0bf086da9fb924d', 'Datadog-Meta-Lang'=>'ruby', 'Datadog-Meta-Lang-Interpreter'=>'ruby-x86_64-linux', 'Datadog-Meta-Lang-Version'=>'3.2.2', 'Datadog-Meta-Tracer-Version'=>'1.13.1', 'User-Agent'=>'Ruby'} (WebMock::NetConnectNotAllowedError)
```

**Comment by ivoanjo** [comment]
@tim-wovn sorry to hear that! I've created https://github.com/DataDog/dd-trace-rb/issues/3050 to track it separately, do you mind if we move the discussion over there?
