### ISSUE TITLE
`env` & `service` configured as symbols break log correlation in 1.11.0

### ISSUE THREAD

**Issue by Aerdayne** [DataDog/dd-trace-rb#2827]
**Current behaviour**
Plain boilerplate RoR application with the following dd-trace configuration:
```ruby
Datadog.configure do |c|
  c.env = :production
  c.service = :service_a
end
```

Results in the following:
```ruby
irb(main):001:0> Datadog::Tracing.log_correlation
/<..>/ddtrace-1.11.0/lib/datadog/core/utils/safe_dup.rb:29:in `frozen_dup': undefined method `-@' for :production:Symbol (NoMethodError)
     -v if v
     ^
```

**Expected behaviour**
I think it would be great to either explicitly prohibit symbols from being passed to these configuration parameters, or preserve the old behaviour that was changed in https://github.com/DataDog/dd-trace-rb/pull/2704.

**Steps to reproduce**
Pass symbol values to `env` or `service` during configuration. 

**Environment**

* **ddtrace version:1.11.0**
* **Ruby version:3.1.2**
* **Relevant library versions:**
```
    ddtrace (1.11.0)
      debase-ruby_core_source (>= 0.10.16, <= 3.2.0)
      libdatadog (~> 2.0.0.1.0)
      libddwaf (~> 1.8.2.0.0)
      msgpack
```

**Comment by TonyCTHsu** [comment]
@Aerdayne Thanks for reporting. I can take a look into this. I think we should make it more explicit about the type for those fields and whether symbol should be allowed. 

In the meanwhile, change to string would avoid this.

```ruby
Datadog.configure do |c|
  c.env = 'production'
  c.service = 'service_a'
end
```

**Comment by ivoanjo** [comment]
We should probably call `to_s` on the value being set inside the `Settings` class to make sure it's a valid string.

**Comment by marcotc** [comment]
The fact that `c.env` and `c.service` worked with Symbols was not really intended by `ddtrace`.

We have always considered them to be Strings.
We have documented these types in our YARD docs:
* https://datadoghq.dev/dd-trace-rb/Datadog/Core/Configuration/Settings.html#service-instance_method
* https://datadoghq.dev/dd-trace-rb/Datadog/Core/Configuration/Settings.html#env-instance_method

@TonyCTHsu's suggestion is the best approach here.

**Comment by Aerdayne** [comment]
We have changed the values to strings immediately, and it's understandable that there are restrictions on the classes of objects being passed to certain configuration parameters.

However, wouldn't it be safer if the library enforced type constraints explicitly? Not only through YARD docs, but either through an appropriately raised exception whenever configuration block is evaluated, or through an implicit `#to_s` cast after configuration is done (as @ivoanjo suggested)? 

Catching this at boot time would be more appropriate, provided such capability exists in the current gem architecture, of course.

As a side note, I'd like to thank all contributors working on dd-trace-rb, it is a joy to use and Datadog itself is a phenomenal product.
