### ISSUE TITLE
How to disable remote_configuration via Ruby?

### ISSUE THREAD

**Issue by mscoutermarsh** [DataDog/dd-trace-rb#2828]
Now that remote configuration is enabled by default (1.11.0), we have these errors in our local development logs.

```
E, [2023-05-02T09:18:59.638942 #65910] ERROR -- ddtrace: [ddtrace] (/Users/mscoutermarsh/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.11.0/lib/datadog/core/remote/negotiation.rb:33:in `endpoint?') agent reachable but unexpected response: cannot negotiate /v0.7/config
E, [2023-05-02T09:18:59.639108 #65910] ERROR -- ddtrace: [ddtrace] (/Users/mscoutermarsh/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.11.0/lib/datadog/core/remote/component.rb:143:in `build') endpoint unavailable: disabling remote configuration for this process.
```

Even though:

```Ruby
  c.tracing.enabled = false
```

Is disabled in local dev.

I've done a bit of searching and can't find a way to disable it via Ruby config. Is the only option the env variable?

**Comment by mscoutermarsh** [comment]
Found the cause! It's because we also have:

```
  c.appsec.enabled = true
```

I've updated it to be disabled unless we're in production.

**Comment by TonyCTHsu** [comment]
It seems to be resolved. Closing it for now.

**Comment by urbanautomaton** [comment]
For the benefit of anyone else arriving at this issue via googling the error message, in version 1.13.0 of dd-trace-rb I was able to disable the remote configuration in ruby like so:

```ruby
Datadog.configure do |config|
  config.remote.enabled = false
end
```

**Comment by ivoanjo** [comment]
Thanks @urbanautomaton for the hint! We're tracking the impact on webmock tests in https://github.com/DataDog/dd-trace-rb/issues/2823 .

To anyone that runs into this issue, we're very interesting in knowing details on how this affected you so we can fix/improve the experience in the next releases of ddtrace.

Feel free to open an issue or chime in on this thread :)
