### ISSUE TITLE
Ability to set service name via env var

### ISSUE THREAD

**Issue by HoneyryderChuck** [DataDog/dd-trace-rb#2834]
**Is your feature request related to a problem? Please describe.**

The configuration of the service name for integrations should default to use an envvar when available. The python ddtrace package allows doing this (see [this](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/psycopg/__init__.py#L24) for an example, there are more like it).

**Describe the goal of the feature**

Not only is it a convenient way to set the service name for multiple services using datadog (instead of hand-annotate config sections), it also takes care of indirect setups (for example, I'm using the `sequel` integration, which in my case loads the `postgres` integration indirectly, I'd have to explicitly load it so I could handwrite the service name).

**Comment by TonyCTHsu** [comment]
👋 @HoneyryderChuck , I did not quite understand the issue. 

Could you provide me an example? Are you referring to our sequel instrumentation that does not contain an environment variable to assign service name?

**Comment by HoneyryderChuck** [comment]
I actually found out that the ruby sdk supports them, but with a different prefix (`DD_TRACE_` instead of `DD_`). Would be cool to coalesce on something that works for all SDKs altogether, though.

Will close it.
