### ISSUE TITLE
ActiveSupport events cause child spans to be mislabeled as service-entry

### ISSUE THREAD

**Issue by marcotc** [DataDog/dd-trace-rb#2846]
**Current behaviour**
Spans created by the [Datadog::Tracing::Contrib::ActiveSupport::Notifications::Event](https://github.com/DataDog/dd-trace-rb/blob/7303a3fe39f09768d0f529446326331f15e93465/lib/datadog/tracing/contrib/active_support/notifications/event.rb#L14) module receive their service name, resource name, and tags as the span is finishing.

This means that all child span of the ActiveSupport Notification event have already finished.

This causes service-entry span detection to fail at child spans as it depends on the parent span's service being populated by the the time the children have finished, so that service names can be compared: https://github.com/DataDog/dd-trace-rb/blob/7303a3fe39f09768d0f529446326331f15e93465/lib/datadog/tracing/span_operation.rb#L469

This causes non-service-entry spans to be marked as service-entry in the Datadog UI, making Trace Search return false positives when searching for "Service Entry Spans".

**Expected behaviour**

Service-entry detection should be reliable: child spans should not be marked as service-entry if their service name is the same as their parent, using the best information available.

**Steps to reproduce**

1. Configure `c.tracing.instrument :active_record, service_name: 'ar-service'` (or any custom service name).
1. Create an ActiveRecord trace.
    1. Two spans will be generated: a `#{adapter_name}.query` span, and a `active_record.instantiation`.
1. Inspect that the `active_record.instantiation` span is tagged with the metric `_dd.top_level: 1.0`, despite having the same service name as `#{adapter_name}.query`.

**Environment**

* **ddtrace version: 1.11.1**
* **Ruby version: Any**
* **Operating system: Any**

**Comment by delner** [comment]
@marcotc any updates on this? I know we saw this, not sure if we've made any progress on it.

**Comment by marcotc** [comment]
I've put an hour back when I created this issue to see if this was a quick win ([wip branch](https://github.com/DataDog/dd-trace-rb/compare/7303a3fe39f09768d0f529446326331f15e93465...activesupport-tag-early?expand=1#js-repo-pjax-container)), but turns out it's not.

All our integrations that subscribe to ActiveSupport currently execute their operations after the ActiveSupport event is finished, including setting the `service` name, which is the culprit in this issue.

We can't simply change all ActiveSupport subscribers in our codebase to subscribe to ActiveSupport events _before_ callback because not all the information is available at the _before_ event (e.g. information regarding the event result).

Some integrations depend on the result of an event to fully populate their respective spans.

Some integrations need to both set the span `service` name before the event is fire AND also need information about the result to populate the same span.

**Comment by Drowze** [comment]
We are facing this issue as well. Particularly the `active_record.instantiation` spans being marked as service entry are pretty annoying - is there anything we can do to remediate the issue? For instance, this is an excerpt from our current config:
```ruby
    c.tracing.instrument :rails
    c.tracing.instrument :active_record, describes: :primary do |primary|
      primary.service_name = "pg-master"
    end
    c.tracing.instrument :active_record, describes: :primary_replica do |replica|
      replica.service_name = "pg-replica"
    end
```

![Screenshot 2023-10-03 at 08 39 18](https://github.com/DataDog/dd-trace-rb/assets/9031589/034ede1b-602b-4231-b08c-a71a55b478fb)
![Screenshot 2023-10-03 at 08 45 53](https://github.com/DataDog/dd-trace-rb/assets/9031589/fcddb340-6fb6-4062-96b4-01347213c377)
_(`LocationTemplate` is a model used within a few of our services)_
