### ISSUE TITLE
`TraceOperation#full?` is not monitoring the length but the depth

### ISSUE THREAD

**Issue by beauraF** [DataDog/dd-trace-rb#2886]
**Context**
We have long running jobs, generating a lot of spans. Those jobs get OOM kill by our infrastructure because of high memory consumption, due to datadog storing a lot of spans. We therefore looked to cap the number of spans generated. `TraceOperation::DEFAULT_MAX_LENGTH` and `TraceOperation#max_length` looked promising.

```ruby
      def full?
        @max_length > 0 && @active_span_count >= @max_length
      end
``` 

But as you can see above, the `#full?` method is monitoring the number of `active_span_count`. So it's more a way of controlling depth. More than length.

I'm reporting this as a bug, as I think the intention was to monitor the number of `finished_span_count`. 

**Current behaviour**
There is no limits of spans in a trace. Leading to high memory consumption until the trace can be flush.

**Expected behaviour**
 `#full?` monitor `#finished_span_count` so we are able to put a limit on the number of spans per trace.

**Environment**

* **ddtrace version:** 1.11.1
* **Ruby version:** 3.2.2

**Comment by TonyCTHsu** [comment]
👋 @beauraF, If I understand the your origin problem for long running jobs is that those jobs become memory bloated and eventually ran out of memory. 

Have you tried the partial flushing approach with enabling `tracing.partial_flush.enabled` ? 
https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#additional-configuration

**Comment by delner** [comment]
Hi @beauraF ! I hope partial flushing worked for you. I'm going to close this for now; if it's not actually resolved, please feel free to reopen. Thank you!
