### ISSUE TITLE
Make `TraceOperation::DEFAULT_MAX_LENGTH` configurable 

### ISSUE THREAD

**Issue by beauraF** [DataDog/dd-trace-rb#2887]
**Is your feature request related to a problem? Please describe.**
Link to https://github.com/DataDog/dd-trace-rb/issues/2886. 

**Describe the goal of the feature**
We would love to be able to easily configure `TraceOperation::DEFAULT_MAX_LENGTH`. As 100 000 seems to huge on our side to protect our infrastructure.

**Describe alternatives you've considered**
We are currently doing:

```ruby
::Datadog::Tracing::TraceOperation.send(:remove_const, :DEFAULT_MAX_LENGTH)
::Datadog::Tracing::TraceOperation.const_set(:DEFAULT_MAX_LENGTH, 10_000)
```

**Comment by TonyCTHsu** [comment]
I suggested partial flushing alternatives in https://github.com/DataDog/dd-trace-rb/issues/2886#issuecomment-1576471787 . We could revisited this approach if partial flushing does not work.
