### ISSUE TITLE
Internal error during Datadog::Transport::HTTP::Client request. on EKS fargate

### ISSUE THREAD

**Issue by naruse666** [DataDog/dd-trace-rb#2899]
**Current behaviour**
ddtrace can't send to datadog-agent.
```
ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-1.12.0/lib/ddtrace/transport/http/client.rb:37:in `rescue in send_request') Internal error during Datadog::Transport::HTTP::Client request. Cause: Errno::ECONNREFUSED Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
WARN -- ddtrace: [ddtrace] DATADOG DIAGNOSTIC - Agent Error: Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Errno::ECONNREFUSED error:Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126)
```
I'm running datadog-agent as a sidecar.
When I run `curl localhost:8126` from my application to the datadog-agent container, it returns a `404 page not found.`

This PR discusses ECS Fargaate, but a 404 is responded to as well.
I'm aware that kubernetes can connect as localhost to the sidecar, but should I suspect an error on the datadog-agent side?
https://github.com/DataDog/dd-trace-rb/issues/1446

same this error [APM Connection Errors](https://docs.datadoghq.com/tracing/troubleshooting/connection_errors/).

**Expected behaviour**
No error state.

**Steps to reproduce**
I set this up as reference [Amazon EKS on AWS Fargate](https://docs.datadoghq.com/integrations/eks_fargate/).

I have not been able to confirm that the problem is on the ddtrace side, but I am hoping to learn something from the answers, as no one else has faced this problem.

**Environment**

* **ddtrace version:** 1.12.0
* **Configuration block (`Datadog.configure ...`):** only set instruments maybe it doesn't matter.
* **Ruby version:** 2.6.8
* **Operating system:** EKS on Fargate (k8s version: 1.25)

**Comment by TonyCTHsu** [comment]
👋 @naruse666 , Thanks for reporting. 

It looks like your `127.0.0.1:8126` is the [correct agent settings on tracing libraries for AWS EKS Fargate](https://docs.datadoghq.com/tracing/troubleshooting/connection_errors#containerized-setups). 

I would suggest verifying your agent status. 

Otherwise, raise an issue at [Datadog/datadog-agent](https://github.com/DataDog/datadog-agent/issues ) or [contact support](https://docs.datadoghq.com/help/)

**Comment by ideaoforder** [comment]
Is "try a startup delay" really the answer here? That seems mighty janky.

**Comment by ideaoforder** [comment]
Awesome--thanks @ivoanjo. I'll post back on this thread if we get any generally useful feedback.

**Comment by tkling** [comment]
@ideaoforder Random passerby getting the same `Errno::ECONNREFUSED Failed to open TCP connection` experience 🥴 Did you get any generally useful feedback after opening a support ticket?
