### ISSUE TITLE
Ruby Profiler with In Code configuration not generating profiles for sidekiq

### ISSUE THREAD

**Issue by liaden** [DataDog/dd-trace-rb#2901]
**Current behaviour**
After adding configuration for the ruby profiling, I am only generating profiles for rails controller actions. We already had APM working for Rails and Sidekiq beforehand.

**Expected behaviour**
Generate profiles for sidekiq jobs.

I'd rather not have to adjust the run command for sidekiq since that requires affecting our deployment tooling. It can be done, but it is a lot more aggravating as it requires dealing with other apps that are not doing any profiling.

**Steps to reproduce**: N/A

**Environment**

* versions:
  * **ddtrace version:** 1.9.0
  * **google-protobuf:** 3.23.2
  * **dogstatsd-ruby:** 5.5.0
* **Ruby version:** 2.7.8
* **Operating system:** Alpine
* **Relevant library versions:**
* **Configuration block (`Datadog.configure ...`):**
```ruby
require 'datadog/statsd'

disabled_environments = %w[test development]

Datadog.configure do |c|
  app = 'name'

  if disabled_environments.include?(Rails.env)
    c.tracing.enabled = false
  end

  c.profiling.enabled = c.tracing.enabled

  c.tracing.instrument(:rails, service_name: app)
  c.tracing.instrument(:aws, service_name: "#{app}-aws")
  c.tracing.instrument(:redis, service_name: "#{app}-redis")
  c.tracing.instrument(:pg, service_name: "#{app}-postgres")

  %i[
    ethon
    excon
    faraday
    http
    httpclient
    httprb
    rest_client
  ].each do |net|
    # Name network call services by the domain name instead of the http gem
    # https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#faraday
    c.tracing.instrument(net, split_by_domain: true)
  end

  rack_options = {
    service_name: "#{app}-rack",
    request_queuing: true,
    web_service_name: "#{app}-web-server",
    quantize: { args: { show: :all } }
  }
  c.tracing.instrument(:rack, rack_options)

  # Additional Sidekiq integration config happens in sidekiq.rb
  sidekiq_options = {
    service_name: "#{app}-sidekiq",
    client_service_name: "#{app}-sidekiq-client",
  }
  c.tracing.instrument(:sidekiq, sidekiq_options)

  # Rake integration config happens in Rakefile

  # Enable partial flushing to avoid eating up all the memory during long-running Sidekiq jobs
  # https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#payload-too-large
  c.tracing.partial_flush.enabled = true

  # Ruby VM stats
  c.runtime_metrics.enabled = true

  # link DBM and APM
  c.tracing.instrument(:pg, comment_propagation: 'full') if c.tracing.enabled
end

# Drop noisy, unhelpful traces. true = trace is dropped
noisy_spans_filter = Datadog::Tracing::Pipeline::SpanFilter.new do |span|
  (span.name == 'rack.request' && span.get_tag('http.url') == '/health_check') || # ignore health check requests
    (span.name == 'sidekiq.job_fetch' && span.status == 0) # ignore Sidekiq's periodic Redis polling unless there's an error
end
Datadog::Tracing.before_flush(noisy_spans_filter)

# This module exists to allow us to monkey patch ruby's sleep method so we
# can track the amount of ruby execution time associated with sleep.
module DatadogTraceSleepExtension
  def sleep(*)
    # Skip when there is no active span to avoid error logging
    # on the rails console and similar situations
    return super unless Datadog::Tracing.active_trace

    Datadog::Tracing.trace('sleep') do
      super
    end
  end
end

require 'datadog/profiling/preload'

Kernel.prepend(DatadogTraceSleepExtension)
Object.prepend(DatadogTraceSleepExtension)
```

**Comment by liaden** [comment]
Screenshot of what I see currently:
<img width="1592" alt="Screen Shot 2023-06-07 at 10 46 04 AM" src="https://github.com/DataDog/dd-trace-rb/assets/444656/ec710c11-4cbf-4f96-a21a-ea217fae619b">

**Comment by ivoanjo** [comment]
Hey there @liaden :wave:

> I'd rather not have to adjust the run command for sidekiq since that requires affecting our deployment tooling. It can be done, but it is a lot more aggravating as it requires dealing with other apps that are not doing any profiling.

Indeed you don't need to adjust the run command for sidekiq. Enabling the profiler via the `Datadog.configure` block is enough.

(Compared to the `configure` block, the run command has the advantage of capturing profiles from the boot of the application, but otherwise you'll get exactly the same result)

One interesting thing I spotted in your application is that it both has quite a lot of threads, and the profiler is detecting it to be idle.

If it's truly idle, you won't see many details until you start putting load on sidekiq (submitting tasks). This is because the profiler always employs sampling -- it doesn't show every function that is called, and instead it only looks periodically (usually every 10ms) at what's running.

If it's not completely idle, but the profiler is still not showing the expected info, my recommendation is to upgrade your `ddtrace`. We've made some big improvements to the profiler recently that would make the profiler get more information in such situations. I see that you're on `ddtrace` 1.9.0, and that version still was not using those improvements (it was in beta back then). Can you give the latest 1.12.0 a try?

**Comment by liaden** [comment]
Deployment with this configuration went out around 7:00PM yesterday and there was a lot of jobs running. They were in the order of 17-19/sec.

<img width="1443" alt="Screen Shot 2023-06-07 at 11 25 41 AM" src="https://github.com/DataDog/dd-trace-rb/assets/444656/68ea40f4-3c02-4062-b19f-293cb18b1bf6">

Will give 1.12.0 a try.

**Comment by liaden** [comment]
After deploying this morning, I can see the profiled function for a sidekiq jobs `perform` method in the function list on the flamegraph view, but I do not see the job class as a resource like I do when I look at the puma page. On the puma page, I get a breakdown by endpoint.

Also, I can see one of my sidekiq jobs on the puma page when I filter down to "Other Activity" under the "CPU Time by endpoint" options.

**Comment by liaden** [comment]
We are not on Sidekiq 7. 

Using the `show_from(directory:/rails_app_root/app/workers)` is pretty great at just filtering it down to load from workers.

Then, I tried setting `CPU Time by` to `File`, but my workers file that shows up in the filtered flamegraph is not in the file list:

<img width="838" alt="Screen Shot 2023-06-12 at 12 41 14 PM" src="https://github.com/DataDog/dd-trace-rb/assets/444656/2c6430de-c21e-46d9-ae7a-cd64f0f776ab">

I am getting profiles so I can close this ticket if you'd like, but I am seeing less profiling than I'd expect.

**Comment by ivoanjo** [comment]
I noticed your screenshots so far show "CPU Time"; did you have a chance to check out "Wall Time" as well?

When sidekiq jobs do a lot of waiting (for database requests, external APIs, etc), that view may be more realistic/better for tackling performance issues than only looking at "CPU Time".

> I am getting profiles so I can close this ticket if you'd like, but I am seeing less profiling than I'd expect.

We're definitely interested in making sure you're happy with the product. Happy to arrange a call to make sure you're getting the data you need, if you have the availability!

**Comment by liaden** [comment]
I hadn't tried wall time, and that view shows idle processing work and not any particular jobs. I am not surprised about a lot of idle processing since we overprovisioned things recently after seeing we were underprovisioned and pegging CPU.

A call might be a good idea since it may help with the back and forth?

**Comment by ivoanjo** [comment]
Awesome, let's make it happen. Can you e-mail me at ivo dot anjo at datadoghq dot com so we can discuss the details?
