### ISSUE TITLE
service crashing with `Segmentation fault` error

### ISSUE THREAD

**Issue by dhurba87** [DataDog/dd-trace-rb#2908]
We're getting `Segmentation fault` error when executing long-running task in sidekiq and it looks like it is related to ddtrace. Can somebody help to debug?

```
/shared/bundle/ruby/2.7.0/gems/ddtrace-1.11.1/lib/ddtrace/transport/serializable_trace.rb:79: [BUG] Segmentation fault at 0x00000000000000b8
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [aarch64-linux]

-- Control frame information -----------------------------------------------
```

**Steps to reproduce**
- it happens occasionally only

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version:** 1.11.1
* **Configuration block**
```ruby
# config/initializers/datadog-tracer.rb
require 'ddtrace/auto_instrument'

Datadog.configure do |c|
  c.profiling.enabled = Rails.env.production? || Rails.env.staging?
  c.tracing.enabled = Rails.env.production?
  c.env = Rails.env
  c.service = "<service-name>"
end
```
* **Ruby version:** 2.7.6p219
* **Operating system:** Linux

**Comment by ivoanjo** [comment]
Thanks for the info!

1. Full crash info usually looks like [this example](https://github.com/DataDog/dd-trace-rb/issues/2288#issuecomment-1270141017). Unless something goes really wrong (which it can, in a crash), Ruby generally is able to print it all.

2. Thanks for the gemfile.lock. I don't see anything that looks particularly like a smoking gun... :thinking:  I would maybe suggest upgrading to Ruby 2.7.8 and msgpack 1.7.1 "just in case" but with the current info that's just a shot in the dark.

Let us know if you do see it again, we're definitely interested in getting to the bottom of this.

**Comment by delner** [comment]
Agreed; initial signs point to `msgpack`, failing when trying to "pack" the trace ID. Maybe something about the trace ID makes it difficult to serialize.

This is low probability, but do you customize trace IDs at all? Or do you use a distributed tracing propagation style other than Datadog's? (e.g. W3C, B3, etc..)

**Comment by delner** [comment]
Hi @dhurba87! Just wanted to follow up on this. Were you able to resolve this? Or do you have any additional information you can share?

**Comment by ivoanjo** [comment]
>  I'll reopen the issue if I encounter it again.

:+1: Thanks for the update! I'll mark it as closed for now, please do reopen if the issue shows up again.
