### ISSUE TITLE
Rails version comparison bug in Datadog::Tracing::Contrib::ActiveRecord::Utils.db_config

### ISSUE THREAD

**Issue by tomekchime** [DataDog/dd-trace-rb#2924]
**Current behaviour**
`Datadog::Tracing::Contrib::ActiveRecord::Utils.adapter_name` always returns `defaultdb` for Rails version 7.0

**Expected behaviour**
`Datadog::Tracing::Contrib::ActiveRecord::Utils.adapter_name` returns the correct adapter name for Rails version 7.0

**Steps to reproduce**

[Datadog::Tracing::Contrib::ActiveRecord::Utils.db_config](https://github.com/DataDog/dd-trace-rb/blob/bdd22a40a837ad3bc9d034726753afea7f75c15a/lib/datadog/tracing/contrib/active_record/utils.rb#L115-L121) returns the configuration hash for the database.

`::Rails::VERSION::MAJOR >= 6 && ::Rails::VERSION::MINOR >= 1` is really meant to check for Rails version >= 6.1 but because of the `::Rails::VERSION::MINOR >= 1`  conditional, it doesn't pass for Rails version 7.0 (where `::Rails::VERSION::MAJOR` will be > 6, but `::Rails::VERSION::MINOR` will be < 1).

From here it tries to call `connection_pool.spec.config` (which doesn't exist for rails versions >6.1) and throws a `NoMethodError: undefined method spec for #<ActiveRecord::ConnectionAdapters::ConnectionPool...` exception.

That exception is then [caught by this line](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/active_record/utils.rb#L110-L112), which returns an `EMPTY_CONFIG`. When it comes time to normalize the db vendor, it's nil and so defaultdb is returned here https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/utils/database.rb#L16

**Environment**

* **ddtrace version:** N/A
* **Configuration block:** N/A
* **Ruby version:** Any supported by Rails 7
* **Operating system:** Any
* **Relevant library versions:** Rails 7.0

**Comment by tomekchime** [comment]
Tried my hand at creating a patch for this, but I couldn't figure out the command to correctly run `spec/datadog/tracing/contrib/active_record/utils_spec.rb`

I tried the following:

```
bundle exec appraisal ruby-2.7.6-rails5-postgres rake spec:active_record
bundle exec rake spec:active_record
bundle exec appraisal ruby-2.7.6-rails5-postgres rspec spec/datadog/tracing/contrib/active_record/utils_spec.rb
bundle exec rspec spec/datadog/tracing/contrib/active_record/utils_spec.rb
```

Each command returned a different error trying to run the test 😢

**Comment by TonyCTHsu** [comment]
👋 @tomekchime , I think we are missing `require 'active_record'` for `spec/datadog/tracing/contrib/active_record/utils_spec.rb` if trying to this single file. 

I suggest to tried out the following commands:
```
bundle exec appraisal ruby-2.7.6-contrib rake spec:active_record
# or
bundle exec appraisal ruby-2.7.6-contrib rspec spec/datadog/tracing/contrib/active_record/utils_spec.rb
# or 
bundle exec appraisal ruby-2.7.6-rails5-mysql2 rspec spec/datadog/tracing/contrib/active_record/utils_spec.rb
```

I have not looked into the error you mentioned yet, and it would be awesome if you already have a fix for it.

**Comment by delner** [comment]
> it tries to call `connection_pool.spec.config` (which doesn't exist for rails versions >6.1)

@tomekchime Do you know if there's an alternative for this in Rails 7.x by chance?

**Comment by GustavoCaso** [comment]
@tomekchime the latest release of dd-trace-rb `1.1.4.01 includes the [fix](https://github.com/DataDog/dd-trace-rb/pull/3051) for this bug. 

Please let us know if the issue is resolved on your end 😄 

Thank you so much for opening the issue
