### ISSUE TITLE
warning for workaround for mysql2 BUT we're running latest mysql2 and libmysqlclient on 20.04

### ISSUE THREAD

**Issue by dfuentes77** [DataDog/dd-trace-rb#2954]
**Current behaviour**
I'm using latest mysql2 gem 0.5.5 with latest dd-trace-rb gem version 1.12.1 on ubuntu 20.04, but I'm seeing these warnings:
```
W, [2023-07-07T03:43:05.047679 #213807]  WARN -- ddtrace: [ddtrace] Enabling the profiling "no signals" workaround because an incompatible version of the mysql2 gem is installed. Profiling data will have lower quality.To fix this, upgrade the libmysqlclient in your OS image to version 8.0.0 or above.
```
**Expected behaviour**
I shouldn't see those warnings and profiling should be enabled

**Steps to reproduce**
I'm finding that it's failing on [this line in dd-trace](https://github.com/DataDog/dd-trace-rb/blob/8d303a972c50c0c7b8fe2f6a893c96ef8dd44cbe/lib/datadog/profiling/component.rb#L248)

But when I run those checks and the following in rails console, I get back the correct libmysqlclient version and its newer than the required version:
```
irb(main):001:0> defined?(Mysql2::Client)
=> "constant"
irb(main):002:0> Mysql2::Client.respond_to?(:info)
=> false
irb(main):003:0> Mysql2::Client.info[:version]
=> "8.0.33"
irb(main):004:0> libmysqlclient_version = Gem::Version.new(Mysql2::Client.info[:version])
=> #<Gem::Version "8.0.33">
irb(main):005:0> compatible = libmysqlclient_version >= Gem::Version.new('8.0.0')
=> true
```

**How does `ddtrace` help you?**
Using it as a general APM for performance tracking

**Environment**

* **ddtrace version:** 1.12.1
* **Configuration block:**
```
unless Rails.env.development? || Rails.env.test?
  Datadog.configure do |c|
    c.profiling.enabled = true
    c.runtime_metrics.enabled = true
    c.tracing.analytics.enabled = true
    c.tracing.partial_flush.enabled = true
    c.tracing.sampling.default_rate = Rails.env.production? ? 0.1 : 1.0
    rev_file = '/data/api/current/REVISION'
    if File.exist?(rev_file) && File.readable?(rev_file)
      c.version = File.read('/data/api/current/REVISION')
    end
    # Shared under one service name
    c.tracing.instrument :rails, log_injection: true, service_name: Rails.env + '-api'
    c.tracing.instrument :active_model_serializers, service_name: Rails.env + '-api'
    c.tracing.instrument :concurrent_ruby, service_name: Rails.env + '-api'
    c.tracing.instrument :faraday, service_name: Rails.env + '-api'
    c.tracing.instrument :http, service_name: Rails.env + '-api'
    c.tracing.instrument :httpclient, service_name: Rails.env + '-api'
    # Use distinct service names
    c.tracing.instrument :aws, service_name: Rails.env + '-api-aws'
    c.tracing.instrument :dalli, service_name: Rails.env + '-api-memcached'
    c.tracing.instrument :redis, service_name: Rails.env + '-api-redis'
    c.tracing.instrument :sidekiq, service_name: Rails.env + '-api-sidekiq', client_service_name: Rails.env + '-api-sidekiq-client'
  end
end
```

* **Ruby version:** 2.6.8
* **Operating system:** Ubuntu 20.04
* **Relevant library versions:** mysql2 gem 0.5.5

**Comment by ivoanjo** [comment]
Hey @dfuentes77, thanks for reaching out!

This is indeed weird... :thinking: 

You mentioned that the check is failing on line 248:

https://github.com/DataDog/dd-trace-rb/blob/8d303a972c50c0c7b8fe2f6a893c96ef8dd44cbe/lib/datadog/profiling/component.rb#L248

I'm curious -- how did you spot that this specific line was failing? Were you able to observe a situation where after `require 'mysql2'` those classes/methods don't exist?

That would mean that somehow the gem isn't quite loaded when we run our check, which makes me suspect something with bundler and the gemfile not being loaded yet. Can you share the full command that you're using to start your application in production?

Finally, until we figure this out, it's actually possible to disable the workaround manually, using either the `DD_PROFILING_NO_SIGNALS_WORKAROUND_ENABLED` environment variable or `c.profiling.advanced.no_signals_workaround_enabled = false`.

**Comment by ivoanjo** [comment]
> I'm curious -- how did you spot that this specific line was failing? Were you able to observe a situation where after require 'mysql2' those classes/methods don't exist?

:sweat_smile:  I just realized that you showed off

```
irb(main):002:0> Mysql2::Client.respond_to?(:info)
=> false
```

on irb. Let me see if I can reproduce it with that exact Ruby/gem combination.

**Comment by ivoanjo** [comment]
I was not able reproduce the same interaction on irb, with the same Ruby/mysql2 version.

On top of sharing the command you're using to start your application in production, could you try running the following commands on your Rails console, one by one, and sharing the results:

```ruby
Mysql2::Client.respond_to?(:info)

Mysql2::Client.info[:version]

Mysql2::Client.respond_to?(:info) # I'm curious to see if this changes after info has been called the first time

(Mysql2::Client.methods - Object.methods).sort

(Mysql2::Client.instance_methods - Object.methods).sort
```

Thanks! :)

**Comment by dfuentes77** [comment]
Thanks for looking into this.  

Sure here is the command we run inside a systemd service file:
`/usr/local/rbenv/shims/bundle exec puma -e production config.ru`

and here are the results of the above commands:
```
irb(main):001:0> Mysql2::VERSION
=> "0.5.5"
irb(main):002:0> Mysql2::Client.respond_to?(:info)
=> false
irb(main):003:0> Mysql2::Client.info[:version]
=> "8.0.33"
irb(main):004:0> Mysql2::Client.respond_to?(:info)
=> false
irb(main):005:0> (Mysql2::Client.methods - Object.methods).sort
=> [:method_missing]
irb(main):006:0> (Mysql2::Client.instance_methods - Object.methods).sort
=> [:client, :method_missing, :query, :reconnect!]
```

**Comment by ivoanjo** [comment]
Huh... That's _very_ interesting. Are you by any chance using `mysql2-aurora`?

That `reconnect!` method doesn't exist anywhere in the `mysql2` gem codebase, and through a bit of googling I found `mysql2-aurora` has that method + monkey patches itself in front of `mysql2`.

You can doublecheck if that's the case in irb using `source_location`:

```ruby
[11] pry(main)> Mysql2::Client.instance_method(:query).source_location
=> [".rvm/gems/ruby-2.7.7/gems/mysql2-0.5.5/lib/mysql2/client.rb", 149]
```

...which will change with that gem to:

```ruby
[3] pry(main)> Mysql2::Client.instance_method(:query).source_location
=> [".rvm/gems/ruby-2.7.7/gems/mysql2-aurora-0.5.2.1/lib/mysql2/aurora.rb", 24]
```

**Comment by dfuentes77** [comment]
yes, we are using the mysql-aurora gem.  Is there a quick hack/workaround if that's getting in the way or do i have to wait until they fix it?

**Comment by ivoanjo** [comment]
> Thanks. I was thinking of a workaround where profiling would still be enabled since my setup with mysql2 and libmysqlclient is compatible, but with that NO_SIGNALS_WORKAROUND, doesn't that mean that profiling would still be disabled?

Ah! To clarify: the "no signals" workaround modifies how the profiler triggers data collection, but you still get profiles with or without it.

The default for the no signals workaround is auto (e.g. that's why it turned on in your case); if you force it to off what happens is that you'll get the regular working mode of the profiler data collection, which uses signals.

(If you're not seeing profiles and you've enabled the profiler, that's a different issue, and definitely not expected!)
