### ISSUE TITLE
Ability to scrub sensitive query string params from net/http spans

### ISSUE THREAD

**Issue by fgrehm** [DataDog/dd-trace-rb#3014]
**Is your feature request related to a problem? Please describe.**

We consume a third party API that does not support authentication using HTTP headers, we are forced to pass in tokens as query strings which are ultimately captured as DD traces.

**Describe the goal of the feature**

It would be great if there was a way to configure the net/http integration to scrub query params based on host or param names.

**Describe alternatives you've considered**

As of now I'm trying to come up with a way to monkey patch ddtrace to get those tokens out of DD spans, will report back if I get it to work in case others hit this as well.

**Additional context**

![image](https://github.com/DataDog/dd-trace-rb/assets/81859/7c71ff3e-ce03-4d84-9109-ceba1e20c7af)

**How does `ddtrace` help you?**

**Comment by fgrehm** [comment]
If anyone else is in the same situation, here's how we redacted the param from traces:

```ruby
# config/initializers/00_datadog.rb
Datadog::Tracing::Contrib::HTTP::Instrumentation.after_request(
  &NetHttpInstrumentationCleaner.method(:clean)
)

# lib/net_http_instrumentation_cleaner.rb
module NetHttpInstrumentationCleaner
  EXAMPLE_HOST_REGEX = /example.io$/

  def self.clean(span, http, request, response)
    host = span.get_tag(Datadog::Tracing::Metadata::Ext::TAG_PEER_HOSTNAME)
    if host !~ EXAMPLE_HOST_REGEX
      return
    end

    url = span.get_tag(Datadog::Tracing::Metadata::Ext::HTTP::TAG_URL)
    url = url.gsub(/(api_key=[^&]+)/, 'api_key=REDACTED')
    span.set_tag(Datadog::Tracing::Metadata::Ext::HTTP::TAG_URL, url)
  end
end
```

**Comment by TonyCTHsu** [comment]
👋 @fgrehm , Thanks for reporting. 

I like your implementation with `after_request` hook to clean it up, pretty neat!

Last time I checked, only `net/http` integration exposed this `after_request` hook, but not other http client integrations. I supposed you also have other http client integrations running into this, no?

**Comment by fgrehm** [comment]
> I supposed you also have other http client integrations running into this, no?

We do use other HTTP clients for other APIs. I haven't checked all the 3rd party API client gems we use but I remember we have HTTParty and Faraday installed for ex, there could be more :speak_no_evil: 

Thankfully there's only one 3rd party API we consume that _requires_ tokens to be set in the URI, all of the other APIs we consume support HTTP headers for auth so this is not a problem (unless ddtrace blindly pushes HTTP headers to traces which I believe it doesn't :sweat_smile: )

**Comment by TonyCTHsu** [comment]
👋 @fgrehm , Thanks for the feedback. I do believe this is a valid request that is useful for many others. 

I am taking this back to our team with plans to implement filtering for all http spans.

**Comment by marcotc** [comment]
👋 @fgrehm, could you submit a support ticket with Datadog at https://help.datadoghq.com/hc/en-us/requests/new, so we can look specifically into your account data?

Feel free to link to this GitHub issue in the ticket, so that we can quickly triage it.
