### ISSUE TITLE
Track Active Record instantiations

### ISSUE THREAD

**Issue by dasch** [DataDog/dd-trace-rb#311]
[`instantiation.active_record`](http://guides.rubyonrails.org/active_support_instrumentation.html#instantiation-active-record) is being emitted in newer versions of Rails. A significant amount of time can be spent instantiation AR classes, so it would be nice to track it.

**Comment by delner** [comment]
Opened a pull request to track this: https://github.com/DataDog/dd-trace-rb/pull/334

**Comment by palazzem** [comment]
Closed via https://github.com/DataDog/dd-trace-rb/pull/334
