### ISSUE TITLE
Nested Span tags with + and - buttons

### ISSUE THREAD

**Issue by ccoffey** [DataDog/dd-trace-rb#3117]
Auto instrumented traces have span tags which are nested and have these nice `+` and `-` buttons so I can expand/collapse levels. Here is an example `operation: rack.request`:

![Screenshot 2023-09-08 at 07 52 07](https://github.com/DataDog/dd-trace-rb/assets/456400/f81bae54-6246-49dd-9890-21a5b72e470c)

However, when I  try to create a span with nested tags like so:

```ruby
Datadog.tracer.trace("cathal") { |span| span.set_tags("a"=>{"b"=>"c","d"=>"e"})}
=> {"a"=>{"b"=>"c","d"=>"e"}}
```

They end up being displayed in this much less useful format (no `-` or `+` buttons to expand/collapse levels):

![Screenshot 2023-09-08 at 08 02 29](https://github.com/DataDog/dd-trace-rb/assets/456400/522dcb5b-6819-443e-a458-5f8f0bdb69af)

Am I doing something wrong?

**Comment by marcotc** [comment]
👋 @ccoffey, you can nest tags with a `.` character, for example in the first screenshot you posted, `set_tag('http.base_url', 'http://localhost:3000')` is how we get the nested tag.
