### ISSUE TITLE
[ddtrace-1.14.0] Consistent Segmentation Fault 

### ISSUE THREAD

**Issue by Nealsoni00** [DataDog/dd-trace-rb#3151]
**Current behaviour**
Current random pods/nodes that are ruby are segmentation fault crashing. This is NOT happening frequently but does happen enough to raise an issue. 

This has been happening for the last 2 weeks. 

**Expected behaviour**
No segmentation fault. 

**Steps to reproduce**
Not sure how to reproduce but can provide log files. 

**Environment**
Dev/Staging/Production

* **ddtrace version:** 1.14.0
* **Configuration block (`Datadog.configure ...`):**
```ruby
Datadog.configure do |c|
    c.tracing.instrument :rails, request_queuing: true
    c.tracing.instrument :pg, service_name: "postgres", comment_propagation: "full"
    c.tracing.instrument :sidekiq, tag_args: true, distributed_tracing: true
    c.tracing.instrument :aws
    c.tracing.instrument :http
    c.tracing.instrument :redis
    c.tracing.instrument :grpc

    c.diagnostics.startup_logs.enabled = false

    if ENV["DD_APPSEC_ENABLED"] == "true"
      c.appsec.enabled = true
      c.appsec.instrument :rails
    end

    c.runtime_metrics.enabled = ENV["DD_RUNTIME_METRICS_ENABLED"] == "true"
    c.runtime_metrics.statsd = Datadog::Statsd.new(ENV.fetch("HOST_IP", "localhost"), 8125, namespace: "api")
  end
```
* **Ruby version:**
ruby-3.1.2

* **Operating system:**
Linux ARM

* **Log Files**
<img width="1426" alt="Screenshot 2023-09-22 at 6 03 37 PM" src="https://github.com/DataDog/dd-trace-rb/assets/7013191/72eb23f2-fc2d-43d6-a691-3d39ecdcb099">

DM me for logs files. I have a few.

**Comment by marcotc** [comment]
Hey @Nealsoni00, as you mentioned you have sensitive information (logs) that might be helpful here, could you please submit a formal support ticket here? https://help.datadoghq.com/hc/en-us/requests/new

This allows our full solutions team to gather all the information we have in our backend to help debug this issue.

You can link to this issue for our team's reference.

**Comment by marcotc** [comment]
👋 @Nealsoni00, we are going to follow up on this issue through the support ticket (created by [help.datadoghq.com/hc/en-us/requests/new](https://help.datadoghq.com/hc/en-us/requests/new)), so I'm going to close this GH issue.

**Comment by quinot** [comment]
@Nealsoni00 we are seeing similar segfaults currently in a Python application when DataDog app sec is enabled. Did you ever identify a root cause on your side?

**Comment by ivoanjo** [comment]
Hey @quinot 👋. Very unfortunately, segmentation faults can come from different causes, so the source of this issue is likely not the same as the issue you're seeing in dd-trace-py.

Still, we're here to help! Please do open a high priority ticket via the helpdesk in https://github.com/DataDog/dd-trace-py/issues/new/choose (or an issue on github, but that way it's hard for us to look your issue on our internal telemetry) and we'll get you sorted :)
