### ISSUE TITLE
Adding the source location to each span of our trace

### ISSUE THREAD

**Issue by nvh0412** [DataDog/dd-trace-rb#3181]
**Is your feature request related to a problem? Please describe.**

As a developer, I would like to see the backtrace of our SQL or gRPC, so I can track down where queries or gRPC call in our applications. Useful for performance optimisations.

**Describe the goal of the feature**

Consider the source location of a trace event to be the line of our code that triggered the event. We know that computing call-stack for each event would cost us significant performance costs, hence we might locate the most relevant point of our call-stack and report that as the source location as a tag inside our trace data.

Let's say we have this trace, imagine that we would know where these redis commands come from would bring a huge benefit to our devs.

![Screenshot 2023-10-04 at 4 25 02 pm](https://github.com/DataDog/dd-trace-rb/assets/1973623/90a44563-a837-4d4e-85e1-31714542a35c)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ivoanjo** [comment]
Hey @nvh0412 :wave:

You may want to give `ddtrace`'s profiler [a try](https://docs.datadoghq.com/profiler/enabling/ruby/) since it allows you to see the stack traces the profiler captured during a given span (under the "Code Hotspots" tab you see on the bottom panel).

**Comment by nvh0412** [comment]
Thanks @ivoanjo 

I really dropped the ball on this one, but just want to confirm that this "Code Hotspots" only works when we turn on the profiler feature for our app?

**Comment by ivoanjo** [comment]
> I really dropped the ball on this one, but just want to confirm that this "Code Hotspots" only works when we turn on the profiler feature for our app?

Indeed, you'll need to have the profiler enabled for data to show up on that tab. You may also want to give [the timeline visualization a try](https://docs.datadoghq.com/profiler/connect_traces_and_profiles/#span-execution-timeline-view) which is a feature we've [just released in beta for Ruby](https://github.com/DataDog/dd-trace-rb/releases#:~:text=Timeline%20view%20for%20Profiler%20beta).

**Comment by nvh0412** [comment]
Thanks heaps @ivoanjo , I'll close this issue.
