### ISSUE TITLE
Datadog::Lambda.configure_apm broken in v1.15

### ISSUE THREAD

**Issue by amancevice** [DataDog/dd-trace-rb#3202]
**Current behaviour**
`Datadog::Lambda.configure_apm` is broken in v1.15

**Expected behaviour**
`Datadog::Lambda.configure_apm { |c| ... }` should not throw an error

**Steps to reproduce**

```bash
gem install datadog-lambda:2.20.0 ddtrace:1.15.0
ruby -r datadog/lambda -e 'Datadog::Lambda.configure_apm'
D, [2023-10-16T11:05:29.686860 #674] DEBUG -- : metrics are going to be handled by the forwarder
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ddtrace/transport/io (LoadError)
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/bundle/gems/datadog-lambda-2.20.0/lib/datadog/lambda.rb:33:in `configure_apm'
	from -e:1:in `<main>'
```

**How does `ddtrace` help you?**
N/A

**Environment**

* **ddtrace version:** v1.15.0
* **Configuration block (`Datadog.configure ...`):** `Datadog::Lambda.configure_apm { |c| c.tracing.instrument :aws }`
* **Ruby version:** 3.2.2
* **Operating system:** macOS 14.1
* **Relevant library versions:** datadog-lambda v2.20.0

**Comment by ekump** [comment]
Hi @amancevice, thank you for opening this issue and apologies for any inconvenience it caused. A breaking change was accidentally introduced in dd-trace-rb [v1.15.0 ](https://github.com/DataDog/dd-trace-rb/releases/tag/v1.15.0)for datadog-lambda-rb. [v2.21.0](https://github.com/DataDog/datadog-lambda-rb/releases/tag/v2.21.0) of datadog-lambda-rb includes [a fix](https://github.com/DataDog/datadog-lambda-rb/pull/85). Please let us know if you continue to have issues have updating.

**Comment by amancevice** [comment]
thanks, v2.21.0 seems to resolve — cheers
