### ISSUE TITLE
Puma warning log

### ISSUE THREAD

**Issue by pbstriker38** [DataDog/dd-trace-rb#3203]
**Current behaviour**
Puma logs a warning that it has detected threads starting when the app boots

```shell
[1] ! WARNING: Detected 1 Thread(s) started in app boot:
[1] ! #<Thread:0x0000ffff7ecdf4a0@Datadog::Core::Telemetry::Heartbeat /home/ruby/vendor/bundle/ruby/3.0.0/gems/ddtrace-1.15.0/lib/datadog/core/workers/async.rb:136 sleep> - /home/ruby/vendor/bundle/ruby/3.0.0/gems/ddtrace-1.15.0/lib/datadog/core/workers/interval_loop.rb:98:in `sleep'
```

**Expected behaviour**
ddtrace should not be starting threads during app boot

**Steps to reproduce**
start puma with workers and `preload_app!`

```
bundle exec puma -w 2 --preload
```

**Environment**

* **ddtrace version:** 1.15.0
* **Configuration block (`Datadog.configure ...`):**
```ruby
Datadog.configure do |c|
  c.tracing.instrument :rack, service_name: ENV['DD_SERVICE']
  c.tracing.instrument :grape, service_name: ENV['DD_SERVICE']
  c.tracing.instrument :http, service_name: ENV['DD_SERVICE']

  c.tracing.instrument :http, describes: /\.us-west-2\.amazonaws\.com/ do |http|
    http.service_name = "#{ENV['DD_SERVICE']}-dynamodb"
  end
  c.tracing.instrument :aws, service_name: "#{ENV['DD_SERVICE']}-dynamodb"

  c.runtime_metrics.enabled = true
end
```
* **Ruby version:** 3.0.5
* **Operating system:** Alpine Linux
* **Relevant library versions:** puma v6.4.0

**Comment by pbstriker38** [comment]
Good to know. Should there maybe be some documentation somewhere that mentions this?

**Comment by ivoanjo** [comment]
Very reasonable ask! I'm thinking it could be added [to the "Known issues and suggested configurations"](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#known-issues-and-suggested-configurations) section of our docs.

I'll leave this issue open until I open a PR for it (may take a few days, a bit tight ATM!) :)

**Comment by ivoanjo** [comment]
Actually now that I got back to this, I spotted in the puma code that there's actually a way to mark threads as fork safe, which is much better! So I've opened #3279 and in the future puma will not show this warning for ddtrace threads :tada:
