### ISSUE TITLE
Broken Sidekiq <> Datadog Integration with version 5.6.1 

### ISSUE THREAD

**Issue by LindseySaari** [DataDog/dd-trace-rb#3215]
Hello,

We encountered an issue with the Datadog Sidekiq integration on our [Va.gov API](https://github.com/department-of-veterans-affairs/vets-api) after upgrading to version 5.6.1. Metrics (only for Sidekiq) stopped coming into Datadog. After downgrading back to 5.6.0, the metrics resumed as expected. For context, our Sidekiq pods operate within EKS. I'm highlighting this in case it's relevant to others facing similar challenges. For reference, you can view our dogstatsd-ruby configuration [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/datadog.rb). Additionally, we followed the direct Datadog instructions for setting up the Datadog <> Sidekiq Integration.

Best regards,
Lindsey Hattamer
Tech Lead, Va.gov Platform

**Comment by marcotc** [comment]
Hey @LindseySaari, could you let us know what metrics exactly you are missing for Sidekiq when you upgrade to dogstatsd 5.6.1?

**Comment by LindseySaari** [comment]
Hi @marcotc We were missing all of the `sidekiq.*` metrics. Everything in the table below: (we also have Sidekiq enterprise just FYI) 


![Screenshot 2023-10-25 at 11 49 27 AM](https://github.com/DataDog/dd-trace-rb/assets/5834818/a1b95711-a612-48ed-ad82-faac950b864c)

Also, sorry, I realized I may have opened this in the wrong repo. Would you rather I open this in the dogstatd-ruby repository?
