### ISSUE TITLE
Cannot disable pg instrumentation in v1.14.0

### ISSUE THREAD

**Issue by JuanitoFatas** [DataDog/dd-trace-rb#3269]
Hi 👋🏻 

I am trying to disable instrumenting pg gem via Ruby because [duplicate spans](https://github.com/DataDog/dd-trace-rb/issues/3225#issuecomment-1781872617) incurring extra costs. I tried to disable this way but it is not working. Is there any other way (disable via ENV?) I can disable pg instrumentation? Thanks!

**Current behaviour**

pg gem still being instrumented.

**Expected behaviour**

Not seeing pg gem being instrumented.

**Steps to reproduce**

```ruby
Datadog.configure do |c|
  c.tracing.instrument :pg, enabled: false
end
```

**Environment**

* **ddtrace version:** 1.14.0

**Comment by TonyCTHsu** [comment]
👋 @JuanitoFatas Thanks for reporting, I will take care of this.

**Comment by JuanitoFatas** [comment]
Upgraded to v1.18.0 and confirmed https://github.com/DataDog/dd-trace-rb/pull/3271 is working that `pg` can be disabled via `c.tracing.instrument :pg, enabled: false`. 

Thanks!
