### ISSUE TITLE
Has ddtrace v1.17.0 been yanked?

### ISSUE THREAD

**Issue by mobilutz** [DataDog/dd-trace-rb#3276]
**Current behaviour**

Updating to ddtrace v1.17.0 through bundler does not work.

The following error is raised:
```
❯ bundle update ddtrace
Fetching gem metadata from https://rubygems.org/.......
Could not find gem 'ddtrace (>= 1.17.0)' in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'ddtrace':
  ...
  * ddtrace-1.16.2
```

Strange though, that rubygems lists v1.17.0 as being present:
https://rubygems.org/gems/ddtrace

**Expected behaviour**

Updating works without error.

**Steps to reproduce**

Gemfile
```
gem 'ddtrace', '>= 1.17.0'
```

```shell
bundle update ddtrace
```

**Environment**

* **ddtrace version:** N/A
* **Configuration block (`Datadog.configure ...`):** N/A
* **Ruby version:** ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
* **Operating system:** macOS 13.5.2
* **Relevant library versions:** N/A

**Comment by ivoanjo** [comment]
It's fixed! The gem now shows up on https://index.rubygems.org/info/ddtrace and can be installed.

Thanks a lot @mobilutz for the patience, and feel free to let us know if there's anything more we can help with :)
