### ISSUE TITLE
Can't use Datadog.configure_onto on a Redis instance initiated before Datadog was configured

### ISSUE THREAD

**Issue by Drowze** [DataDog/dd-trace-rb#3277]
_opened a PR proposing a fix: https://github.com/DataDog/dd-trace-rb/pull/3278_

---

**Current behaviour**
When I have a Redis instance that was created before Datadog is configured, using `Datadog.configure_onto` on it has no effect.

**Expected behaviour**
I would expect that `Datadog.configure_onto` works fine, regardless of when the Redis instance is configured.

**Steps to reproduce**
I did setup a small test repository to reproduce the issue here: https://github.com/Drowze/datadog-debug-redis-configure-onto
But to reproduce, it is a matter of simply initializing redis before configuring Redis tracing e.g.:
```ruby
Datadog.configure do |c|
  c.service = "test-service"
  c.env = "development"
  c.logger.instance = Logger.new($stdout)
  c.runtime_metrics.enabled = true
  c.diagnostics.debug = true
end

$redis = Redis.new
Datadog.configure do |c|
  c.tracing.instrument :redis
end
$redis_2 = Redis.new

# This configure_onto doesn't work; interactions with this redis instance will
# be reported with default "redis" service name and "command_args" false.
# This happens because this redis instance was initialized before Datadog redis
# instrumentation was configured.
Datadog.configure_onto($redis, service_name: "my-custom-redis", command_args: true)

# This configure_onto works fine, as it was initialized after Datadog redis
# instrumentation was configured.
Datadog.configure_onto($redis_2, service_name: "my-other-redis", command_args: true)
```

**How does `ddtrace` help you?**
We use a lot Datadog in our services and its distributed tracing feature is fantastic! In our particular usecase, we have a few internal gems that are writing to the same Redis host/database, but on different namespaces (so still logically separated). We want to have special service names for them, so we happened to stumble on this issue.

**Environment**

* **ddtrace version:** 1.16.2
* **Configuration block (`Datadog.configure ...`):** (already added above)
* **Ruby version:** 3.2.0
* **Operating system:** MacOS
* **Relevant library versions:** -

**Comment by TonyCTHsu** [comment]
👋 @Drowze Thanks! Will check!
