### ISSUE TITLE
Child finishing after parent "resurrects" the parent for subsequent spans

### ISSUE THREAD

**Issue by aroben** [DataDog/dd-trace-rb#33]
Consider the following code:

```ruby
a = tracer.trace('a')
b = tracer.trace('b')
b.parent == a # true

a.finish
b.finish

c = tracer.trace('c')
c.parent == a # true
```

It is surprising that `c`'s parent gets set to `a`.

This happens because `b.finish` calls `Tracer#record` which [stores the finished span's parent in the `SpanBuffer`](https://github.com/DataDog/dd-trace-rb/blob/a75ac88be8b0a32ebd815f99ba434b53e2e41262/lib/ddtrace/tracer.rb#L146). So now the already-finished parent span (`a`) gets used as the parent for subsequent `tracer.trace` calls.

Is this intended? This example is not completely contrived; imagine if `b` is measuring the execution of a subprocess that isn't `wait`ed on until after `a` has finished.

/cc @jnunemaker

**Comment by galdor** [comment]
Fixed by #49 .
