### ISSUE TITLE
Datadog CI is loading in production code and producing warnings

### ISSUE THREAD

**Issue by DougEdey** [DataDog/dd-trace-rb#3314]
**Current behaviour**

In our production env we're seeing output from datadog-ci, we never use or explicitly enable datadog-ci and I'm not sure why it's being loaded in production code

```
ERROR -- ddtrace: [ddtrace] (/<snip>/vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:56:in `validate_repository_url') DD_GIT_REPOSITORY_URL is not set or empty; no repo URL was automatically extracted
ERROR -- ddtrace: [ddtrace] (/<snip>/vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:64:in `validate_git_sha') DD_GIT_COMMIT_SHA must be a full-length git SHA. No value was set and no SHA was automatically extracted.
ERROR -- ddtrace: [ddtrace] (/<snip>/vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:56:in `validate_repository_url') DD_GIT_REPOSITORY_URL is not set or empty; no repo URL was automatically extracted
ERROR -- ddtrace: [ddtrace] (/<snip>/vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:64:in `validate_git_sha') DD_GIT_COMMIT_SHA must be a full-length git SHA. No value was set and no SHA was automatically extracted.
ERROR -- ddtrace: [ddtrace] (<snip>/vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:56:in `validate_repository_url') DD_GIT_REPOSITORY_URL is not set or empty; no repo URL was automatically extracted
ERROR -- ddtrace: [ddtrace] (/<snip>/vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:64:in `validate_git_sha') DD_GIT_COMMIT_SHA must be a full-length git SHA. No value was set and no SHA was automatically extracted.
ERROR -- ddtrace: [ddtrace] (/<snip>vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:56:in `validate_repository_url') DD_GIT_REPOSITORY_URL is not set or empty; no repo URL was automatically extracted
ERROR -- ddtrace: [ddtrace] (<snip>vendor/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:64:in `validate_git_sha') DD_GIT_COMMIT_SHA must be a full-length git SHA. No value was set and no SHA was automatically extracted.
```

**Expected behaviour**

No warnings for datadog-ci in production code.

**Steps to reproduce**

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version:** 1.18.0
* **Configuration block (`Datadog.configure ...`):**
```ruby
 Datadog.configure do |c|
    # Global settings
    c.service = service_name

    # Tracing settings
    c.tracing.enabled = Rails.application.config.dd_trace_enabled

    # Instrumentation
    c.tracing.instrument(:sidekiq, service_name: "#{service_name}-sidekiq", tag_args: true, distributed_tracing: true)
    c.tracing.instrument(:action_cable, service_name: "#{service_name}-websocket")
    c.tracing.instrument(:active_record, service_name: "#{service_name}-db")
    c.tracing.instrument(:elasticsearch, service_name: "#{service_name}-elasticsearch", quantize: { show: :all })
  end
```
* **Ruby version:** 3.2.2
* **Operating system:** Linux
* **Relevant library versions:** ddtrace 1.18.0, datadog-ci 0.5.0

**Comment by DougEdey** [comment]
I tried to use `c.ci.enabled = false` but that doesn't remove the errors.

**Comment by anmarchenko** [comment]
Hi! thanks a lot for the report, I wasn't aware of this. I will submit fix for datadog-ci gem soon in patch release.

We'll remove datadog-ci gem from ddtrace dependencies in 2.0 so it would not start in production. Nevertheless, I'll make sure that datadog-ci does not validate environment and does not spit those warning unless running in CI mode. Will add a comment here when fix is released.

**Comment by anmarchenko** [comment]
reopening the issue before the release is out

**Comment by anmarchenko** [comment]
Patch is released, this issue can be solved by updating `datadog-ci` gem to version 0.5.1: `bundle update datadog-ci`

Sorry for the inconvenience caused and thank you for your patience!

**Comment by andrewthauer** [comment]
@anmarchenko - Is there going to be a patch release of `ddtrace` as well?

**Comment by anmarchenko** [comment]
@andrewthauer there is no need to release ddtrace, bundle update datadog-ci will fix the issue

**Comment by andrewthauer** [comment]
> @andrewthauer there is no need to release ddtrace, bundle update datadog-ci will fix the issue

Yes, I realize manually bundle updating is a workaround. However, this requires extra steps, which most people won't realize until they actually run into this and find this GH issue. Why not do a patch release so that dependency updaters (e.g. dependabot) pick up the change and avoid the having folks figure this out the hard way?

**Comment by anmarchenko** [comment]
Very fair point, pushing a new version of ddtrace would indeed make the upgrade smoothly/automatically.

Our current plan is to hold off on a patch release since this issue does not break any functionality (although +1 fully agreed it is annoying). That's because we usually try to limit patch releases to showstopper issues. Hopefully this is acceptable.

**Comment by andrewthauer** [comment]
@anmarchenko - Yeah, I think showstopper is subjective here. The behaviour in our case causes all kinds of error logs, which then either eat into SLO error budgets and/or trigger alerts unnecessarily. So, I would argue this is worthy of a patch release.

**Comment by anmarchenko** [comment]
Yeah, I hear you, this is annoying. Does updating datadog-ci in your bundle solve the issue?

**Comment by andrewthauer** [comment]
It does solve the problem and yes we have many services that would need this manual fix.

The fact that the fix is buried in this GH issue is a problem. I honestly do not understand the hesitation in providing a patch release for this breaking change. This would formalize the issue and make it very noticeable in the changelog, which is likely the first place people will look that run into this problem.
