### ISSUE TITLE
New warning message `DD_GIT_REPOSITORY_URL is not set or empty; no repo URL was automatically extracted`

### ISSUE THREAD

**Issue by alexevanczuk** [DataDog/dd-trace-rb#3319]
```
E, [2023-12-11T20:13:03.420676 #1349] ERROR -- ddtrace: [ddtrace] (/opt/render/project/.gems/ruby/3.2.0/gems/datadog-ci-0.5.0/lib/datadog/ci/ext/environment.rb:56:in `validate_repository_url') DD_GIT_REPOSITORY_URL is not set or empty; no repo URL was automatically extracted
```

Hi! We just upgraded to ddtrace 1.18.0 and are now seeing this warning message.

Note that we are setting `git.repository_url` within our datadog configuration:
```ruby
Datadog.configure do |c|
  c.env = Rails.env
  c.service = DatadogHelper.service_name
  c.version = git_sha

  c.tags = {
    "git.commit.sha" => git_sha,
    "git.repository_url" => repo_url,
  }
end
```

This is a new warning so wondering if it is intentional!

**Comment by anmarchenko** [comment]
Hi Alex! No, this is not intended, sorry for this inconvenience. It was fixed here https://github.com/DataDog/dd-trace-rb/issues/3314

You can update datadog-ci dependency to 0.5.1 with `bundle update datadog-ci` and the warning will go away.
