### ISSUE TITLE
"no signals" workaround used with MariaDB-devel-11.2.2-1.el9

### ISSUE THREAD

**Issue by matt-domsch-sp** [DataDog/dd-trace-rb#3334]
**Current behaviour**
Similar to #2954, the "no signals" workaround is being enabled when MariaDB-devel (latest) is in use.
`
WARN -- ddtrace: [ddtrace] Enabling the profiling "no signals" workaround because an incompatible version of the mysql2 gem is installed. Profiling data will have lower quality. To fix this, upgrade the libmysqlclient in your OS image to version 8.0.0 or above.
`
**Expected behaviour**
The "no signals" workaround should not be enabled.

**Steps to reproduce**
```
irb(main):001> Mysql2::VERSION
=> "0.5.5"
irb(main):002>
irb(main):003> Mysql2::Client.respond_to?(:info)
=> true
irb(main):004>
irb(main):005> Mysql2::Client.info[:version]
=> "3.3.8"
irb(main):006>
irb(main):007> Mysql2::Client.respond_to?(:info) # I'm curious to see if this changes after info has been called the first time
=> true
irb(main):008>
irb(main):009> (Mysql2::Client.methods - Object.methods).sort
=> [:default_query_options, :escape, :info]
irb(main):010>
irb(main):011> (Mysql2::Client.instance_methods - Object.methods).sort
=>
[:abandon_results!,
 :affected_rows,
 :async_result,
 :automatic_close=,
 :automatic_close?,
 :close,
 :closed?,
 :encoding,
 :escape,
 :find_default_ca_path,
 :info,
 :last_id,
 :more_results?,
 :next_result,
 :parse_connect_attrs,
 :parse_flags_array,
 :parse_ssl_mode,
 :ping,
 :prepare,
 :query,
 :query_info,
 :query_info_string,
 :query_options,
 :read_timeout,
 :reconnect=,
 :select_db,
 :server_info,
 :session_track,
 :set_server_option,
 :socket,
 :ssl_cipher,
 :store_result,
 :thread_id,
 :warning_count]
irb(main):012>
```

Note: client.info has a header_version field that contains the MariaDB version string.
`Mysql2::Client.info
=> {:id=>30308, :version=>"3.3.8", :header_version=>"11.2.2"}
`

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version:**  ddtrace-1.17.0
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:** 3..1.2-p20
* **Operating system:** RHEL 9.3 UBI
* **Relevant library versions:** 

```
Name        : MariaDB-devel
Version     : 11.2.2
Release     : 1.el9
Architecture: x86_64
Install Date: Sun Dec 10 08:02:44 2023
Group       : Applications/Databases
Size        : 56828812
License     : GPLv2
Signature   : RSA/SHA512, Mon Nov 20 22:10:12 2023, Key ID f1656f24c74cd1d8
Source RPM  : MariaDB-devel-11.2.2-1.el9.src.rpm
Build Date  : Sun Nov 19 09:13:20 2023
Build Host  : rhel9-amd64
Vendor      : MariaDB Foundation
URL         : http://mariadb.org
Summary     : MariaDB database development files`
```

**Comment by ivoanjo** [comment]
Thanks for the report!

We'll make sure to whip up a PR to update the detection code to correctly flag MariaDB. Until then, if you want to skip the check there's a way to force the "no signals" workaround not to be used.

For that you can set the `DD_PROFILING_NO_SIGNALS_WORKAROUND_ENABLED` environment variable to `false` or via code:

```ruby
Datadog.configure { |c| c.profiling.advanced.no_signals_workaround_enabled = false }
```
