### ISSUE TITLE
Request for Guidance: Applying Samplers to Specific Instruments in Datadog Tracing

### ISSUE THREAD

**Issue by sinoridha** [DataDog/dd-trace-rb#3351]
Overview:
I'm exploring how to apply samplers selectively to specific instruments in Datadog tracing. Specifically, I want to set the sampling rate to 1 for the service named 'web' and 0.5 for 'kafka.'

Current Configuration Snippet:
ruby
Copy code
sampler = Datadog::Tracing::Sampling::RateSampler.new(0.5)

Datadog.configure do |c|
  c.tracing.instrument :rails, service_name: 'web'
  c.tracing.instrument :kafka, service_name: 'kafka'

  c.tracing.sampler = sampler # set sampling rate
end
Documentation Reference:
I've referred to the [Datadog Tracing Ruby Library documentation](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/ruby/#sampling), but it primarily provides examples of applying samplers at the tracing level. I would appreciate guidance on how to implement samplers for specific instruments.

Thank you for your assistance!

**Comment by benoittgt** [comment]
Hello @sinoridha 

By any chance did you try to specify 

```ruby
sampler = Datadog::Tracing::Sampling::RateSampler.new(0.5)

Datadog.configure do |c|
  c.tracing.sampler = sampler # set sampling rate

  c.tracing.instrument :rails, { service_name: 'web', analytics_sample_rate: 1.0 }
  c.tracing.instrument :kafka, service_name: 'kafka', { service_name: 'web', analytics_sample_rate: 0.5 } # for clarity

end
```

It's defined in [kafka/configuration/settings.rb](https://github.com/DataDog/dd-trace-rb/blob/a6f2af005202ba806e52448c86bf2e28c37f04e9/lib/datadog/tracing/contrib/kafka/configuration/settings.rb#L26C21-L30) 
And there is a [constant](https://github.com/DataDog/dd-trace-rb/blob/a6f2af005202ba806e52448c86bf2e28c37f04e9/lib/datadog/tracing/contrib/kafka/ext.rb#L12) for this too. 

Tell me if it's working for you? 😉

**Comment by ivoanjo** [comment]
This ticket has been open for quite a while so I'm going to assume no news is good news? Please do feel free to open a new ticket if there's anything we can help with :) (and thanks to Benoit for jumping to help on this one too!)
