### ISSUE TITLE
debase-ruby_core_source should be updated 3.3.0

### ISSUE THREAD

**Issue by mscrivo** [DataDog/dd-trace-rb#3372]
in the gemspec. I was going to do this myself and submit a PR but then I saw https://github.com/DataDog/dd-trace-rb/pull/3284/files and figured you have a script to do this quickly and painlessly?

**Comment by ivoanjo** [comment]
Hey! Thanks for the heads-up :) 

Unfortunately we're blocked by https://github.com/ruby-debug/debase-ruby_core_source/issues/10 -- the latest version is missing some headers that were added late in the Ruby 3.3 release cycle.

Without those headers, upgrading to `debase-ruby_core_source` 3.3.0 breaks dd-trace-rb (see #3353).

Just to double-check, is our usage of 3.2.3 impacting you?

**Comment by mscrivo** [comment]
> Unfortunately we're blocked by [ruby-debug/debase-ruby_core_source#10](https://github.com/ruby-debug/debase-ruby_core_source/issues/10) -- the latest version is missing some headers that were added late in the Ruby 3.3 release cycle.
> Without those headers, upgrading to `debase-ruby_core_source` 3.3.0 breaks dd-trace-rb (see #3353).

Ah thanks for that!

> Just to double-check, is our usage of 3.2.3 impacting you?

We thought it was, because we were seeing build failures in dd-trace-rb's native extension, but then we found that we were installing an old version of the `debase-ruby_core_source` gem explicitly before calling bundle install, as soon as we updated that to version 3.2.3, all was fine with dd-trace-rb during bundle. However, if we try using 3.3.0, then it breaks, probably because of the issue you mentioned above.

**Comment by ivoanjo** [comment]
> We thought it was, because we were seeing build failures in dd-trace-rb's native extension, but then we found that we were installing an old version of the debase-ruby_core_source gem explicitly before calling bundle install, as soon as we updated that to version 3.2.3, all was fine with dd-trace-rb during bundle. However, if we try using 3.3.0, then it breaks, probably because of the issue you mentioned above.

Ah, got it! Yeah, only 3.2.3 works with the final 3.3.0 release; the previous versions were missing some changes that came late in the 3.3 development cycle.

The fixed version of debase-ruby_core_source already got released so the plan is to have  https://github.com/DataDog/dd-trace-rb/pull/3373 merged to master and released very soon.
