### ISSUE TITLE
Failed to deploy via capistrano due to assets:precompile error

### ISSUE THREAD

**Issue by alienxp03** [DataDog/dd-trace-rb#3484]
**Current behaviour**
- `capistrano deploy` failed to run `assets:precompile`
- No issue to run the server: `rails server`

```ruby
/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/format.js:79
      01   if (tags['service.name']?.toLowerCase() !== tracerService) {
      01                            ^
      01
      01 SyntaxError: Unexpected token '.'
      01     at wrapSafe (internal/modules/cjs/loader.js:1070:16)
      01     at Module._compile (internal/modules/cjs/loader.js:1120:27)
      01     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      01     at Module.load (internal/modules/cjs/loader.js:1000:32)
      01     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      01     at Module.require (internal/modules/cjs/loader.js:1042:19)
      01     at require (internal/modules/cjs/helpers.js:77:18)
      01     at Object.<anonymous> (/opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/span_processor.js…
      01     at Module._compile (internal/modules/cjs/loader.js:1156:30)
      01     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      01 /opt/datadog/apm/library/nodejs/node_modules/dd-trace/packages/dd-trace/src/format.js:79
```

**Expected behaviour**
- Should not cause any error

**Steps to reproduce**
- Run `capistrano deploy staging`
- Failed at `assets:precompile` step.

**How does `ddtrace` help you?**
- I want to use the APM for my Rails app.

**Environment**

* **ddtrace version:** 1.20.0
* **Configuration block (`Datadog.configure ...`):**
```
Datadog.configure do |c|
  c.tracing.enabled = true
  c.tracing.sampling.default_rate = 0.4
end
```
* **Ruby version:** 2.7.7
* **Node version:** 12.16.2
* **Operating system:** Ubuntu 18.04.3
* **Relevant library versions:**
```ruby
# Gemfile.lock
datadog-ci (0.7.0)
      msgpack
ddtrace (1.20.0)
      datadog-ci (~> 0.7.0)
      debase-ruby_core_source (= 3.3.1)
      libdatadog (~> 5.0.0.1.0)
      libddwaf (~> 1.14.0.0.0)
      msgpack
    debase-ruby_core_source (3.3.1)
    libdatadog (5.0.0.1.0)
    libddwaf (1.14.0.0.0)
      ffi (~> 1.0)
```

**Comment by anmarchenko** [comment]
Hi! I have a very strong suspicion that this error comes not from dd-trace-rb but from https://github.com/DataDog/dd-trace-js 

Could you check your package.json if you have `ddtrace` there? 
If yes, then you can remove it as it is used for backend nodejs apps. As of latest version dd-trace-js supports node.js >= v18.

**Comment by alienxp03** [comment]
That was my suspicion too, but unfortunately my `package.json` doesn't have `ddtrace`. Does `dd-trace-rb` call `dd-trace-js` at all? Because if it doesn't, then it means something on my repo or server is calling it somehow.

**Comment by anmarchenko** [comment]
No, `dd-trace-rb` does not use `dd-trace-js`, so it is very odd that it is getting injected in your rails project

**Comment by alienxp03** [comment]
Thanks for the info. Yes, it's very odd to me too considering I have a different project using Node 12 and works just fine. Feel free to close this issue. I'll dig around more and see what else am I missing here. Will post an update here for reference to others in case I manage to find the root cause.

**Comment by alienxp03** [comment]
Some updates. Turns out it is coming from the injection in `/opt/datadog/apm` on the host (_I'm installing the agent via host, not Docker_). It is expecting a different version of Nodejs to be running. I'm not sure whether that's expected since I didn't see any Nodejs dependency in the instruction page.

What I did:

- `sudo rm -rf /opt/datadog/`
  - Probably shouldn't have done this manually😅 
- Try to install the injection and agent again using `https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)` script
  - This step unfortunately failed with error message `/usr/bin/dd-host-install: line 21: /opt/datadog/apm/inject/common_functions.sh: No such file or directory`
  - My assumption was that it will redownload `/opt/datadog/apm`, but it seems like it doesn't for some reason.

What works:
- Install using agent v6 script `https://s3.amazonaws.com/dd-agent/scripts/install_script_agent6.sh`
- No issue. And as for `dd-trace-rb`, I'm using the latest version with no issue so far. All APM data are sent to Datadog successfully.

Ideally I would prefer to run agent v7 since it's the latest, and I need to migrate to it sooner or later. But at least for now, it works (which is more important for me right now). Should I open an issue in https://github.com/DataDog/datadog-agent instead? Do let me know where is the right place for me to ask for help or checking if I'm missing anything on my agent installation. Thanks!

**Comment by anmarchenko** [comment]
Yes, I think it is best to contact datadog-agent team via https://github.com/DataDog/datadog-agent
Unfortunately I don't have a lot of context on Datadog Agent and I find it very puzzling that it auto instruments you frontend javascript code by default.

**Comment by alienxp03** [comment]
Will do. Thanks!
