### ISSUE TITLE
v1.21.0 causes outages due to a nil error in rack middleware

### ISSUE THREAD

**Issue by ejoubaud** [DataDog/dd-trace-rb#3538]
**Current behaviour**

Nil error in ddtrace rack middleware when requesting any page on a Rails 7.1.3.2 app.

**Steps to reproduce**

- upgrade to 1.21.0
- start rails app (`rails server`)
- try to load any page
- get the following error:

```
Puma caught this error: undefined method `+' for nil:NilClass (NoMethodError)
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.21.0/lib/datadog/tracing/contrib/rack/middlewares.rb:134:in `call'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webpacker-6.0.0.rc.6/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-proxy-0.7.6/lib/rack/proxy.rb:87:in `call'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.3.2/lib/rails/engine.rb:536:in `call'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/Users/ejoubaud/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

Looks like it was introduced [here](https://github.com/DataDog/dd-trace-rb/commit/6d0f1186cd067a19bdebe5eabe660e50f97f94aa#diff-5934ebefd042f70e1c83157584faa0f1d97f1777aa9621d089e0dc3273108c79R134)

Note also the commented out `# binding.pry` [in that commit](https://github.com/DataDog/dd-trace-rb/commit/6d0f1186cd067a19bdebe5eabe660e50f97f94aa#diff-1e177ffab920078613fe84e90be601a236849f0334e5d54506266d65e086df8fR79)

**Environment**

* **ddtrace version:** 1.21.0
* **Configuration block (`Datadog.configure ...`):** happens even when block is entirely removed
* **Ruby version:** 3.2.2
* **Operating system:** Mac, Linux
* **Relevant library versions:**

**Comment by ivoanjo** [comment]
Hey! Sorry that you ran into this :cold_sweat:. We're going to publish 1.21.1 ASAP with a revert of this change, since it clearly was not ready (#3539).

Thanks for the patience.

**Comment by ivoanjo** [comment]
(We've merged a fix for this, and we're in the final validation steps before publishing a 1.21.1 with the release. Because a lot of folks seem to be bitten by this, I'll go ahead and reopen the issue until we actually put the release out so folks can easily find this ticket)

**Comment by TonyCTHsu** [comment]
👋 @ejoubaud `1.21.1` has been released!
