### ISSUE TITLE
Question: could not collect runtime metrics after first refork by pitchfork.

### ISSUE THREAD

**Issue by r-plus** [DataDog/dd-trace-rb#3576]
Hi.

We recently migrate web server to [pitchfork](https://github.com/Shopify/pitchfork) from unicorn. After that migration we noticed runtime metrics are not recorded after the first refork by pitchfork.

I tried `single_thread` mode of the `Datadog::Statsd`, but not changed.
In addition, we tried replacing to new instance, but the same result.

```ruby
after_worker_fork do |_, _|
  Datadog.configuration.runtime_metrics.statsd = Datadog::Statsd.new(single_thread: true) if defined?(Datadog)
end
```

Do you have any idea for fork safety?

--- 

configuration

```ruby
  Datadog.configure do |c|
    c.env = 'production'
    c.service = 'xxx'
    c.profiling.enabled = true
    c.tracing.sampling.default_rate = 0.2
    c.runtime_metrics.enabled = true
    c.runtime_metrics.statsd = Datadog::Statsd.new(single_thread: true)
  end
```

**Comment by ivoanjo** [comment]
Hey @r-plus, thanks for reaching out!

This should trigger ddtrace to start all needed threads again after a fork:

```ruby
after_worker_fork do
  Datadog.configure { }
end
```

When we added this feature [we explicitly not made it restart on forks](https://github.com/DataDog/dd-trace-rb/pull/988#discussion_r401191677) and I'm not quite sure that decision is still the right one; I've ping'ed some folks to help out and try to confirm we can change that default.

**Comment by r-plus** [comment]
Hi @ivoanjo, thanks for your reply.

I'll try it :), APM is working event after refork but runtime metrics was no longer being collected, so that is helpful. 👍
