### ISSUE TITLE
ActionView::render swallows given block

### ISSUE THREAD

**Issue by dorner** [DataDog/dd-trace-rb#359]
`render` can take a block implementation inside ActionView. DataDog swallows this block rather than passing it onto the underlying method, which can cause crashes when it tries to render the block since other options like `:file` and `:partial` are not given.

Testing using Rails 3.0.

**Comment by delner** [comment]
Related PR https://github.com/DataDog/dd-trace-rb/pull/360

**Comment by delner** [comment]
Resolved with #360
