### ISSUE TITLE
Require 'ddtrace' needed even though gem defined in Gemfile

### ISSUE THREAD

**Issue by davidkarim** [DataDog/dd-trace-rb#361]
We were getting the following error when implementing the ddtrace gem, we were seeing this error when using version 0.11.0 all the way up to the latest beta. 
```
2018-03-05T15:39:21Z main:ROIISTCMTGP/757bfa7e2aed NameError: uninitialized constant Datadog
2018-03-05T15:39:21Z main:ROIISTCMTGP/757bfa7e2aed /app/config/initializers/datadog-tracer.rb:1:in `<top (required)>'
2018-03-05T15:39:21Z main:ROIISTCMTGP/757bfa7e2aed /gems/vendor/cache/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
```
We were only able to get rid of this error by requiring the gem in the configuration file even though we have it defined in the Gemfile and we could see that it loaded using a bundle list.

```
require 'ddtrace'

Datadog.configure do |c|
  # Tracer
  # 
```
Any input on this would be appreciated. Even though we are no longer getting the error, I don't believe that including this require statement in the configuration file is normal, and it is certainly not shown in the samples. We have the ddtrace gem defined in our Gemfile and we are on Rails 4.2.

**Comment by delner** [comment]
I can't replicate the issue. What I did was:

```sh
$ rails new blah
$ cd blah
$ touch config/initializers/datadog.rb
```

Then added to `datadog.rb`:

```ruby
Datadog.configure do |c|
end
```

Then added to `Gemfile`:

```
gem 'ddtrace'
```

Then:

```sh
$ bundle install
$ rails c
Running via Spring preloader in process 2120
Loading development environment (Rails 5.1.5)
2.4.2 :001 > Datadog
 => Datadog
```

Do you have some other set of steps I can follow to replicate the issue?

**Comment by davidkarim** [comment]
We had an erroneous environment value for RAILS_ENV which was bypassing the installation of that gem in the Gemfile. Looks like this was a bug on our side. Thanks for looking into it.

**Comment by rmsy** [comment]
Hello,

I'm sorry to dig this back up, but I'm encountering a similar issue. I have `ddtrace` required in my Gemfile, and I also can confirm that it is installed with `bundle list`. However, not even the `require 'ddtrace'` is working for me.

Here is my `datadog.rb`:
```ruby
require 'ddtrace'
require 'active_record'
Datadog.configure do |c|
  # This will activate auto-instrumentation for Rails
  c.use :rails
  c.use :active_record
end
```

Is there anything I should try? I'm not sure what I'm missing. bundler is installing ddtrace version 0.19.0.

**Comment by rmsy** [comment]
Well, after trying your steps, everything was looking good so I decided to give it another shot. I don't know what changed, but it's working just fine now.

I am assuming that it was some strangeness related to my deploy setup, but it appears to be straightened out now. Thanks for your assistance!
