### ISSUE TITLE
Qless support is missing from 2.0

### ISSUE THREAD

**Issue by sco11morgan** [DataDog/dd-trace-rb#3653]
**Is your feature request related to a problem? Please describe.**

Qless support is missing from 2.0. 

While viewing the [changelog](https://github.com/DataDog/dd-trace-rb/blob/master/CHANGELOG.md) I noticed that dd-trace-rb 2.0 removes support for Qless. We actively use Qless with DataDog at my company. Can you put re-add support? Thanks

The [PR](https://github.com/DataDog/dd-trace-rb/pull/3398) to remove it didn't list any reasoning behind taking it out.

**Comment by TonyCTHsu** [comment]
👋 @sco11morgan 

I am curious which tracer/ruby version you are using? I have updated the PR to explain the train of thoughts about the removal. 

Please contact [support](https://help.datadoghq.com/hc/en-us/requests/new), to help triage and get engineering support
