### ISSUE TITLE
GraphQL queries will error out after datadog upgrade ("Found two visible definitions")

### ISSUE THREAD

**Issue by RaphaelPLM** [DataDog/dd-trace-rb#3705]
**Current behaviour**
When Rails hot-reloads (after making any code change), some GraphQL queries will start failing with the following error:

```Found two visible definitions for `MyModel`: Types::MyModelType, Types::MyModelType```.

After restarting the Rails server, code will start to execute regularly. There are no duplicate types defined explicitly in our code base. The issue will only occur after hot reloading.

Before having this issue, I used ddtrace v0.54.2, and it wasn't a problem.

**Expected behaviour**
I'd expect the GraphQL queries to run successfully.

**Steps to reproduce**
The steps are simple:
1. Make a change in any place at the code. It can be a simple line such as `puts "abc"` on a model method.
2. Run an arbitrary GraphQL query. Doesn't matter the source. Usually I'll run through GraphiQL.

Note: Unfortunately, I couldn't reproduce this issue in a minimal Rails app using the same versions and a similar setup. Still, I wonder if this sounds familiar to any contributor. **If not having a sample app is a blocker, I'll work on getting a shareable snippet.** 

**Environment**

* **datadog version:** 2.1.0
* **Configuration block (`Datadog.configure ...`):** 
``` 
Datadog.configure do |c|
      c.agent.host = ENV.fetch('DD_AGENT_HOST')
      c.tracing.instrument :rails
      c.tracing.instrument :sidekiq, analytics_enabled: true
      c.tracing.instrument :mysql2, comment_propagation: ENV.fetch('DD_DBM_PROPAGATION_MODE')

      # To enable runtime metrics collection, set `true`. Defaults to `false`
      # You can also set DD_RUNTIME_METRICS_ENABLED=true to configure this.
      # c.runtime_metrics.enabled = true

      # Optionally, you can configure the DogStatsD instance used for sending runtime metrics.
      # DogStatsD is automatically configured with default settings if `dogstatsd-ruby` is available.
      # You can configure with host and port of Datadog agent; defaults to 'localhost:8125'.
      # c.runtime_metrics.statsd = Datadog::Statsd.new
end
```
* **Ruby version:** 2.7.6
* **Operating system: macOS Sonoma 14.0 (23A344)**
* **Relevant library versions:** `graphql: 2.1.11`, `datadog: 2.0.0`

**Comment by RaphaelPLM** [comment]
Turns out this was a false alarm, and I made some confusion when pinpoint the changes that lead to the issue. This is not related to the datadog upgrade, so I'll close the issue.

I apologize for the inconvenience!

**Comment by ivoanjo** [comment]
> Turns out this was a false alarm, and I made some confusion when pinpointing the changes that lead to the issue. This is not related to the datadog upgrade, so I'll close the issue.

:+1: Thanks for letting us know, and please do reach out if we can help in any way with your upgrade (or if you run into any issues!)
