### ISSUE TITLE
Connection Pooling to Agent

### ISSUE THREAD

**Issue by buddhistpirate** [DataDog/dd-trace-rb#372]
We're running into an issue where the agent is rate limiting us. It seems that the agent is limited to 2000 connections per lease period. However it looks like the Ruby client spins up a new connection for each request. 

Would it make more sense for the Ruby client to keep open a connection to the agent and possibly do some connection pooling if it needs to?

**Comment by delner** [comment]
It's an interesting thought, but it might heavily depend on agent implementation.

In theory, something like https://github.com/mperham/connection_pool might be useful for managing a pool of HTTP connections. However, it's not yet clear to me how these HTTP connections could be pooled, given the typical lifecycle of an HTTP 1 request.

Maybe experimenting with Keep-Alives or implementing HTTP/2 multiplexing might be the way forward on that front. Whatever the best approach is, it'd have to be reconciled with the agent implementation. Suggestions or ideas are always welcome, though.

**Comment by buddhistpirate** [comment]
I agree that it does depend on the agent implementation, but perhaps that's okay?

It also seems that for a library that is responsible for tracing, that the overhead of establishing a new connection might be a good thing to optimize. That being said this is all done in a separate thread, so maybe it doesn't matter.

I'm torn on whether this is an issue with the client or the agent. At one level it seems like the client could handle this. On the other hand, maybe the agent isn't implementing their rate-limiting in an appropriate way.

**Comment by toofishes** [comment]
Our agent logs are full of things like this; we have a high-volume transaction environment on our machines running sidekiq so we are running into connection limits it seems. Maybe there is an issue on the trace agent side where it doesn't recycle old connections fast enough?

```
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 5ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 5ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 5ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 10ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 20ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 40ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 80ms
Apr 19 12:08:21 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:21 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 160ms
Apr 19 12:08:22 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:22 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 320ms
Apr 19 12:08:22 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:22 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 640ms
Apr 19 12:08:23 worker-03 datadog-trace-agent[1465]: 2018/04/19 12:08:23 http: Accept error: accept tcp 127.0.0.1:8126: accept4: too many open files; retrying in 1s
```

**Comment by buddhistpirate** [comment]
I'm going to close this as I no longer have any issues related to this. Thanks.
