### ISSUE TITLE
Wrong MIME/Content-Type for code provenance multipart data

### ISSUE THREAD

**Issue by sivachandran** [DataDog/dd-trace-rb#3767]
**Current behaviour**
The MIME/Content-Type of the code provenance data is specified as `application/json` where as the data is binary. The code provenance data is sent as multipart form data.

Code provenance part header dump
```go
textproto.MIMEHeader{"Content-Disposition":[]string{"form-data; name="code-provenance"; filename="code-provenance.json""}, "Content-Type":[]string{"application/json"}
```

**Expected behaviour**
The `Content-Type` of the code provenance data should be `application/octet-stream`.

**Steps to reproduce**
1. Profile a Ruby application
2. Wait for the profile data to be sent to agent/server
3. Inspect the `Content-Type` of the code provenance data in the form multipart data

**How does `datadog` help you?**
I'm using ddtrace to profile Ruby application and redirecting the profile data to my server. The server generate profile metrics based on the profile data. I noticed the wrong `Content-Type` while processing the profile data request at the server.

* **datadog version:** ddtrace 1.23 
* **Configuration block (`Datadog.configure ...`):** `require 'datadog/profiling/preload'`
* **Ruby version:** 3.3.1
* **Operating system:** Debian Bookworm (12)
* **Relevant library versions:** refer below Gemfile.lock content

```
GEM
  remote: https://rubygems.org/
  specs:
    base64 (0.2.0)
    datadog-ci (0.8.3)
      msgpack
    ddtrace (1.23.0)
      datadog-ci (~> 0.8.1)
      debase-ruby_core_source (= 3.3.1)
      libdatadog (~> 7.0.0.1.0)
      libddwaf (~> 1.14.0.0.0)
      msgpack
    debase-ruby_core_source (3.3.1)
    ffi (1.17.0-x86_64-linux-gnu)
    libdatadog (7.0.0.1.0-x86_64-linux)
    libddwaf (1.14.0.0.0-x86_64-linux)
      ffi (~> 1.0)
    msgpack (1.7.2)
    mustermann (3.0.0)
      ruby2_keywords (~> 0.0.1)
    rack (3.0.11)
    rack-protection (4.0.0)
      base64 (>= 0.1.0)
      rack (>= 3.0.0, < 4)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rackup (2.1.0)
      rack (>= 3)
      webrick (~> 1.8)
    ruby2_keywords (0.0.5)
    sinatra (4.0.0)
      mustermann (~> 3.0)
      rack (>= 3.0.0, < 4)
      rack-protection (= 4.0.0)
      rack-session (>= 2.0.0, < 3)
      tilt (~> 2.0)
    tilt (2.3.0)
    webrick (1.8.1)

PLATFORMS
  x86_64-linux-gnu

DEPENDENCIES
  ddtrace (~> 1.21)
  rack
  rackup
  sinatra

BUNDLED WITH
   2.5.9
```

**Comment by ivoanjo** [comment]
Hey there!

I just took a look and I cannot reproduce this :thinking:.

Here's what I tried:

```bash
# Profile for 1 second
% DD_INSTRUMENTATION_TELEMETRY_ENABLED=false DD_PROFILING_ENABLED=true DD_PROFILING_TIMELINE_ENABLED=false be ddprofrb exec ruby -e "sleep 1"
```

```bash
# Create raw socket listener to see what comes up
% netcat -l 8126
...
content-type: application/octet-stream
content-disposition: form-data; name="code-provenance.json"; filename="code-provenance.json"
...
```

Can you perhaps repeat the same experiment on your side, and see if you get a different result?

**Comment by sivachandran** [comment]
I tried the experiment on my setup and the content-type is correct.

Further analysis revealed that the problem is not with Ruby profiler but the Python profiler. Python profiler is using `application/json` content-type for code provenance data, refer [here](https://github.com/DataDog/dd-trace-py/blob/2b14b3e4f5a700bbe7de119cd0846a1cb2b4ff52/ddtrace/profiling/exporter/http.py#L207). I was also running Python profile which generated the code provenance data with wrong content-type which I mistook coming from Ruby profiler.

I will create an issue in dd-trace-py repository.

Thanks for verifying and sharing the snippet.
