### ISSUE TITLE
`user_id cannot be nil` when manually triggering login failure appsec events 

### ISSUE THREAD

**Issue by jwoodrow** [DataDog/dd-trace-rb#3840]
**Current behaviour**

When a user tries to sign in using alternative sign in flows then login success/failures are tracked manually. But when this alternative login attempt fails because the user does not exist then there can be no `user_id` for the `Datadog::Kit::AppSec::Events.track_login_failure`

This results in an `ArgumentError user_id cannot be nil` even if `user_exists: false` is provided

**Expected behaviour**

if `user_exists: false` is provided, a `nil` value should be allowed.

**Steps to reproduce**

Call `Datadog::Kit::AppSec::Events.track_login_failure` with `user_id: nil, user_exists: false`

**How does `datadog` help you?**

We use datadog for log management, APM and security protection

**Environment**

* **datadog version:** 7
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:** 3.3.4
* **Operating system:** Heroku ubuntu
* **Relevant library versions:**

**Comment by y9v** [comment]
hey @jwoodrow, thanks for bringing this to our attention. I will work on a fix.

**Comment by y9v** [comment]
@jwoodrow this issue should be fixed in the upcoming 2.3.0 release

**Comment by y9v** [comment]
@jwoodrow We just released version 2.3.0 that fixes the issue you had.

**Comment by jwoodrow** [comment]
Going to try out the latest release next week and see how it goes, but from I saw in the PR I don't expect there'll be any issues on that front. Thanks for the quick fix
