### ISSUE TITLE
Tracing set to false stills produces lots of logs

### ISSUE THREAD

**Issue by louiscb** [DataDog/dd-trace-rb#3872]
**Current behaviour**

I set tracing to be false programmatically with: 

```
Datadog.configure do |c|
   c.tracing.enabled = false
```

I verify this in my running Rails console with:

```
irb(main):004> Datadog.configuration.tracing.enabled
=> false
```

However on startup I get several TCP connection errors. I also get an INFO log with this excerpt saying that tracing is enabled:

```
INFO -- ddtrace: [ddtrace] DATADOG CONFIGURATION - TRACING - {"enabled":true,"agent_url":"http://127.0.0.1...
```

The errors I see are:

```
INFO -- ddtrace: [ddtrace] DATADOG CONFIGURATION - CORE - {"date":"2024-08-28T10:45:07+00:00","os_name":"x86_64-pc-linux","version":"1.19.0","lang":"ruby","lang_version":"3.3.0","env":null,"service":"rails","dd_version":null,"debug":false,"tags":null,"runtime_metrics_enabled":false,"vm":"ruby-3.3.0","health_metrics_enabled":false}

WARN -- ddtrace: [ddtrace] DATADOG ERROR - TRACING - Agent Error: {"agent_error":"Datadog::Core::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Errno::ECONNREFUSED error:Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for \"127.0.0.1\" port 8126)"}
```

**Expected behaviour**

Tracing should be disabled, and there shouldn't be these large errors on startup of my application.

**Steps to reproduce**

Similar to this issue https://github.com/DataDog/dd-trace-rb/issues/2693 except the difference is the log I see regarding the tracing being enabled. 

**Environment**

* **datadog version:**
1.19.0
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:**
 3.3.0

**Comment by ivoanjo** [comment]
Hey @louiscb, thanks for reaching out :wave: 

I wonder if what's happening is that your `Datadog.configure` block is only being executed a bit later in the application boot, and so you still see the logs and attempts to trace that happened before the configure block got executed.

This can happen when using `gem 'datadog', require: 'datadog/auto_instrument'` in the Gemfile, for instance.

One suggestion is to try disabling using the `DD_TRACE_ENABLED` environment variable to disable dd-trace-rb, if possible. Setting the environment variable before the process starts ensures that it gets picked up immediately by dd-trace-rb, even if there's `Datadog.configure` block that happens later in the process.

**Comment by louiscb** [comment]
@ivoanjo thanks, setting the env variable helped with the logs

**Comment by ivoanjo** [comment]
Awesome, glad to hear that :D
