### ISSUE TITLE
Support for Delayed::Job tracking

### ISSUE THREAD

**Issue by KieranP** [DataDog/dd-trace-rb#393]
Similar to Sidekiq, Resque, and SuckerPunch, support for DelayedJob would be useful.

**Comment by delner** [comment]
Hey @KieranP, this is scheduled in our pipeline. I'll let you know when we have something ready for this.

**Comment by delner** [comment]
This was released with 0.14.0.beta2 and will make its way to stable under 0.14.0. Closing this one out. Feel free to check it out and let us know how it works for you!
