### ISSUE TITLE
Distributed Tracing Sampling - Weighting Needs Work

### ISSUE THREAD

**Issue by whithajess** [DataDog/dd-trace-rb#406]
I noticed when looking at Traces the other day that some will be lucky enough to have Full Tracing all the way through a request (microservices) and others have half or none.

It looks like because  tracing is only a sample of a request. While one service may decide to sample a particular trace, another service (for the same request) may not.

Here is an example with 3/5:

![screen shot 2018-04-24 at 3 31 03 pm](https://user-images.githubusercontent.com/2069021/39164701-06c77628-47d5-11e8-859a-1836d8d7f563.png) 

I think the weighting for deciding to sample down the chain should be be decided when the first caller makes the choice to sample (It is much better to have a full trace then lots of partials).

Does that make sense?

**Comment by whithajess** [comment]
I think you could do something like:

    If sampling?
      send header 'x-datadog-sample-rate: 1'
      if :distributed_tracing? 
         if header has x-datadog-sample-rate
         set sample rate = header

**Comment by whithajess** [comment]
Ignore this it may already exist 🤦‍♂️

**Comment by delner** [comment]
Yeah, if distributed tracing is sending headers as it should, then it forwards the sampling priority too, which gets inherited by the services further down the chain.
