### ISSUE TITLE
Setting a custom service name for net/http doesn't work.

### ISSUE THREAD

**Issue by undergroundwebdesigns** [DataDog/dd-trace-rb#407]
From my experience and from reading the code, it looks like the service name for the net/http integration is hard-coded to "net/http", which conflicts with the [docs](http://gems.datadoghq.com/trace/docs/#Net_HTTP) that say the default service name is "http" and also that it's configurable with the `service_name` option.

**Comment by delner** [comment]
Can you provide a code sample that replicates the problem? What version of the library are you using?

**Comment by pawelchcki** [comment]
@undergroundwebdesigns Thank you for reporting this!

PR https://github.com/DataDog/dd-trace-rb/pull/430 addresses both default service name in docs, and ability to override it. It will be included in 0.12.1 release.

**Comment by delner** [comment]
Closing this, since it will be released as a part of `0.12.1`. Thanks again for your contribution!
