### ISSUE TITLE
Support for RestClient

### ISSUE THREAD

**Issue by rohitjangid** [DataDog/dd-trace-rb#422]
It would be useful to have RestClient support. 

For Reference: https://github.com/rest-client/rest-client

**Comment by delner** [comment]
Thanks for the suggestion, @rohitjangid ! We'll take a look at this, and perhaps add it to our backlog.

**Comment by delner** [comment]
This is going to be released with 0.14.0.rc1. Feel to check it out and let us know what you think! Closing this one out.
