### ISSUE TITLE
various integrations: Fail if incompatible

### ISSUE THREAD

**Issue by NobodysNightmare** [DataDog/dd-trace-rb#457]
I a currently setting up datadog for one of our applications. While configuring graphql I was irritated, that I got no metrics.

I checked the [source code](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/graphql/patcher.rb#L21) and found this:

```ruby
def patch
  return if ... || !configured? || ...
  ...
end

def configured?
  ... && Gem.loaded_specs['graphql'].version >= Gem::Version.new('1.7.9')
end
```

### Current behavior

What happens here is that the integration will silently not activate if there is no graphql or the version is not supported.

### Expected behavior

An exception is raised and tells me that what I am trying to do will not work.

I can understand, that for integrations like `rails`, which get activated implicitly this is not a desireable behaviour, since by default the gem should not crash anything.

However, for an integration that I manually activate it is rather frustrating to just notice that "it is not working" and then checking the source code to see, that a simple `bundle update` will solve my problem.

Update: I just noticed that the same behaviour applies to the **mongo** integration.

**Comment by delner** [comment]
The general doctrine to this point had been "don't break things", and to this end, the tracer has avoided raising exceptions except when absolutely necessary. I can see how this can fall short though, particularly if it doesn't help you debug your tracing setup.

Perhaps it'd make sense to log some kind of warning to logs. We do have a `debug` mode that prints out all kinds of additional information to console/logs that would be useful to this end. I'm just not sure if it actually prints a warning when an application attempts to activate an integration that isn't compatible (I suspect it doesn't.)

If you activated `debug` mode, and `debug` mode printed warnings whenever you tried to activate an integration that isn't compatible, would that be sufficient? Thoughts?

**Comment by NobodysNightmare** [comment]
I think logging would already greatly help here.

**Comment by delner** [comment]
I think we've actually done quite a bit to log errors and warn about instrumentation that fails to apply since this issue was first opened. Going to close it for now, but if you feel like this needs more work, please feel free to comment.
