### ISSUE TITLE
Excon from version 0.58 to make it work with fog-aws

### ISSUE THREAD

**Issue by argami** [DataDog/dd-trace-rb#461]
Hey Guys, 

I have seen the integration with excon 0.62  in the upcoming 0.13 version (0.13-dev) i'm very interested to use this, because of fog-aws (especifically fog-core).

But fog-core only allows version 0.58. I download the project and test it with version 0.58 and all the tests works fine.

Would you think is agood idea to PR this? or there is any reason to use the 0.62 version that might not be covered by the tests? @delner 

Thanks

PS. if is a good idea to PR im more than happy to do it.

**Comment by delner** [comment]
The 0.62 version we have listed in the documentation is the lower limit to which we'd officially provide support (e.g. bug fixes or additional features.)

However, I think in your case concerning Excon, the compatibility check in the code [doesn't enforce a version](https://github.com/DataDog/dd-trace-rb/blob/0.13-dev/lib/ddtrace/contrib/excon/patcher.rb#L41), meaning you should be able to run the tracing library with 0.58 in your application anyways, if you so chose.

The only caveat to this is that if there's a bug in `ddtrace` with Excon 0.58 that isn't present when using Excon 0.62 or greater, we wouldn't fix it ourselves. If anyone would like to submit PRs that are compatible with both versions that are older than 0.62, and ones newer than 0.62, I don't see why we wouldn't consider merging that in.

**Comment by argami** [comment]
Thanks for your quick answer i will do some tests with the 0.58 and review if that everything works fine (i only try with the tests). 

If i find anything i will send a PR 

Once more thanks!!
