### ISSUE TITLE
Support for memory allocation metrics and statistics

### ISSUE THREAD

**Issue by w32-blaster** [DataDog/dd-trace-rb#468]
In some cases it would be useful to see memory related metrics. It could help to find endpoints which are having higher memory footprint.

**Comment by delner** [comment]
Thanks for the suggestion @w32-blaster . We currently have an issue #312 open that tracks these memory stats. Can we add any additional considerations there and close this one?

**Comment by w32-blaster** [comment]
It's similar but that request is specific for garbage collection. Other tools support complete memory stats for requests, so you can see which are the more problematic requests/jobs in the app

**Comment by marcotc** [comment]
👋 I captured your feature request, did some research and added implementation details in #2164.
#2164 will serve as our implementation plan and actionable discussion around how to collect and report allocation metrics.
I'll close this issue, but this feature development can be followed #2164.
