### ISSUE TITLE
How to disable per environment?

### ISSUE THREAD

**Issue by shaneog** [DataDog/dd-trace-rb#509]
I can't find any documentation on how to disable the tracer per environment. For example, I only want it to run in `production`.

**Comment by shaneog** [comment]
Found that I need this in my initializer, outside the configure block: 
```ruby
Datadog.tracer.enabled = Rails.env.production?
```

**Comment by jarl-dk** [comment]
With the new API it is this snippet in the `initializers/datadog.rb`
```ruby
Datadog.configure do |c|
  c.tracing.enabled = Rails.env.production?
end
```

**Comment by jesuissuyaa** [comment]
I think it should be 

```ruby
Datadog.configure do |c|
  c.tracer.enabled = Rails.env.production?
end
```

trac**er** gives

```
`block in <main>': undefined method `tracing' for #<Datadog::Configuration::Settings:0x00007fb7040b8840> (NoMethodError)
Did you mean?  tracer
```

**Comment by ivoanjo** [comment]
@jesuissuyaa both are correct, in different cases 😉 

### For dd-trace-rb 1.x series (1.0 and above):

```ruby
Datadog.configure do |c|
  c.tracing.enabled = Rails.env.production?
end
```

### For dd-trace-rb 0.x series (0.54 and below):

(We highly recommend upgrading to the 1.x series!)

```ruby
Datadog.configure do |c|
  c.tracer.enabled = Rails.env.production?
end
```

**Comment by exoego** [comment]
For those using dd-trace-rb 2.x (now `datadog` gem):
```ruby
Datadog.configure do |c|
  c.tracing.enabled = Rails.env.production?
end
```
`.tracer` is now `.tracing`
