### ISSUE TITLE
Default service prefix

### ISSUE THREAD

**Issue by errriclee** [DataDog/dd-trace-rb#513]
ddtrace should support a prefix for service names.

We are having to make code like this, which is needed because we have multiple Rails applications. Having to specify the same prefix on every service seems unnecessary:

service_name = 'backend'

Datadog.configure do |c|
  c.use :active_record, service_name: "#{service_name}-active_record", orm_service_name: "#{service_name}-active_record"  
  c.use :rails,         service_name: "#{service_name}-rails"
  c.use :sidekiq,       service_name: "#{service_name}-sidekiq"
  c.use :redis,         service_name: "#{service_name}-redis"
  c.use :aws,           service_name: "#{service_name}-aws"
  c.use :faraday,       service_name: "#{service_name}-faraday"
  c.use :http,          service_name: "#{service_name}-net/http"
end

Optimally we would just specify something like:

Datadog.configure do |c|
  c.default_prefix 'backend'

  c.use :active_record
  c.use :rails
  c.use :sidekiq
  c.use :redis
  c.use :aws
  c.use :faraday
  c.use :http
end

Then, any time the service name is explicitly set, it overrides that prefix.

**Comment by watsonjon** [comment]
This would make our code so much easier! As of now we have to dig into the gem's source to ensure we set the correct option.

**Comment by delner** [comment]
I like this suggestion. We'll take a look at this, thank you!

**Comment by delner** [comment]
This is being worked on as a part of #542.

**Comment by delner** [comment]
Per the pull request:

> When this PR was opened, we intended to split a single Ruby application into many "services", both "internal" and "external", in order to provide layers of visibility on key metrics (e.g. Rack vs GraphQL vs Rails vs ActiveRecord and so on...)

> This approach has two major downsides; 1) it requires users to label each of their integrations with service names individually and to differentiate "internal" vs "external" integrations which complicates onboarding/setup, and 2) can create a mess of the service map in the Datadog UI... where users typically expect to see service = application, they were seeing potentially dozens of "services" instead.

> Since then, we've decided it would be better if each Ruby application had only one service name. Ideally in the near future, all spans produced by a Ruby app will receive this single service name via DD_SERVICE or configuration file. This pull request doesn't really jive with that direction, so I've decided to close this for now.

> If you still have other thoughts, please feel free to share them here. We'd like to make "service name" intuitive, fluid, and work for your application, and user feedback helps us do just that.
