### ISSUE TITLE
Distributed tracing: Typhoeus support

### ISSUE THREAD

**Issue by guizmaii** [DataDog/dd-trace-rb#527]
Hi,

We're using https://github.com/typhoeus/typhoeus to make our HTTP calls. Is it possible for you to support this lib ?

Jules

**Comment by delner** [comment]
Hey @guizmaii , sorry for the late reply! I'll take a look at this and try to get it on our schedule. Thanks for the suggestion!

**Comment by che-burashco** [comment]
@delner Is there any way you could take a look at https://github.com/DataDog/dd-trace-rb/pull/778? We (Wealthsimple) are facing the same issue as Jules and @al-kudryavtsev has done some work to add the support for Ethon

**Comment by delner** [comment]
@che-burashco Yeah, no problem, I'm going to try to get the priority bumped up on this. The PR looks more complete since last I saw it, so I'll check there if its ready for a review.

One thing that isn't clear to me; would that PR sufficiently cover the Typhoeus support requested here? I'm not familiar with the relationship between Typhoeus vs Ethon other than they stem from the same org.

**Comment by delner** [comment]
@guizmaii @che-burashco I was discussing #778 with @al-kudryavtsev and it sounds like that PR will add tracing to Ethon which, by proxy, should implement some basic tracing for Typhoeus, albeit not specialized instrumentation or details specific to Typhoeus. Tracing would be activated with `c.use :ethon`.

Would that PR be sufficient to address (close) this issue? Or are there other features you would consider necessary to consider this done?

**Comment by che-burashco** [comment]
That would be enough for us

**Comment by guizmaii** [comment]
Hi everyone, 

I'm not working anymore with Ruby so I can't help you here. HF :)

**Comment by delner** [comment]
We released Ethon tracing support with version 0.27.0, which should cover Typhoeus. Going to close this issue, but feel free to check that out, and re-open/comment here if need be!
