### ISSUE TITLE
Flaky CI build step for Ruby 1.9

### ISSUE THREAD

**Issue by pawelchcki** [DataDog/dd-trace-rb#567]
CI sometimes fails on ruby 1.9 build step that tries to fetch incompatible Rake version that doesn't support ruby 1.9.

```
Fetching rake 12.3.1
Installing rake 12.3.1
Gem::RuntimeRequirementNotMetError: rake requires Ruby version >= 2.0.0. The
current ruby version is 1.9.1.
An error occurred while installing rake (12.3.1), and Bundler
cannot continue.
Make sure that `gem install rake -v '12.3.1' --source 'https://rubygems.org/'`
succeeds before bundling.
```

**Comment by delner** [comment]
I've seen this a couple of times, too. I think this might have something to do with Bundler caching things weirdly, but I'm not totally sure. If I were debugging this, I'd look at Bundler first.

**Comment by delner** [comment]
Should be irrelevant now, as we don't support Ruby 1.9.
