### ISSUE TITLE
Support service mappings

### ISSUE THREAD

**Issue by drobert** [DataDog/dd-trace-rb#585]
If you look at the configuration options for the [java tracer](https://docs.datadoghq.com/tracing/setup/java/#configuration), there is support for the notion of "service mappings". That is, the runtime may instrument a particular service as "foo" but want to report it to datadog as "bar".

It would be helpful to have this support built into the tracer.

(Truthfully, it feels odd that tracers are responsible for this rather than this being a base capability of the datadog agent itself, but as it stands this is a feature the java tracer has that the ruby tracer does not.)

**Comment by delner** [comment]
Can you be a bit more specific as to how this could apply to Ruby? Any examples where it might benefit from this?

As it stands right now, many integrations support (what I think is) the equivalent of service mapping, particularly in the database service name case. e.g. [ActiveRecord settings per database](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#active-record) or [different settings for Sequel databases](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#sequel). These are done on an integration by integration basis currently. We're working towards greater consistency, likely mirroring what we have for ActiveRecord.

**Comment by delner** [comment]
Hey @drobert , we took a look at this, and it sounds like the team has a better alternative in the works, so I don't think we're going to pursue this particular service mapping. We'll update you when we have that alternative ready!

Please feel free to leave a comment if you have any thoughts!
