### ISSUE TITLE
False positive "ActionView::MissingTemplate" when using devise

### ISSUE THREAD

**Issue by frsantos** [DataDog/dd-trace-rb#632]
We have a lot of error traces in our APM like this:

> ActionView::MissingTemplate: Missing template devise/sessions/create, devise/create, devise_application/create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :axlsx, :coffee, :haml, :jbuilder]}. Searched in: * "/home/user/releases/20181112170058/app/views" * "/home/user/shared/bundle/ruby/2.5.0/gems/kaminari-core-1.1.1/app/views" * "/home/user/shared/bundle/ruby/2.5.0/gems/devise-security-0.11.0/app/views" * "/home/user/shared/bundle/ruby/2.5.0/gems/devise-4.4.1/app/views"

These traces correspond to correct logins (`Devise::SessionsController.create`) with the standard `devise` gem. In the stacktrace there is a call to the method `ActionController::Responder#to_html` in the gem `responders` (used by the `devise` gem):

```
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/path_set.rb:46:in `find'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/lookup_context.rb:116:in `find'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:38:in `determine_template'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/renderer/template_renderer.rb:8:in `render'
/home/user/shared/bundle/ruby/2.5.0/gems/ddtrace-0.14.1/lib/ddtrace/contrib/rails/core_extensions.rb:45:in `block (2 levels) in render_with_datadog'
/home/user/shared/bundle/ruby/2.5.0/gems/ddtrace-0.14.1/lib/ddtrace/contrib/rails/core_extensions.rb:96:in `with_datadog_span'
/home/user/shared/bundle/ruby/2.5.0/gems/ddtrace-0.14.1/lib/ddtrace/contrib/rails/core_extensions.rb:45:in `block in render_with_datadog'
/home/user/shared/bundle/ruby/2.5.0/gems/ddtrace-0.14.1/lib/ddtrace/tracer.rb:296:in `trace'
/home/user/shared/bundle/ruby/2.5.0/gems/ddtrace-0.14.1/lib/ddtrace/contrib/rails/core_extensions.rb:41:in `render_with_datadog'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/renderer/renderer.rb:23:in `render'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:103:in `_render_template'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/home/user/shared/bundle/ruby/2.5.0/gems/actionview-5.1.4/lib/action_view/rendering.rb:83:in `render_to_body'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/abstract_controller/rendering.rb:24:in `render'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:36:in `render'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/home/user/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/user/shared/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/home/user/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
/home/user/shared/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:43:in `render'
/home/user/shared/bundle/ruby/2.5.0/gems/wicked_pdf-1.1.0/lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
/home/user/shared/bundle/ruby/2.5.0/gems/wicked_pdf-1.1.0/lib/wicked_pdf/pdf_helper.rb:27:in `render'
/home/user/shared/bundle/ruby/2.5.0/gems/responders-2.4.0/lib/action_controller/responder.rb:238:in `default_render'
/home/user/shared/bundle/ruby/2.5.0/gems/responders-2.4.0/lib/action_controller/responder.rb:170:in `to_html'
/home/user/shared/bundle/ruby/2.5.0/gems/responders-2.4.0/lib/action_controller/responder.rb:163:in `respond'
/home/user/shared/bundle/ruby/2.5.0/gems/responders-2.4.0/lib/action_controller/responder.rb:156:in `call'
/home/user/shared/bundle/ruby/2.5.0/gems/responders-2.4.0/lib/action_controller/respond_with.rb:211:in `respond_with'
/home/user/shared/bundle/ruby/2.5.0/gems/devise-4.4.1/app/controllers/devise/sessions_controller.rb:23:in `create'
[...]
```

The method is this: https://github.com/plataformatec/responders/blob/master/lib/action_controller/responder.rb#L170

As you can see, the exception is captured and handled, however datadog shows the trace as error. The session login is working as expected, no error is shown to the user, in the application log or reported from Rollbar.

**Comment by delner** [comment]
I see. What is the deepest span that the error appears on? `rails.render_template`? 

This is a little tricky since it's hard to configure the trace to whitelist an `ActionView::MissingTemplate` error under this very specific set of circumstances.

I'm thinking if we wanted to solve this with a code change, there are two strategies that could help with this. Either 1) add a more generalized exception whitelisting behavior (which I don't how this would apply or fix this issue) or 2) add an integration-specific patch/hook for this `responders` gem that modifies the behavior of this part of the trace. Of these, number 2 seems the most preferable way as its the most direct means of solving this.

However, there might be a way to circumvent this via pipeline configuration without needing to patch the `ddtrace` gem, at least in the interim. If you can identify the spans by name and perhaps error class, you could unset the error flag on the span so they don't appear as an error in the UI.

Want to take a look [at this](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#processing) and tell me if that helps address the issue sufficiently? Otherwise I'd be happy to consider suggestions for how to whitelist this kind of error.

**Comment by frsantos** [comment]
Thanks @delner. 

Yes, in fact this is the first time I've seen this pattern (try to render, capture, do other things), so I may workaround with what you suggest. I'll take a look in some days, when I'm not so busy.

**Comment by ryanspiffy** [comment]
@delner We recently started using DataDog and also see this issue spamming our logs as errors.  At first, I thought it was something we needed to fix that had possibly gone unnoticed with our last APM solution, but it seems the error is being handled by Devise correctly.  I'm not sure I understand your suggestion to handle the issue with a pipeline configuration. Could you provide some additional guidance?

**Comment by delner** [comment]
@ryanspiffy The reference to the pipeline is [the link](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#processing-pipeline) I shared above.

**Comment by frsantos** [comment]
Sorry, I completely forgot about this.

I added the following snippet after the Datadog initializer to remove the invalid trace, and it's been working fine for us for quite some time now:

```ruby
Datadog::Pipeline.before_flush(
  # Devise (actually the responders gem) tries to render a partial, and if it doesn't exist, it redirects. However,
  # Datadog thinks there is a missing partial, and so adds a span with error to the trace. This SpanFilter removes that
  # erroneous span. See https://github.com/DataDog/dd-trace-rb/issues/632
  Datadog::Pipeline::SpanFilter.new do |span|
    span.status == Datadog::Ext::Errors::STATUS &&
      span.get_tag(Datadog::Ext::Errors::TYPE) == 'ActionView::MissingTemplate' &&
      span.get_tag(Datadog::Ext::Errors::MSG)&.match('Missing template devise/sessions/create')
  end
)

```

**Comment by delner** [comment]
This issue is a bit older and seems to have a suitable workaround. If necessary we may revisit this in the future, but I'm going to close this for the time being.
