### ISSUE TITLE
What is Scout's ruby gem doing right?

### ISSUE THREAD

**Issue by incorvia** [DataDog/dd-trace-rb#694]
Just getting started with DataDog APM, installed dd-trace-rb and was a little disappointed that so little was available out of the box. I found this article about [DataDog vs Scout](https://scoutapp.com/blog/datadog-vs-scout-which-is-right-for-you) and it made me wonder, does anyone know why Scout's gem is able to get such rich metrics about each method call within action? Is there anyway I can replicate this easily with dd-trace-rb?

**Comment by incorvia** [comment]
Seems its related to ScoutProf https://github.com/scoutapp/slate_apm_help/blob/master/source/includes/_reference.md#scoutprof-faq

And seems their special sauce is that they do a sample every 1ms that produces a backtrace and they batch process those on the server to compare time spent in different methods. Doesn't seem their solution strictly involves their gem and also involves server processing.. hmm

**Comment by delner** [comment]
Hey @incorvia, I know this response comes long after your original question. From what you're describing, to me, it sounds like the difference between tracing and profiling.

What Scout is doing (sampling every 1ms to produce a backtrace) is what's considered profiling; the advantage of doing so, is as you said, you get richer output. The downside however is it cannot capture every operation or request, as it is merely a statistical sum.

Tracing is different, in that each instrumented operation always produces spans, and those spans can be tagged with rich data specific to that occurrence allowing the developer to look at every request. Downside is you typically cannot/do not want to implement tracing on every method as it can be very expensive to application performance.

As these strategies are largely considered complementary (think "right tool for the job"), Datadog offers both tracing and profiling which you can employ independently or cooperatively within the same application. There should be more details within our readme if you're interested.

As this is an old question, and hopefully this should now be answered, I'm going to close this issue. Please feel free to leave any further questions you may have here!
