### ISSUE TITLE
Extend trace IDs to 128-bit for OpenCensus compatibility with distributed traces

### ISSUE THREAD

**Issue by porty** [DataDog/dd-trace-rb#698]
When working with compatibility with other tracing systems, I've found that Datadog's 64-bit trace IDs cause issue when working with OpenCensus' 128-bit trace IDs. Outgoing request trace information is OK (as 64-bit trace IDs can be extended to 128-bit) however incoming request traces cannot be continued. I see the Go OpenCensus implementation silently drops half the trace ID: https://github.com/DataDog/opencensus-go-exporter-datadog/blob/20ec6f43ee69811290ba6fc6f0fc64f8a87f5d42/span.go#L50

There would be compatibility issues with such a change - this would probably require a secondary header with the 128-bit trace ID and the existing 64-bit trace ID as a legacy header.

Changing the msgpack format would also be a change across multiple codebases - dd-trace-rb is probably just a downstream consumer of such a change, and this issue might be better placed in another repo.

**Comment by delner** [comment]
Right, it would take a lot of changes in the Datadog repos or infrastructure to make this happen; maybe it will eventually, but unlikely to be anytime soon.

That said, leveraging your idea of tagging secondary headers could be implemented as an extension to this Datadog library; it could come in the form of a gem like `ddtrace-opencensus` or the like. In such a gem, you could inject a module into our own distributed tracing implementation such that it would both read and write this header where appropriate. That way you could add support for OpenCensus as it passes through a Ruby application instrumented with `dd-trace-rb`.

We've done something similar in this repo with OpenTracing, it just wasn't enshrined as an official gem, but more or less behaves this way. I don't see why something like this couldn't also exist to improve interoperability between Datadog and OpenCensus (at least with this library.)

**Comment by delner** [comment]
As this is both old and unlikely to be changed anytime soon, I'm going to close this for the time being. Please feel free to comment if you have any additional thoughts about this issue.
