### ISSUE TITLE
Apply AWS integration for service level gems

### ISSUE THREAD

**Issue by alksl** [DataDog/dd-trace-rb#707]
Configuring the AWS integration when using service level gems e.g. `aws-sdk-dynamodb` don't work since the integration only checks for the presence of the `aws-sdk` gem and the integration will never be patched. 
See 
https://github.com/DataDog/dd-trace-rb/blob/ff0bad458fab522e0566d279cd6f2ef519ade32c/lib/ddtrace/contrib/aws/integration.rb#L14-L16

A possible solution can be to check for either the `aws-sdk` gem or `aws-sdk-core`.

**Comment by alksl** [comment]
Using this workaround at the moment which will force patch this integration.

```ruby
Datadog.registry[:aws].patcher.patch
```

**Comment by delner** [comment]
This should be resolved with 0.23.2. Closing for now. Let me know if this is still an issue!
