### ISSUE TITLE
Improve logging and active correlation when Lograge enabled

### ISSUE THREAD

**Issue by nic-lan** [DataDog/dd-trace-rb#727]
Hi, 

I found a way to improve a bit ( in my opinion 😂  ) the logging on STDOUT.
I opened a [PR on lograge](https://github.com/roidrage/lograge/pull/281) too, but no answer there..

Since the changes were introduced to deal with active-correlation and datadog agent fetching logs from STDOUT I repost in here.
Maybe someone find this interesting and we add this to the dd-trace-rb documentation

----

#### Description

This assumes a Lograge::Formatters::LogstashRaw formatter class within the list of the existing ones in lograge formatters as suggested in this [PR](https://github.com/roidrage/lograge/pull/281) because sometime it can be convenient to pass around Logstash::Event objects in the log stack better than pure json objs

In particular Lograge::Formatters::LogstashRaw is responsible for formatting the lograge payload as LogStash::Event.
    
It can be useful when lograge logs are meant to be integrated with a custom rails logger formatter,
where for example we want to add logger custom options.
In the above case can be convenient to postpone the `event.to_json` ( as it is in the child class Logstash ) when the actual `call` of the logger formatter is happening and not before that moment to avoid Json parse back.
    
Example: Custom Rails Logger Formatter
 
```ruby
#  config/production.rb
Rails.application.configure do
  ...
  config.log_formatter = FooFormatter.new
  ...
end
``` 
 
```ruby
#  foo_formatter.rb
class FooFormatter < ActiveSupport::Logger::SimpleFormatter
  # This method is called everytime a log event happens
  def call(severity, timestamp, progname, message)
    return super if message.is_a? String

    # those are the custom options we want to add to each log event not only lograge ones
    message.merge(
      # Adds IDs as tags to log output
      :dd => {
        :trace_id => correlation.trace_id,
        :span_id => correlation.span_id
      },
      :ddsource => ["ruby"]
     )
    "#{message.to_json}\n"
  end
end
```
 So now when logging is happening:
```ruby
Rails.logger(message: "An Amazing Log")
```
=>
```json
{
  "message": "An Amazing Log",
  "dd": {
    "trace_id": "1234567",
    "span_id": "abcdef"
  },
  "ddsource": ["ruby"],
  "level": "INFO"
}
```

At the same time the custom options will be applied to the lograge log too,
without the need of passing any custom option to the lograge configuration

```json
{
  "method": "POST",
  "path": "/api/v1/my_path",
  "controller": "Api::V1::MyPathController",
  "action": "create",
  "status": 200,
  "params": {
    "one": "param",
    "another": "param"
  },
  "message": "[200] POST /api/v1/my_path (Api::V1::MyPathController#create)",
  ...
  "dd": {
    "trace_id": '1234567',
    "span_id": 'abcdef'
  },
  "ddsource": ["ruby"],
  "level": 'INFO'
  ...
}
```

hopefully you will find this useful.

**Comment by marcotc** [comment]
👋 @nic-lan, I'm going through some old issues today, pardon my tardiness.

I looked at the upstream PR you linked and one question I have is if what you are proposing with `LogstashRaw` can't be achieved today with `Lograge#custom_options`?

For example, our tracer log correlation can be manually configured like this ([from our docs](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#manual-lograge)):
```ruby
lograge.custom_options = lambda do |event|
  # Retrieves trace information for current thread
  correlation = Datadog.tracer.active_correlation

  {
    # Adds IDs as tags to log output
    :dd => {
      # To preserve precision during JSON serialization, use strings for large numbers
      :trace_id => correlation.trace_id.to_s,
      :span_id => correlation.span_id.to_s,
      :env => correlation.env.to_s,
      :service => correlation.service.to_s,
      :version => correlation.version.to_s
    },
    :ddsource => ["ruby"],
    :params => event.payload[:params].reject { |k| %w(controller action).include? k }
  }
end
```

Unrelated, but we've shipped automatic log correlation injection for Rails, which encapsulates this logic behind the scenes:
```ruby
Datadog.configure do |c|
  c.use :rails, log_injection: true
end
```

**Comment by nic-lan** [comment]
hi @marcotc 

thank you for coming back to me ( after some time 😂 )

To be honest i forgot about this issue.

That been said since you are asking if it can be achieved today with the `Lograge#custom_options` i would say that one limit of Lograge is that it would not work for custom Log calls but only for the logs shipped within the lograge logic, would it ?

for example:
```
def my_method
  Rails.logger.info('My custom message)
end
```

If i remember correctly this log call would be printed out without the dd correlation params and therefore it would not be tracked successfully in the same trace.

Another limit of the Lograge is that if you don't have `lograge` gem in your project then well.. you don't have the custom_options :-)

I would say that a closer solution to my original issue description is the rails feature log_injection.
 If i understand well what you say that is going exactly to do what i was suggesting and then i would say that this issue is not relevant anymore and can probably be closed.

That been said i wonder if for example you have the log_injection feature available also for a generic ruby project like

```ruby
Datadog.configure do |c|
  c.log_injection = true
end
```
 
because otherwise someone might still need to define a custom logger formatter as in the example i posted originally in order to have the the logger printing out with the right correlation params.

**Comment by ericmustin** [comment]
@nic-lan For a generic ruby project you'll have to configure your logger manually. There are plenty of examples in our documentation that should act as a guide broadly speaking.

-  https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#trace-correlation

The simple reason why manual config is needed for a generic ruby project is that, as library authors, afaik we just simply lack a reasonable hook for when we could safely monkey patch and auto inject the trace correlation details. Rails, otoh, provides these hooks for us to do so.

Does that help clarify things?

**Comment by marcotc** [comment]
👋 @nic-lan, super late ping, but I was wondering if this issue is still relevant to you? We have official Lorage integration today, for both Rails and plain Ruby apps.

I understand if this is not related to any of your active projects anymore.

**Comment by ivoanjo** [comment]
We haven't heard back in a bit, so I'm going to go ahead and close this one :)
