### ISSUE TITLE
Question: Active Record postgres db events 

### ISSUE THREAD

**Issue by MZic** [DataDog/dd-trace-rb#780]
Hi all, 

I hope you can help me with this. I've set up ddtrace on my application as following:

```
Datadog.configure do |c|
  c.use :rails
  c.use :sidekiq
  c.use :active_record, { analytics_enabled: true }
end
```

I'm getting loads of events for Postgres service, by I would like to be able to log only the query slower than X. Is there any way to do it?
I know there is the sampler, but as far as I could understand it samples everything, and by the way, I'm not sure if it is going to be reliable for my incident detection.

I've also tried to remove the active_record integration, but I still get all the query logged on my APM. Any reason for that? 

Thank you very much

**Comment by delner** [comment]
Hey @MZic! In the UI for the Postgres service I think you should be able to filter the traces to those with a duration longer than X time. I would not recommend filtering those from the Ruby side, since its a bit more inflexible and doing so would skew statistics for your service overall (change averages, etc.)

Its likely that you're receiving ActiveRecord traces because `use :rails` is a meta-integration that activates tracing for ActionPack, ActionView and ActiveRecord simultaneously. Currently I don't think there's a way of deactivating ActiveRecord if `use :rails` is used, but we're working on a refactor that will eventually make this possible.

**Comment by MZic** [comment]
Hi @delner thank you for your reply! Yes, I know I can filter in the UI, my problem is that I'm receiving more than 1M events a day for queries like `select * from table where id in (?)`, and in DataDog I pay 1.27$ for million. I think you can imagine how the cost is going to bloat pretty fast for.

>Its likely that you're receiving ActiveRecord traces because use :rails is a meta-integration that activates tracing for ActionPack, ActionView and ActiveRecord simultaneously.

Yeah I suspected that, but so what is the point of having ` c.use :active_record, { analytics_enabled: true }` ?

**Comment by delner** [comment]
Okay, understood. If your goal is to throttle down the number of traces coming out of your application, we can do that; I think the best way to do that would be using the processing pipeline, which can filter out traces based on custom criteria. We have an example for this [here](https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#filtering).

Regarding ActiveRecord, the `c.use :active_record` is mostly for the benefit of users who use ActiveRecord without Rails, or want to reconfigure certain features for ActiveRecord. The plan is to overhaul the `c.use :rails` command such that you can explicitly exclude the activation of ActiveRecord.

**Comment by MZic** [comment]
Ah that's is cool, thank you very much.

So do you know if there is any way I can get the latency from the event itself? 
So I can filter by that.

**Comment by delner** [comment]
If you'd like to drop just the Postgres spans whose latency is under a certain limit, you can use this span filter basically anywhere after you `require 'ddtrace'`, but with different criteria.

You'd probably want to check the span name (to see if its a DB span) and the difference between its start and end times, then return `true` if you want to filter it out. The trace will be persisted, but the span should be removed from the trace.

**Comment by MZic** [comment]
Perfect thank you very much for your answers!

**Comment by delner** [comment]
@MZic By the way, I may have misinterpreted the intent here.

If your goal was to reduce the volume of billable events for search & analytics (as opposed to the raw volume of traces), you have some other options to do that without dropping spans from traces.

 - Setting `analytics_enabled: false` for an integration will prevent the sampling tag for search and analytics from being applied (meaning they won't be available/billed for S&A.)
 - Setting `analytics_sample_rate` for an integration to a value less than `1.0` will change the sampling rate for search and analytics, allowing you to still have some S&A events for that integration but with reduced volume.
 - As an admin/owner, there should be a control in the settings UI to change the sample rate by env/service.

However, none of the above options will allow you to specifically target the sample rate for spans of a particular duration, as you had requested before. In that case, you could use `Datadog::Pipeline::SpanProcessor` (as opposed to the filter) to remove the sample rate metric `_dd1.sr.eausr` from the span, allowing the span to be preserved but excluded from S&A.
