### ISSUE TITLE
Feature request: auto detect ActiveRecord on Sinatra app

### ISSUE THREAD

**Issue by cabello** [DataDog/dd-trace-rb#84]
Hi, we are integrating some Sinatra apps, they all use ActiveRecord for database connection I see in the source code instrumentation for ActiveRecord on Rails apps, it would be awesome to have similar kind of detection on Sinatra apps.

**Comment by ufoot** [comment]
Indeed, it would be relevant to have AR work transparently when used from Sinatra.

**Comment by ufoot** [comment]
Available in https://github.com/DataDog/dd-trace-rb/releases/tag/v0.6.2 , thanks again for your work!
