### ISSUE TITLE
Sidekiq tracer middle reconfigures already-configured datadog tracer

### ISSUE THREAD

**Issue by sj26** [DataDog/dd-trace-rb#85]
Using sidekiq in a rails app, I have already configured datadog tracer in an initializer:

```ruby
# config/initializers/ddtrace.rb
Rails.configuration.datadog_trace = {
  enabled: !Rails.env.production?
}
```

When I add the sidekiq tracer middleware to my sidekiq config without any options:

```ruby
# config/initializers/sidekiq.rb
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    require "ddtrace/contrib/sidekiq/tracer"
    chain.add Datadog::Contrib::Sidekiq::Tracer
  end
end
```

Then `Datadog.tracer` is implicitly reconfigured with sidekiq defaults [by the middleware's initializer](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/sidekiq/tracer.rb#L31-L35). I found this very surprising. I don't expect a sidekiq middleware's initializer to mutate the global state of my application.

I had to override this back to my rails configuration with:

```ruby
    chain.add Datadog::Contrib::Sidekiq::Tracer,
      enabled: Rails.configuration.datadog_trace.fetch(:enabled)
```

Perhaps this initializer should only set those values on the tracer if the options are passed (non-nil), similar to the `Datadog::Tracer#configure` method?

**Comment by palazzem** [comment]
Hello @sj26 ! yes actually we haven't released the Sidekiq integration because we still need to fix the interaction between the library and Rails. I will keep you updated about this issue.

Thanks for reporting that!

**Comment by sj26** [comment]
@palazzem sorry, we're probably jumping the gun a bit! But we're wanting to give Datadog APM a good go while we're still in trial which means turning on all the bells and whistles and getting it recording and tagging spans across the board. So far it's pretty amazing to see every request and job popping up   live as a trace, fully tagged!

**Comment by palazzem** [comment]
@sj26 eheheh thank you! actually I'm working on https://github.com/DataDog/dd-trace-rb/pull/86 that solves some problems with the Sidekiq integration. After that I'll prepare another PR for your use case that makes sense to me, and that must be supported easily without any effort from your side :)

**Comment by palazzem** [comment]
Hello @sj26 ! https://github.com/DataDog/dd-trace-rb/pull/87 should fix this issue. Actually we're inheriting the Rails configuration if it's available, so your code should work without any further change. Let me know if you think it will not fix the problem.

Closing the issue for now.

**Comment by palazzem** [comment]
Hello @sj26 ! we've released a new version of the gem: https://github.com/DataDog/dd-trace-rb/releases/tag/v0.5.0

Let us know if it's working for you!

**Comment by sj26** [comment]
@palazzem sorry for the delay, we're just updating now. Looks good — thanks! :+1:
