### ISSUE TITLE
Set template/partial name as the resource for rails.render_template and rails.render_partial 

### ISSUE THREAD

**Issue by djmb** [DataDog/dd-trace-rb#855]
The action_view integration doesn't set a resource for the `rails.render_template` and `rails.render_partial` spans. This means that everything gets lumped together in the span summary.

It would be useful it it used the template or partial name as the resource.

**Comment by delner** [comment]
@djmb Hmmm, I think you're right; I don't see any setting of the resource in our ActionView instrumentation. We probably should change that, thanks for the suggestion!

**Comment by delner** [comment]
Just a heads up @djmb, we addressed this in #881 which was merged to master and should roll with the next release `0.31.0`.

Thanks again for the suggestion!

**Comment by marcotc** [comment]
Hi @djmb, we've just released this feature in 0.31.0.

Give it a try and let us know if you have any further feedback!
