### ISSUE TITLE
`analytics_enabled` ignore on active_record integrations with per database connections

### ISSUE THREAD

**Issue by djmb** [DataDog/dd-trace-rb#860]
If you have config like:
```
Datadog.configure do |c|
  c.use :rails
  c.use :active_record, describes: :foo_db, service_name: :foo_db, analytics_enabled: true
end
```
then analytics are not enabled on `:foo_db`.

This does enable analytics on `:foo_db`:
```
Datadog.configure do |c|
  c.use :rails
  c.use :active_record, analytics_enabled: true
  c.use :active_record, describes: :foo_db, service_name: :foo_db
end
```

**Comment by delner** [comment]
Looks like this might be the case because it derives the setting from `Datadog.configuration[:active_record]` which is the integration-level default, not the DB-specific settings. I think we could easily change this though to use the DB-specific settings.

Thanks for the report @djmb! :+1:

**Comment by marcotc** [comment]
`analytics_enabled` has been [deprecated for a few years.](https://docs.datadoghq.com/tracing/legacy_app_analytics/)

I'm going to close this issue as this option is no longer officially supported.
