### ISSUE TITLE
Prefer to use `Module#prepend` for wrappers.

### ISSUE THREAD

**Issue by ioquatix** [DataDog/dd-trace-rb#862]
A user is trying to combine dd-trace with scout apm https://github.com/scoutapp/scout_apm_ruby/issues/309

Because you are using legacy style method alias wrappers, it's failing.

https://github.com/DataDog/dd-trace-rb/blob/aac77842aeff0deafab97701ef8a0b4de38a2000/lib/ddtrace/contrib/action_view/instrumentation/template_renderer.rb#L79-L80

You should prefer `Module#prepend` for wrapping methods, not only is it more efficient, it's simpler and more composable. It's supported in Ruby 2.0+

**Comment by delner** [comment]
Yeah, we actually did start switching over to `prepend`, as you can see in our [patcher code](https://github.com/DataDog/dd-trace-rb/blob/aac77842aeff0deafab97701ef8a0b4de38a2000/lib/ddtrace/contrib/action_view/patcher.rb#L31). This kind of method aliasing is only for Rails 3.0, so users with Rails versions newer than that should not have this issue. Perhaps the Rails 3.0 patch is applying when it shouldn't if this is happening on any newer versions.

**Comment by w32-blaster** [comment]
@delner We do use rails 5 and seeing the error from the original issue. From which version of ddtrace is the patcher code available? We have ddtrace version 0.26

**Comment by delner** [comment]
@w32-blaster Looks like our Rails refactor landed in 0.27.0 which changed how this was patched. I would recommend updating to 0.29.0 and see if the problem still exists there, then I think we can investigate this further.

**Comment by delner** [comment]
@w32-blaster I think our latest Rails code should have replaced the old behavior with `prepend` and addressed the issue. I'm going to close this for now, but please feel free to update and try it out and let us know if it's working.
