### ISSUE TITLE
Feature request: net/http instrumentation should add trace-id and span-id

### ISSUE THREAD

**Issue by cabello** [DataDog/dd-trace-rb#89]
Hi, by checking the docs for [trace](http://pypi.datadoghq.com/trace/docs/#distributed-tracing) and the gem source code it seems that the `net/http` instrumentation does not add the headers for parent trace nor parent span.

It would be awesome to have that as an configurable option, so it could be turned on and we could get multi-service traces working out of the box by using DataDog official libraries.

The way I see, the necessary tasks for this feature to work nicely:
- `net/http` instrumentation must add http headers `x-ddtrace-parent_trace_id` and `x-ddtrace-parent_span_id`.
- Rails instrumentation should offer a middleware for connecting to a parent trace/span.
- Sinatra instrumentation should offer a middleware for connection to a parent trace/span.

Thoughts?

**Comment by palazzem** [comment]
Thank you @cabello for this feature request! Actually the `net/http` integration traces only the HTTP call but we were thinking about having this feature "somewhere", maybe not enabled by default. We will keep you updated about the progress.

Thanks!

**Comment by ufoot** [comment]
Implemented in #151
