### ISSUE TITLE
Sidekiq w/ ActiveJob reports wrong resource.

### ISSUE THREAD

**Issue by tpendragon** [DataDog/dd-trace-rb#90]
All my Sidekiq metrics are reporting the resource as `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper`.

**Comment by tpendragon** [comment]
This should be pretty straight-forward to fix, just need to check for the 'wrapped' option in the job arguments: https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L22

**Comment by ufoot** [comment]
FYI @tpendragon I applied the patch you suggested, and it works well. Will very likely ship in our next stable release (coming soon). See https://github.com/DataDog/dd-trace-rb/pull/94 for details.
