### ISSUE TITLE
Trace ID and Span ID with Configurable Prefix or Suffix

### ISSUE THREAD

**Issue by allcentury** [DataDog/dd-trace-rb#905]
[`DataDog::Utils.next_id`](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/utils.rb#L15) produces a random value from 0 to 2**63.

Generally, this produces a large value because of the integer distribution but we are experiencing issues because a lot of these random values resemble [Credit Card Numbers](https://en.wikipedia.org/wiki/Payment_card_number).  We have extensive filtering to prevent such numbers from leaving our system and therefore, we mask trace id's thinking they are credit card numbers. 

Would you be open to a PR that allows for a configurable suffix or prefix, allowing us to do something like:

```ruby
Datadog.configure do |c|
  c.trace_id_prefix = 9999
end
```

I assume these have to remain integers but if not, I'd also be happy to add a PR allowing trace_id's to be `uuid`'s.

**Comment by delner** [comment]
Hmmmm, interesting edge case. How does this CCN mechanism accidentally catch/filter these trace IDs? Through logging? HTTP? Something else?

I think the problem on our end with adding prefixes is that trace IDs while random are not arbitrary, and the type/length/range is meant to be consistent with other tracing paradigms (whose standards we don't control.) In this way, the agent can't arbitrarily accept any value as a trace ID. So I don't think a prefix/UUID will work.

Open to seeing if there's some other creative solution we can accommodate your case with.

**Comment by delner** [comment]
Crazy thought that might not work with your filtering mechanism, but perhaps you could patch the `DataDog::Utils.next_id` in your application to return an instance of `TraceID = Class.new(Integer)`, which you could then add a type check to your filter e.g. `skip if number.kind_of?(TraceID)`.

**Comment by delner** [comment]
Also my colleague @brettlangdon had a great consideration as well; your Ruby application might be one step in a larger distributed trace, and its possible it isn't the service from where the trace originates. In that case, the trace ID would be generated by the originating service and passed in to this one, and serialized.

Thus, the prefix cannot work since it must match the trace ID generated elsewhere. It's possible it could work with the above hack I suggested, but you would also have to modify our distributed tracing code which generates `Context` objects for traces to coerce the trace ID integer to `TraceID` as well.

**Comment by allcentury** [comment]
@delner / @brettlangdon - thanks for suggestions and comments, I hadn't thought of the distributed tracing piece.  I'd prefer not to monkey patch for obvious reasons, do you think instead there's a possibility of having a token/trace id generator as an optional dependency injection?  That way, all of our applications can use a common library but the API is public for others to use.  Something like:

```ruby
Datadog.configure do |c|
  c.trace_id_generator = -> { OurGem.generate_unique_trace_id }
end
```

then in `next_id`:

```ruby
def self.next_id
  reset! if was_forked?

  if config.trace_id_generator
    config.trace_id_generator.call
  else
    @rnd.rand(Datadog::Span::MAX_ID)
  end
end
```

I don't know how that fits into your comment about `Context/TraceID` but if you can point me in the right direction, I'm happy to give it a shot.  Thanks again

**Comment by delner** [comment]
Having a generator you can swap out like this as a facet of the tracer could be reasonable change, but I think we'd have to have a reason for generating a different kinds of IDs. Currently there's only one acceptable form of ID (the Datadog format we accept and use in the agent) and the tracer must emit this form, so allowing different forms to be substituted isn't really a benefit for most, but more of a risk if improperly used.

I lean away from implementing an API like this for those reasons right now. But I won't say "never" as its possible we might permit other forms IDs in the future, at which point this might be relevant change. I'll check to see if there's any other reason we might want to do this, and keep it in mind if things change.

Also FWIW, doing a `Datadog::Utils.prepend(OurGem::IdGeneration)` is very likely to be stable, if you wanted to exercise that option in the mean time.

Regarding context/distributed tracing, you'd also need to patch this distributed tracing code which is responsible for decoding trace IDs from distributed tracing headers:

https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/distributed_tracing/headers/headers.rb#L31

**Comment by delner** [comment]
Going to close this for now as we don't intend on implementing this. Please feel free to comment if you like.
