### ISSUE TITLE
Sidekiq middleware throws an error if no options are passed.

### ISSUE THREAD

**Issue by tpendragon** [DataDog/dd-trace-rb#91]
If I do as the docs suggest and do this: 

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add(Datadog::Contrib::Sidekiq::Tracer)
  end
end
```

it tells me that it expected 1 argument for Tracer and got 0. If I pass some argument to Tracer as in the next part of the docs, it works. I think Tracer just needs adjusted so it looks like so:

```ruby
      class Tracer
        def initialize(options = {})
```

**Comment by ufoot** [comment]
Thanks for the report!

**Comment by ufoot** [comment]
I think https://github.com/DataDog/dd-trace-rb/pull/93/ should fix this.

**Comment by gingerlime** [comment]
When is 0.6.0 due out? I was told Monday by your support... looking forward to getting this fix out officially.

**Comment by ufoot** [comment]
It should be building right now, release in process.
