### ISSUE TITLE
 undefined method `stop' for #<Datadog::SyncWriter ...

### ISSUE THREAD

**Issue by Yurokle** [DataDog/dd-trace-rb#914]
Hello. I'm seeing the exception below when I'm running some rake tasks.
```
Traceback (most recent call last):
	1: from /Users/ynaidyon/.rvm/gems/ruby-2.6.5/gems/ddtrace-0.31.0/lib/ddtrace.rb:33:in `block in <module:Datadog>'
/Users/ynaidyon/.rvm/gems/ruby-2.6.5/gems/ddtrace-0.31.0/lib/ddtrace/tracer.rb:53:in `shutdown!': undefined method `stop' for #<Datadog::SyncWriter:0x00007fb29f827680> (NoMethodError)
```

It looks like `Datadog::SyncWorker` doesn't implement `#stop` method which `Tracer#shutdown!` is trying to call here: https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/tracer.rb#L53

**Comment by marcotc** [comment]
Thank you for the issue report @Yurokle!

I was able to reproduce and create a pull request to address this issue:  #915

**Comment by Yurokle** [comment]
Thanks @marcotc !
