### ISSUE TITLE
Test failures for POST to v0.4/traces

### ISSUE THREAD

**Issue by andrewthauer** [DataDog/dd-trace-rb#916]
I've updated to `ddtrace '0.31.0'` and am now seeing rspec test failures on calls to `/v0.4/traces`.

I could stub this request, but we have multiple projects using it. So, I'm wondering if this is intended or perhaps something that `ddtrace` could address when in a test environment. Thus avoid consuming apps from having to stub the request.

Here's a partial stack trace when running in rspec:

```
#<Thread:0x0000556d2b5fc3a8@/home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/workers.rb:78 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	24: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/workers.rb:78:in `block (2 levels) in start'
	23: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/workers.rb:112:in `perform'
	22: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/workers.rb:112:in `loop'
	21: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/workers.rb:113:in `block in perform'
	20: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/workers.rb:53:in `callback_traces'
	19: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/writer.rb:54:in `block in start'
	18: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/writer.rb:83:in `send_spans'
	17: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/traces.rb:28:in `send_traces'
	16: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/client.rb:27:in `send_request'
	15: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/traces.rb:29:in `block in send_traces'
	14: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/traces.rb:67:in `send_traces'
	13: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/traces.rb:45:in `send_traces'
	12: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/traces.rb:114:in `call'
	11: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/api/endpoint.rb:21:in `call'
	10: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/traces.rb:68:in `block in send_traces'
	 9: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/api/instance.rb:23:in `call'
	 8: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/adapters/net.rb:31:in `call'
	 7: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/adapters/net.rb:42:in `post'
	 6: from /home/********/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/transport/http/adapters/net.rb:24:in `open'
	 5: from /usr/local/lib/ruby/2.6.0/net/http.rb:605:in `start'
.....
You can stub this request with the following snippet:
stub_request(:post, "http://localhost:8126/v0.4/traces") with ...
```

**Comment by delner** [comment]
Hey @andrewthauer, is this running in your test suite? I'm not sure what would've changed to break this (also can't see an exception message from the output?)

My suggestion would be to use our test adapter in your test suite, which will short-circuit this trace flush and prevent the HTTP call, optionally putting the output into a buffer of your choice instead.

Check out this for more details: https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#using-the-transport-test-adapter

**Comment by andrewthauer** [comment]
@delner - Sorry I cut off the actual error message:

```
.../ruby/2.6.2/lib/ruby/gems/2.6.0/gems/webmock-3.7.5/lib/webmock/http_lib_adapters/net_http.rb:114:in `request': Real HTTP connections are disabled. Unregistered request: POST http://localhost:8126/v0.4/traces with body  .... (WebMock::NetConnectNotAllowedError)
```

I've tried configuring the test adapter in the `spec_helper` and it doesn't seem to be making a difference. Any further thoughts?

**Comment by delner** [comment]
If the adapter is configured properly, it definitely shouldn't make any HTTP calls. I would advise sharing your configuration and inspecting `Datadog.tracer.writer.transport` to see if the test adapter is setup.

**Comment by andrewthauer** [comment]
Ok, now I see the issue. I have a rails initializer that was calling `Datadog.configure` before the spec helper sets the test adapter. From what I'm seeing it seems you can only call `tracer` ones as part of the configure? I was able to fix this by checking for a test environment in the initialization code. However, I don't consider that ideal. Is there a way to override the transport_options after the initial configure call to avoid this?

**Comment by delner** [comment]
Yeah, I believe its possible to replace the transport by calling `Datadog.tracer.configure(transport_options: { ... })`, which I think you could do from your `spec_helper`.

Just be mindful that reconfiguring like this will replace the existing `Datadog::Writer` and `Datadog::Transport`, which could effectively overwrite any custom `c.tracer` options set in your initializer. (`Writer` and `Transport` are immutable components.)

**Comment by andrewthauer** [comment]
Thanks. I think that should be fine in this case considering we effectively want the tracing to be a no-op in any test environment (and won't be run as part of any other environment). If this is the case, perhaps the README should be updated to reflect using `Datadog.tracer.configure` rather then use the `Datadog.configure` block.

**Comment by andrewthauer** [comment]
So using `Datadog.tracer.configure` didn't work either. I now think it's due to the AsyncWriter being used. I can fix it using the `Datadog.configure` or `Datadog.tracer.configure` approaches, if I add a `sleep` after.

I found #903 and tried using a SyncWriter which seems related. If I do the following if fixes the original issue:

```rb
Datadog.tracer.configure(
  transport_options: proc { |t| t.adapter :test, [] },
  writer: Datadog::SyncWriter.new(
    transport: Datadog::Transport::HTTP.default { |t| t.adapter :test, [] }
  ),
)
```

However, now I get this error when the test suite ends (which will fail the test run with an error code)

`ruby/2.6.2/lib/ruby/gems/2.6.0/gems/ddtrace-0.31.0/lib/ddtrace/tracer.rb:53:in `shutdown!': undefined method `stop' for #<Datadog::SyncWriter:0x00007fe566edba40> (NoMethodError)`

I have a feeling this might be the approach I'm after, if there wasn't the NoMetehodError.

At this point, the only successful way, that I've been able to get my tests to successfully run is to tack on the test adapter to the original tracer config in my initializer (when it's in the test environment).

**Comment by delner** [comment]
Oh yeah, the `NoMethodError stop` is a known bug, we're in the process of fixing that. For a test suite, you probably do want to use the `SyncWriter`.

**Comment by andrewthauer** [comment]
Thanks @delner! I'm currently using the test env check to configure on initialization. Once #915 is released, I'll try that out instead.

I'm going to close this issue. However, I think it would be helpful if the readme/docs provided a little more clarity on setup for testing. Currently it seems a little subjective and it seems like the approach we've discussed here would could be an commonly used pattern for most folks.

**Comment by delner** [comment]
Yeah I think that's a good idea. Thanks for the suggestion @andrewthauer.

**Comment by louiscb** [comment]
I followed the above steps but couldn't get my test suite passing. The issue was the Telemetry calls Datadog was making. So I ended up writing this to my Datadog initialiser file, it works but feels a bit hacky:

```
  if ::Rails.env.test?
    c.tracing.transport_options = proc { |t|
      t.adapter :test
    }
    c.telemetry.enabled = false
  end
```

**Comment by ivoanjo** [comment]
Yeah, it sounds like you're experiencing https://github.com/DataDog/dd-trace-rb/issues/2823 :|
