### ISSUE TITLE
status code no longer tracked on rack requests when upgrading to 0.31.0

### ISSUE THREAD

**Issue by dkassen** [DataDog/dd-trace-rb#939]
Hi DataDog team,
We have a graph that stopped showing data when we upgraded ddtrace from 0.26.0 to 0.31.0

The graph metric is trace.rack.request.hits.by_http_status

We've tried adding the `TRACE_DD_ANALYTICS_ENABLED` env variable and adding the key `analytics_enabled: true` to our initializer, but that didn't seem to fix the issue.

Please let me know if there is anything more you need.

**Comment by delner** [comment]
Hey @dkassen, I think HTTP status code was tagged as numeric in 0.31.0, but then we reverted it to a string in [0.31.1](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.31.1). I would upgrade to the latest, see if that helps.

**Comment by dkassen** [comment]
That did it, thanks @delner

**Comment by delner** [comment]
Thanks!
