### ISSUE TITLE
Disable DD Ruby tracer in the same way as DD Java tracer

### ISSUE THREAD

**Issue by KIVagant** [DataDog/dd-trace-rb#941]
https://github.com/DataDog/dd-trace-java/pull/824

> Environment Variable: DD_TRACE_ENABLED=false

Please add support of the variable for Ruby tracer.

**Comment by delner** [comment]
Seems fairly straightforward, will look into adding this ENV var; thanks!

**Comment by ericmustin** [comment]
@KIVagant hey there, hope all is well. Just for tracking purposes, this env var got added as part of larger work recently merged here: https://github.com/DataDog/dd-trace-rb/pull/1115 . will update this issue when this work has been released.

**Comment by KIVagant** [comment]
Thank you for the update, @ericmustin

**Comment by marcotc** [comment]
👋  @KIVagant, we've just released [0.39.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.39.0), which adds consistent environment variables with our other supported languages.
