### ISSUE TITLE
Service Name Prefix

### ISSUE THREAD

**Issue by allcentury** [DataDog/dd-trace-rb#959]
I have a question about `service_name` configuration options when using something like:

```ruby
...
c.use :redis, service_name: "#{app_name}-redis"
c.use :rake, service_name: "#{app_name}-rake"
```

We have dozen of services who have many of the same integrations and I'm wondering if there is a benefit to having those services grouped together or to have separate service names.  None of these apps share caches, or databases, so we currently have each `service_name` prefixed with the app name.

If prefixing is your recommendation would you be open to a `prefix` config value so I can stop doing the above and instead do:

```ruby
c.service_name_prefix = "my_app"
```

then each `default` value will simply prepend the prefix to the default name.

**Comment by delner** [comment]
Hey @allcentury ! We actually had this requested via #513 previously, so I will close this one in favor of that issue. Happy to continue the conversation there; thanks!
