### ISSUE TITLE
Support for Hanami

### ISSUE THREAD

**Issue by patrobinson** [DataDog/dd-trace-rb#979]
Hanami apps instrumented with ddtrace don't include proper Resource Names. Even when configuring `middleware_names` and setting `application` to the `Hanami.app` we run, it only resolves to `Hanami::Router`. This is due to the way Hanami executes an application, specifically it calls `compile` on a class, which calls `instance_eval` to dynamically build an application at runtime.
This makes monkey patching impossible I believe.

It'd be nice if someone came up with a solution to this.

**Comment by delner** [comment]
Would love to add first-class support for Hanami. Will bring this to the team; thanks!

**Comment by skcc321** [comment]
any updates?

**Comment by delner** [comment]
At the moment, no. It's on our (very large) list of things to do, and we'll be considering this task, among others, for our schedule soon.

**Comment by ivoanjo** [comment]
Hanami instrumentation was added in https://github.com/DataDog/dd-trace-rb/pull/2230 so I'm going ahead and close this ticket ;)
