### ISSUE TITLE
partial_flush appears to only partially work / unbounded memory growth

### ISSUE THREAD

**Issue by draaglom** [DataDog/dd-trace-rb#984]
## Problem

Performing a traced sidekiq operation with large numbers of inner ActiveRecord spans appears to use unbounded memory, even with partial_flush enabled.

It appears that the spans themselves are flushed and removed from context, but something about the dd-trace instrumentation means that copies of every inner SQL operation are retained in memory until the root trace completes.

I suspect this may be a universal issue, but it's particularly applicable to Sidekiq and other delayed job style services - where it's more likely that real code will be doing very large numbers of sub-operations.

## Steps to reproduce

Example code:

```ruby
class Example
  include Sidekiq::Worker

  def perform
    1_000_000.times do |i|
       # For each iteration, we perform some ActiveRecord operation. Objects
       # allocated here by application code can be GCd away between loop iterations
       # - so without dd-trace-rb this uses ~constant memory.
       # With dd-trace-rb enabled, we appear to keep track of one span per ActiveRecord
       # operation below, including the full query string.
       SomeModel.find(i)
     end
   end
end

Example.perform_async
```

## Expected behaviour

* process memory usage remains a constant multiple above what it would be without ddtrace (e.g. no more than 1.5x)

## Actual behaviour

* Process heap grows linearly with number of operations performed in a single trace
* Dumping the heap with ObjectSpace.dump_all reveals the raw SQL of every AR operation is retained in a hash referenced by ActiveRecord::ConnectionAdapters::PostgreSQLAdapter

## Any details you can share about your configuration including:

 * Ruby version & platform: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
 * ddtrace version: 0.33.1
 * rails 5.2.1
 * Any configuration settings for the trace library (e.g. initializers/datadog.rb): the behaviour seems to be the same with `partial_flush` `true` or `false` - maybe I've misunderstood the intent of this config option?

**Comment by delner** [comment]
Hey @draaglom !

Partial flush is supposed to effectively cap this; it's meant to scan for and regularly flush eligible spans from traces after the trace crosses a certain threshold (I think something like 500 spans by default), and after doing so should release the memory through the usual Ruby GC cycle.

We also do have hard limits on the number of spans that can exist within a single trace (which I think is at 100K right now) that's normally applied when partial flushing is not active. When that limit is reached, it will drop all new spans, retaining spans up to the size limit.

If you're seeing memory grow indefinitely, some possibilities include 1) partial flushing isn't active, 2) partial flushing isn't flushing, 3) memory isn't being released properly after a flush, 4) limits/thresholds somehow aren't working.

When you've run this test, did you see any spans/traces being flushed? Activating debug mode in `ddtrace` (only do this in a safe test environment, its too verbose for production) or tailing trace agent logs will show trace data being sent and received respectively. It may not show up in the UI until the root span flushes (which probably won't happen until the trace completes.)

The example you gave me is pretty straightforward; I'll see if we can run through this ourselves and replicate the issue you're seeing. Thanks for sharing this!

**Comment by draaglom** [comment]
hey @delner! thanks for the in-depth response.

From here it looks like:

* Partial flushing is active

* Adding logging here https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/context_flush.rb#L55 seemed to indicate that we are in fact flushing! I'd missed the debug mode so I did things the hard way.

* Memory isn't being released after a flush. I've been dumping the heap with `ObjectSpace.dump_all` and what I see is:
  * A hash with references to unbounded numbers of raw sql strings
  * That hash is referenced by an instance of `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter`

So I think I may have jumped the gun on identifying this as spans being kept in memory per se --  it's now seeming like something inside the adapter, whose behaviour is changed by including/not including dd-trace.

Here's my initializers/datadog.rb:

```ruby
require 'ddtrace'

Datadog.configure do |c|
  c.tracer enabled: ENV['DATADOG_APM_ENABLED'] == '1',
           env: Rails.env,
           hostname: ENV['DATADOG_APM_HOST'] || 'localhost',
           port: ENV['DATADOG_APM_PORT'] || 8_126,
           analytics_enabled: false,
           partial_flush: true
  c.use :rails, service_name: 'luna', database_service: 'postgres'
  c.use :sidekiq, service_name: 'luna-sidekiq'
  c.use :redis
  c.use :aws
end
```

Toggling the `:sidekiq` instrumentation toggles on/off the issue.

**Comment by draaglom** [comment]
Updated the issue to better reflect my current understanding.

**Comment by delner** [comment]
Out of curiosity, have you tried some other instrumented operation instead of ActiveRecord's `#find`? Like say a Redis `#get` or something similar?

I'd like to see if a specific operation being repeated 1M times, or repeating any operation 1M times is the driving factor here. If the prior, then maybe its a SQL adapter + instrumentation problem, if the latter, then maybe a problem with partial flushing.

**Comment by draaglom** [comment]
Good shout.

I can confirm with the following code:

```ruby
# Sidekiq initializer
require 'rbtrace'
```

```ruby
class Example
  include Sidekiq::Worker

  def perform
    1_000_000.times do |i|
      $redis.get('test_key')
    end
  end
end
```

I see redis operations GC'd correctly:

```bash
bundle exec rbtrace -p <pid> -e 'Thread.new{GC.start;require "objspace";i=File.open("/tmp/r.dump","w");ObjectSpace.dump_all(output: i);i.close}'

grep -r 'GET test_key' /tmp/r.dump |  wc -l
```

The count does not grow unboundedly. So it seems something specific to the AR integration.

**Comment by marcotc** [comment]
This is super helpful to help us narrow the problem down, thank you @draaglom!
We'll dig deeper into the specific integration issues.

**Comment by draaglom** [comment]
no worries @marcotc! I'm going to keep on digging on my side as well.

**Comment by draaglom** [comment]
So, it turns out that this issue was not related to Datadog after all -- I'm positive I tested before / after disabling the sidekiq ddtrace integration, but I guess I must've been caught out by making other concurrent changes.

As it turns out, the ActiveRecord query cache really is just unbounded.

Cheers for the responsiveness on this ticket anyhow, @delner @marcotc  - hope you both have a great day!

**Comment by d11wtq** [comment]
We're observing this too, but not specifically in Sidekiq. We have long running jobs that have a `Datadog.tracer.span` around them, and we get OOM issues on those jobs. We've been able to replicate in the Rails console what happens over time in terms of memory usage if we run the main method from the job (but without all the job baggage wrapped around it), and then running the same code again with Datadog tracing around it. Partial flushing seems to do very little here. The code in question is really just run _a lot_ of ActiveRecord queries.

Without Datadog tracing (log lines are memory usage in kilobytes):

```
irb> perform(dw_table: 'dw_transactions') { print_memory_usage }
387348
445008
540500
498032
527064
501524
515884
456388
511676
517720
519716
531684
548896
518748
518172
529900
533396
533816
523876
552924
566788
556880
534652
527588
526540
523604
526780
519492
522748
517308
541032
545888
551764
558652
567352
550828
517876
513768
531416
545924
544376
537188
532744
547436
546736
550692
560660
528624
```

That's just typical Ruby object allocation -> GC cycles.

Now the same code running for the same amount of time (15 minutes) but with a `Datadog.tracer.span` around it:

```
irb> Datadog.tracer.trace("rails.console", service: "maintenance") { perform(dw_table: 'dw_transactions') { print_memory_usage } }
436692
442972
440872
420884
428444
449656
470540
533524
536984
538508
508760
532120
560116
570044
570996
568556
569492
572540
580228
579572
583564
577360
577364
575264
576872
568932
571632
587364
579812
597272
588812
563120
597928
635096
643144
616252
640856
647732
655812
641592
647196
655500
664752
663248
661672
661920
661212
663228
652360
682872
736532
754036
772896
775456
778328
767804
790068
810136
814640
785276
826528
```

It is very unfortunate that a tool we rely on for metrics is the very thing that is responsible for memory leaks. Is there not some way you can avoid collecting the data in memory and instead periodically write it to a temp file on disk or some such so it does not forever increase memory usage, then when the span completes, collect whatever is in the temp file?

**Comment by brookemckim** [comment]
I am also seeing this with a long running very memory intensive process in Sidekiq. I thought at first it was the ActiveRecord query cache, but completely disabling datadog is the only thing that fixes the issue. 

```ruby
  Datadog.configure do |c|
    c.env = Rails.env
    c.use :sidekiq, service_name: 'core-sidekiq', client_service_name: 'core-sidekiq-client'
    c.use :rails, service_name: 'core'
    c.use :redis, service_name: 'core-redis'
    c.use :aws, service_name: 'core-aws'
    c.runtime_metrics.enabled = true
    c.tracer.partial_flush.enabled = true
  end
```

![Screen Shot 2022-04-05 at 6 06 43 PM](https://user-images.githubusercontent.com/245680/161857742-60263f34-12f9-4cd7-9af8-418030e2c7de.png)

I have not tried `1.0` and am currently on `0.54.2`

**Comment by ivoanjo** [comment]
@brookemckim thanks for the report!

Can I ask you to open a new ticket with it, either via https://www.datadoghq.com/support/ or directly on GitHub, so we can follow up and investigate?
