### ISSUE TITLE
Environment and variables documentation

### ISSUE THREAD

**Issue by rahul342** [DataDog/dd-trace-rb#989]
Following the instruction https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#environment-and-tags

I set the `c.env` and `c.tags` in my initializer (rails), both of which return  `undefined method tags= for #<Datadog::Configuration::Settings`

Am I doing this wrong or is the documentation outdated?

Also the link says, you can use `DD_TAGS` as well,
```DD_TAGS: Custom tags in value pairs separated by , (e.g. layer:api,team:intake)```
but does that work only for Docker agents? (that's the only place i see reference to this)
Also in the example, the tags are comma separated, but docker documentations says it should be space separate.

Separately, not sure if you guys can help, been trying to work with support people, but it's extremely slow and takes a while to figure it out with them. All I am trying to do is add an extra tag (e.g. `sub_env`) that I can filter trace metrics (e.g. `trace.rack.request.hits`) by and use it as a primary tag on APM, but I have tried multiple things, the above being one of them, but it just doesn't work. So far, I have tried passing tags to `c.tracer` args which shows up in individual traces but no in span, I added ` ad.datadoghq.com/tags: '{"sub_env": "primary"}'` in my pod spec; this shows up under tag on infrastructure but not still picked up by traces. How can I make this work?

**Comment by rahul342** [comment]
Just realized this is part of the latest release. I upgraded the gem, and it `undefined method ` issue was gone.  But after deploying it doesn't seem to be functioning the way I thought it would
Previous code
```
  c.tracer enabled: Rails.env.production? || Rails.env.staging?,
           hostname: ENV['DD_AGENT_SERVICE_HOST'],
           port: ENV['DD_AGENT_SERVICE_PORT'],
           env: Rails.env
```

Code after
```
 c.tracer enabled: Rails.env.production? || Rails.env.staging?,
           hostname: ENV['DD_AGENT_SERVICE_HOST'],
           port: ENV['DD_AGENT_SERVICE_PORT']

  c.env = Rails.env
```

Latter code started grouping them under `env:none` 😞

**Comment by delner** [comment]
Thanks for the report, will look into this. I think it might not be updating the `env` tag on the tracer properly. Alternatively you can set this with an env var `DD_ENV` and it should work.

**Comment by delner** [comment]
@rahul342 Opened #990 which should hopefully address this. Can you test this branch, see if it resolves the issue? If so, we can push out a bugfix release soon.

**Comment by rahul342** [comment]
Would #990 set the tags as well such that it become filterable on the dashboards for traces metric?

**Comment by delner** [comment]
Not sure what you mean, but it will set tags on traces and runtime/health metrics. I'm not sure if trace tags are propagated to the auto-generated trace metrics; those metrics are generated in the trace agent not this library.

**Comment by rahul342** [comment]
I see
> Can you test this branch, see if it resolves the issue? 
Is there any other way to test it besides deploying your branch on production?

**Comment by delner** [comment]
Yes, you can use this pre-release gem:

```ruby
source 'http://gems.datadoghq.com/prerelease' do
  gem 'ddtrace', '0.34.0.fix.no.config.updates.58591'
end
```

**Comment by rahul342** [comment]
Fix seems to be working.

**Comment by rahul342** [comment]
@delner sorry for the direct tag, one last question.

Per this [documentation](https://docs.datadoghq.com/tagging/assigning_tags/?tab=ruby#traces), it says 
> When submitting a single trace, tag its spans to **override Agent configuration tags and/or the host tags** value (if any) for those traces:

we are trying to do that by passing `tags` hash to the `c.tracer` in initialization, but it doesn't seem to override? Would this be related to something in this library?

**Comment by delner** [comment]
So you can set tags directly on a trace via the manual instrumentation: `Datadog.tracer.trace('my.operation') { |span| span.set_tag('my-tag', 'my-value') }`

Or set tags for all traces (manual instrumentation & integrations) via this `Datadog.configure { |c| c.tags = { 'my-tag' => 'my-value' } }`. Using `Datadog.configure { |c| c.tracer tags: { 'my-tag' => 'my-value' } }` is the same as `Datadog.tracer.set_tags( 'my-tag' => 'my-value')`, but both of these methods are the old way of doing it and will be deprecated in the future in favor of `#tags=`.

And I believe you can also set tags at the agent level as well (you'd have to see the documentation for that.)

These tags take precedence in order from top to bottom, if they somehow overlap.

**Comment by kelvin-acosta** [comment]
I am still having this issue on 0.35.1 `c.env` and `c.tags` isn't having the traces show up under the correct env. They are instead showing up under `env:none`

**Comment by delner** [comment]
Hi @kelvin-acosta if you can share your code or an example that reproduces the issue, that'd help us understand what's going on.

**Comment by kelvin-acosta** [comment]
@delner Hey sorry for not providing context here, I created this issue with some code https://github.com/DataDog/dd-trace-rb/issues/1032.

**Comment by delner** [comment]
Cool, no problem, we'll pickup the conversation there.
