### ISSUE TITLE
[0.34.1] Debug trace exploding...

### ISSUE THREAD

**Issue by MrAtheist** [DataDog/dd-trace-rb#998]
## Issue

Just updated to 0.34.1 and i've noticed that the amount of logs spitting from ddtrace just exploded...
It didnt happen in 0.33.1.

**running ruby 2.6.5**
```
D, [2020-04-07T20:07:17.417021 #80] DEBUG -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.34.1/lib/ddtrace/tracer.rb:338:in `write') Writing 5 spans (enabled: true)
Name: active_record.instantiation
Span ID: 8174943679064881956
Parent ID: 0
Trace ID: 4313094538369338513
Type: custom
Service: active_record
Resource: hello
Error: 0
Start: 1586372655861069568
End: 1586372655880161792
Duration: 19092170
Allocations: 16030
Tags:[...MORE...]
Metrics: [...A LOT MORE...ok maybe not]
```

Each transaction is spitting out one of those! right now im looking at ~10k lines a minute.

Below is the config. Relatively quiet under 0.33.1, but exploded in 0.34.1
```
Datadog.configure do |c|
    c.tracer enabled: true
    c.tracer debug: true
...
```
At first i thought it's from the `debug` attribute, but nop. I switched to false and didnt make a difference. I'm going to try false on the `enabled` next. If that doesnt work i'm going have to downgrade... Just want to raise the issue here to see if anyone else is experience the same.

**Comment by delner** [comment]
There shouldn't be any changes that materially affect debug logging or ActiveRecord between 0.33.1 and 0.34.1. ActiveRecord applications are known to produce many instantiation spans for each SQL query made, so this may not be unusual depending on your application.

We do not recommend enabled `debug` in any production or other sensitive environment, as it is very verbose. The messages you're seeing are the spans in every trace produced: this can easily and quickly overwhelm logs and you probably don't want it on unless debugging tracer output in a safe environment.

I would ensure that `debug: false`. You can also verify the log level manually by checking `Datadog::Logger.debug_logging` (which should be `false`) and `Datadog::Logger.log.debug?` (which should also be `false`.)

**Comment by MrAtheist** [comment]
Closing this as the issue magically disappeared... Still end up with `c.tracer debug: false`
